package com.kysoft.cpsi.zcb.mapper;

import com.kysoft.cpsi.zcb.entity.SctDwtz;
import com.kysoft.cpsi.zcb.entity.SctDwtzKey;

public interface SctDwtzMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SCT_DWTZ
     *
     * @mbg.generated Tue Jan 03 14:17:25 CST 2017
     */
    int deleteByPrimaryKey(SctDwtzKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SCT_DWTZ
     *
     * @mbg.generated Tue Jan 03 14:17:25 CST 2017
     */
    int insert(SctDwtz record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SCT_DWTZ
     *
     * @mbg.generated Tue Jan 03 14:17:25 CST 2017
     */
    int insertSelective(SctDwtz record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SCT_DWTZ
     *
     * @mbg.generated Tue Jan 03 14:17:25 CST 2017
     */
    SctDwtz selectByPrimaryKey(SctDwtzKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SCT_DWTZ
     *
     * @mbg.generated Tue Jan 03 14:17:25 CST 2017
     */
    int updateByPrimaryKeySelective(SctDwtz record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SCT_DWTZ
     *
     * @mbg.generated Tue Jan 03 14:17:25 CST 2017
     */
    int updateByPrimaryKey(SctDwtz record);
}