package com.kysoft.cpsi.zcb.mapper;

import com.kysoft.cpsi.zcb.entity.SctXzcf;
import com.kysoft.cpsi.zcb.entity.SctXzcfKey;

public interface SctXzcfMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SCT_XZCF
     *
     * @mbg.generated Tue Jan 03 14:17:25 CST 2017
     */
    int deleteByPrimaryKey(SctXzcfKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SCT_XZCF
     *
     * @mbg.generated Tue Jan 03 14:17:25 CST 2017
     */
    int insert(SctXzcf record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SCT_XZCF
     *
     * @mbg.generated Tue Jan 03 14:17:25 CST 2017
     */
    int insertSelective(SctXzcf record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SCT_XZCF
     *
     * @mbg.generated Tue Jan 03 14:17:25 CST 2017
     */
    SctXzcf selectByPrimaryKey(SctXzcfKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SCT_XZCF
     *
     * @mbg.generated Tue Jan 03 14:17:25 CST 2017
     */
    int updateByPrimaryKeySelective(SctXzcf record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SCT_XZCF
     *
     * @mbg.generated Tue Jan 03 14:17:25 CST 2017
     */
    int updateByPrimaryKey(SctXzcf record);
}