package com.kysoft.cpsi.zcb.mapper;

import com.kysoft.cpsi.zcb.entity.SctXzxk;
import com.kysoft.cpsi.zcb.entity.SctXzxkKey;

public interface SctXzxkMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SCT_XZXK
     *
     * @mbg.generated Tue Jan 03 14:17:25 CST 2017
     */
    int deleteByPrimaryKey(SctXzxkKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SCT_XZXK
     *
     * @mbg.generated Tue Jan 03 14:17:25 CST 2017
     */
    int insert(SctXzxk record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SCT_XZXK
     *
     * @mbg.generated Tue Jan 03 14:17:25 CST 2017
     */
    int insertSelective(SctXzxk record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SCT_XZXK
     *
     * @mbg.generated Tue Jan 03 14:17:25 CST 2017
     */
    SctXzxk selectByPrimaryKey(SctXzxkKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SCT_XZXK
     *
     * @mbg.generated Tue Jan 03 14:17:25 CST 2017
     */
    int updateByPrimaryKeySelective(SctXzxk record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SCT_XZXK
     *
     * @mbg.generated Tue Jan 03 14:17:25 CST 2017
     */
    int updateByPrimaryKey(SctXzxk record);
}