package com.kysoft.cpsi.zcb.mapper;

import com.kysoft.cpsi.zcb.entity.SctZcfzb;
import com.kysoft.cpsi.zcb.entity.SctZcfzbKey;

public interface SctZcfzbMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SCT_ZCFZB
     *
     * @mbg.generated Tue Jan 03 14:17:25 CST 2017
     */
    int deleteByPrimaryKey(SctZcfzbKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SCT_ZCFZB
     *
     * @mbg.generated Tue Jan 03 14:17:25 CST 2017
     */
    int insert(SctZcfzb record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SCT_ZCFZB
     *
     * @mbg.generated Tue Jan 03 14:17:25 CST 2017
     */
    int insertSelective(SctZcfzb record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SCT_ZCFZB
     *
     * @mbg.generated Tue Jan 03 14:17:25 CST 2017
     */
    SctZcfzb selectByPrimaryKey(SctZcfzbKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SCT_ZCFZB
     *
     * @mbg.generated Tue Jan 03 14:17:25 CST 2017
     */
    int updateByPrimaryKeySelective(SctZcfzb record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SCT_ZCFZB
     *
     * @mbg.generated Tue Jan 03 14:17:25 CST 2017
     */
    int updateByPrimaryKey(SctZcfzb record);
}