package com.kysoft.cpsi.zcb.entity;

import java.util.Date;

public class SctDwdb extends SctDwdbKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SCT_DWDB.TBRQ
     *
     * @mbg.generated Tue Jan 03 14:17:25 CST 2017
     */
    private Date tbrq;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SCT_DWDB.ZQR
     *
     * @mbg.generated Tue Jan 03 14:17:25 CST 2017
     */
    private String zqr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SCT_DWDB.ZWR
     *
     * @mbg.generated Tue Jan 03 14:17:25 CST 2017
     */
    private String zwr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SCT_DWDB.ZZQZL
     *
     * @mbg.generated Tue Jan 03 14:17:25 CST 2017
     */
    private String zzqzl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SCT_DWDB.ZZQSE
     *
     * @mbg.generated Tue Jan 03 14:17:25 CST 2017
     */
    private Float zzqse;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SCT_DWDB.LXZWQX
     *
     * @mbg.generated Tue Jan 03 14:17:25 CST 2017
     */
    private Date lxzwqx;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SCT_DWDB.BZQJ
     *
     * @mbg.generated Tue Jan 03 14:17:25 CST 2017
     */
    private String bzqj;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SCT_DWDB.BZFS
     *
     * @mbg.generated Tue Jan 03 14:17:25 CST 2017
     */
    private String bzfs;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SCT_DWDB.BZDBFW
     *
     * @mbg.generated Tue Jan 03 14:17:25 CST 2017
     */
    private String bzdbfw;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SCT_DWDB.TBRQ
     *
     * @return the value of SCT_DWDB.TBRQ
     *
     * @mbg.generated Tue Jan 03 14:17:25 CST 2017
     */
    public Date getTbrq() {
        return tbrq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SCT_DWDB.TBRQ
     *
     * @param tbrq the value for SCT_DWDB.TBRQ
     *
     * @mbg.generated Tue Jan 03 14:17:25 CST 2017
     */
    public void setTbrq(Date tbrq) {
        this.tbrq = tbrq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SCT_DWDB.ZQR
     *
     * @return the value of SCT_DWDB.ZQR
     *
     * @mbg.generated Tue Jan 03 14:17:25 CST 2017
     */
    public String getZqr() {
        return zqr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SCT_DWDB.ZQR
     *
     * @param zqr the value for SCT_DWDB.ZQR
     *
     * @mbg.generated Tue Jan 03 14:17:25 CST 2017
     */
    public void setZqr(String zqr) {
        this.zqr = zqr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SCT_DWDB.ZWR
     *
     * @return the value of SCT_DWDB.ZWR
     *
     * @mbg.generated Tue Jan 03 14:17:25 CST 2017
     */
    public String getZwr() {
        return zwr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SCT_DWDB.ZWR
     *
     * @param zwr the value for SCT_DWDB.ZWR
     *
     * @mbg.generated Tue Jan 03 14:17:25 CST 2017
     */
    public void setZwr(String zwr) {
        this.zwr = zwr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SCT_DWDB.ZZQZL
     *
     * @return the value of SCT_DWDB.ZZQZL
     *
     * @mbg.generated Tue Jan 03 14:17:25 CST 2017
     */
    public String getZzqzl() {
        return zzqzl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SCT_DWDB.ZZQZL
     *
     * @param zzqzl the value for SCT_DWDB.ZZQZL
     *
     * @mbg.generated Tue Jan 03 14:17:25 CST 2017
     */
    public void setZzqzl(String zzqzl) {
        this.zzqzl = zzqzl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SCT_DWDB.ZZQSE
     *
     * @return the value of SCT_DWDB.ZZQSE
     *
     * @mbg.generated Tue Jan 03 14:17:25 CST 2017
     */
    public Float getZzqse() {
        return zzqse;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SCT_DWDB.ZZQSE
     *
     * @param zzqse the value for SCT_DWDB.ZZQSE
     *
     * @mbg.generated Tue Jan 03 14:17:25 CST 2017
     */
    public void setZzqse(Float zzqse) {
        this.zzqse = zzqse;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SCT_DWDB.LXZWQX
     *
     * @return the value of SCT_DWDB.LXZWQX
     *
     * @mbg.generated Tue Jan 03 14:17:25 CST 2017
     */
    public Date getLxzwqx() {
        return lxzwqx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SCT_DWDB.LXZWQX
     *
     * @param lxzwqx the value for SCT_DWDB.LXZWQX
     *
     * @mbg.generated Tue Jan 03 14:17:25 CST 2017
     */
    public void setLxzwqx(Date lxzwqx) {
        this.lxzwqx = lxzwqx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SCT_DWDB.BZQJ
     *
     * @return the value of SCT_DWDB.BZQJ
     *
     * @mbg.generated Tue Jan 03 14:17:25 CST 2017
     */
    public String getBzqj() {
        return bzqj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SCT_DWDB.BZQJ
     *
     * @param bzqj the value for SCT_DWDB.BZQJ
     *
     * @mbg.generated Tue Jan 03 14:17:25 CST 2017
     */
    public void setBzqj(String bzqj) {
        this.bzqj = bzqj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SCT_DWDB.BZFS
     *
     * @return the value of SCT_DWDB.BZFS
     *
     * @mbg.generated Tue Jan 03 14:17:25 CST 2017
     */
    public String getBzfs() {
        return bzfs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SCT_DWDB.BZFS
     *
     * @param bzfs the value for SCT_DWDB.BZFS
     *
     * @mbg.generated Tue Jan 03 14:17:25 CST 2017
     */
    public void setBzfs(String bzfs) {
        this.bzfs = bzfs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SCT_DWDB.BZDBFW
     *
     * @return the value of SCT_DWDB.BZDBFW
     *
     * @mbg.generated Tue Jan 03 14:17:25 CST 2017
     */
    public String getBzdbfw() {
        return bzdbfw;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SCT_DWDB.BZDBFW
     *
     * @param bzdbfw the value for SCT_DWDB.BZDBFW
     *
     * @mbg.generated Tue Jan 03 14:17:25 CST 2017
     */
    public void setBzdbfw(String bzdbfw) {
        this.bzdbfw = bzdbfw;
    }
}