package com.kysoft.cpsi.zcb.entity;

import java.util.Date;

public class SctGqbg extends SctGqbgKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SCT_GQBG.TBRQ
     *
     * @mbg.generated Tue Jan 03 14:17:25 CST 2017
     */
    private Date tbrq;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SCT_GQBG.GD
     *
     * @mbg.generated Tue Jan 03 14:17:25 CST 2017
     */
    private String gd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SCT_GQBG.BGQBL
     *
     * @mbg.generated Tue Jan 03 14:17:25 CST 2017
     */
    private Float bgqbl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SCT_GQBG.BGHBL
     *
     * @mbg.generated Tue Jan 03 14:17:25 CST 2017
     */
    private Float bghbl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SCT_GQBG.JZRQ
     *
     * @mbg.generated Tue Jan 03 14:17:25 CST 2017
     */
    private Date jzrq;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SCT_GQBG.PZH
     *
     * @mbg.generated Tue Jan 03 14:17:25 CST 2017
     */
    private String pzh;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SCT_GQBG.TBRQ
     *
     * @return the value of SCT_GQBG.TBRQ
     *
     * @mbg.generated Tue Jan 03 14:17:25 CST 2017
     */
    public Date getTbrq() {
        return tbrq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SCT_GQBG.TBRQ
     *
     * @param tbrq the value for SCT_GQBG.TBRQ
     *
     * @mbg.generated Tue Jan 03 14:17:25 CST 2017
     */
    public void setTbrq(Date tbrq) {
        this.tbrq = tbrq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SCT_GQBG.GD
     *
     * @return the value of SCT_GQBG.GD
     *
     * @mbg.generated Tue Jan 03 14:17:25 CST 2017
     */
    public String getGd() {
        return gd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SCT_GQBG.GD
     *
     * @param gd the value for SCT_GQBG.GD
     *
     * @mbg.generated Tue Jan 03 14:17:25 CST 2017
     */
    public void setGd(String gd) {
        this.gd = gd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SCT_GQBG.BGQBL
     *
     * @return the value of SCT_GQBG.BGQBL
     *
     * @mbg.generated Tue Jan 03 14:17:25 CST 2017
     */
    public Float getBgqbl() {
        return bgqbl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SCT_GQBG.BGQBL
     *
     * @param bgqbl the value for SCT_GQBG.BGQBL
     *
     * @mbg.generated Tue Jan 03 14:17:25 CST 2017
     */
    public void setBgqbl(Float bgqbl) {
        this.bgqbl = bgqbl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SCT_GQBG.BGHBL
     *
     * @return the value of SCT_GQBG.BGHBL
     *
     * @mbg.generated Tue Jan 03 14:17:25 CST 2017
     */
    public Float getBghbl() {
        return bghbl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SCT_GQBG.BGHBL
     *
     * @param bghbl the value for SCT_GQBG.BGHBL
     *
     * @mbg.generated Tue Jan 03 14:17:25 CST 2017
     */
    public void setBghbl(Float bghbl) {
        this.bghbl = bghbl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SCT_GQBG.JZRQ
     *
     * @return the value of SCT_GQBG.JZRQ
     *
     * @mbg.generated Tue Jan 03 14:17:25 CST 2017
     */
    public Date getJzrq() {
        return jzrq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SCT_GQBG.JZRQ
     *
     * @param jzrq the value for SCT_GQBG.JZRQ
     *
     * @mbg.generated Tue Jan 03 14:17:25 CST 2017
     */
    public void setJzrq(Date jzrq) {
        this.jzrq = jzrq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SCT_GQBG.PZH
     *
     * @return the value of SCT_GQBG.PZH
     *
     * @mbg.generated Tue Jan 03 14:17:25 CST 2017
     */
    public String getPzh() {
        return pzh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SCT_GQBG.PZH
     *
     * @param pzh the value for SCT_GQBG.PZH
     *
     * @mbg.generated Tue Jan 03 14:17:25 CST 2017
     */
    public void setPzh(String pzh) {
        this.pzh = pzh;
    }
}