package com.kysoft.cpsi.zcb.entity;

import java.util.Date;

public class SctLrb extends SctLrbKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SCT_LRB.TBRQ
     *
     * @mbg.generated Tue Jan 03 14:17:25 CST 2017
     */
    private Date tbrq;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SCT_LRB.ITEM1_BQFSE
     *
     * @mbg.generated Tue Jan 03 14:17:25 CST 2017
     */
    private Float item1Bqfse;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SCT_LRB.ITEM1_SQFSE
     *
     * @mbg.generated Tue Jan 03 14:17:25 CST 2017
     */
    private Float item1Sqfse;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SCT_LRB.ITEM2_BQFSE
     *
     * @mbg.generated Tue Jan 03 14:17:25 CST 2017
     */
    private Float item2Bqfse;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SCT_LRB.ITEM2_SQFSE
     *
     * @mbg.generated Tue Jan 03 14:17:25 CST 2017
     */
    private Float item2Sqfse;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SCT_LRB.ITEM3_BQFSE
     *
     * @mbg.generated Tue Jan 03 14:17:25 CST 2017
     */
    private Float item3Bqfse;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SCT_LRB.ITEM3_SQFSE
     *
     * @mbg.generated Tue Jan 03 14:17:25 CST 2017
     */
    private Float item3Sqfse;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SCT_LRB.ITEM4_BQFSE
     *
     * @mbg.generated Tue Jan 03 14:17:25 CST 2017
     */
    private Float item4Bqfse;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SCT_LRB.ITEM4_SQFSE
     *
     * @mbg.generated Tue Jan 03 14:17:25 CST 2017
     */
    private Float item4Sqfse;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SCT_LRB.ITEM5_BQFSE
     *
     * @mbg.generated Tue Jan 03 14:17:25 CST 2017
     */
    private Float item5Bqfse;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SCT_LRB.ITEM5_SQFSE
     *
     * @mbg.generated Tue Jan 03 14:17:25 CST 2017
     */
    private Float item5Sqfse;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SCT_LRB.ITEM6_BQFSE
     *
     * @mbg.generated Tue Jan 03 14:17:25 CST 2017
     */
    private Float item6Bqfse;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SCT_LRB.ITEM6_SQFSE
     *
     * @mbg.generated Tue Jan 03 14:17:25 CST 2017
     */
    private Float item6Sqfse;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SCT_LRB.ITEM7_BQFSE
     *
     * @mbg.generated Tue Jan 03 14:17:25 CST 2017
     */
    private Float item7Bqfse;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SCT_LRB.ITEM7_SQFSE
     *
     * @mbg.generated Tue Jan 03 14:17:25 CST 2017
     */
    private Float item7Sqfse;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SCT_LRB.ITEM8_BQFSE
     *
     * @mbg.generated Tue Jan 03 14:17:25 CST 2017
     */
    private Float item8Bqfse;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SCT_LRB.ITEM8_SQFSE
     *
     * @mbg.generated Tue Jan 03 14:17:25 CST 2017
     */
    private Float item8Sqfse;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SCT_LRB.ITEM9_BQFSE
     *
     * @mbg.generated Tue Jan 03 14:17:25 CST 2017
     */
    private Float item9Bqfse;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SCT_LRB.ITEM9_SQFSE
     *
     * @mbg.generated Tue Jan 03 14:17:25 CST 2017
     */
    private Float item9Sqfse;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SCT_LRB.ITEM10_BQFSE
     *
     * @mbg.generated Tue Jan 03 14:17:25 CST 2017
     */
    private Float item10Bqfse;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SCT_LRB.ITEM10_SQFSE
     *
     * @mbg.generated Tue Jan 03 14:17:25 CST 2017
     */
    private Float item10Sqfse;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SCT_LRB.ITEM11_BQFSE
     *
     * @mbg.generated Tue Jan 03 14:17:25 CST 2017
     */
    private Float item11Bqfse;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SCT_LRB.ITEM11_SQFSE
     *
     * @mbg.generated Tue Jan 03 14:17:25 CST 2017
     */
    private Float item11Sqfse;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SCT_LRB.ITEM12_BQFSE
     *
     * @mbg.generated Tue Jan 03 14:17:25 CST 2017
     */
    private Float item12Bqfse;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SCT_LRB.ITEM12_SQFSE
     *
     * @mbg.generated Tue Jan 03 14:17:25 CST 2017
     */
    private Float item12Sqfse;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SCT_LRB.ITEM13_BQFSE
     *
     * @mbg.generated Tue Jan 03 14:17:25 CST 2017
     */
    private Float item13Bqfse;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SCT_LRB.ITEM13_SQFSE
     *
     * @mbg.generated Tue Jan 03 14:17:25 CST 2017
     */
    private Float item13Sqfse;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SCT_LRB.ITEM14_BQFSE
     *
     * @mbg.generated Tue Jan 03 14:17:25 CST 2017
     */
    private Float item14Bqfse;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SCT_LRB.ITEM14_SQFSE
     *
     * @mbg.generated Tue Jan 03 14:17:25 CST 2017
     */
    private Float item14Sqfse;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SCT_LRB.ITEM15_BQFSE
     *
     * @mbg.generated Tue Jan 03 14:17:25 CST 2017
     */
    private Float item15Bqfse;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SCT_LRB.ITEM15_SQFSE
     *
     * @mbg.generated Tue Jan 03 14:17:25 CST 2017
     */
    private Float item15Sqfse;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SCT_LRB.ITEM16_BQFSE
     *
     * @mbg.generated Tue Jan 03 14:17:25 CST 2017
     */
    private Float item16Bqfse;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SCT_LRB.ITEM16_SQFSE
     *
     * @mbg.generated Tue Jan 03 14:17:25 CST 2017
     */
    private Float item16Sqfse;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SCT_LRB.ITEM17_BQFSE
     *
     * @mbg.generated Tue Jan 03 14:17:25 CST 2017
     */
    private Float item17Bqfse;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SCT_LRB.ITEM17_SQFSE
     *
     * @mbg.generated Tue Jan 03 14:17:25 CST 2017
     */
    private Float item17Sqfse;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SCT_LRB.ITEM18_BQFSE
     *
     * @mbg.generated Tue Jan 03 14:17:25 CST 2017
     */
    private Float item18Bqfse;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SCT_LRB.ITEM18_SQFSE
     *
     * @mbg.generated Tue Jan 03 14:17:25 CST 2017
     */
    private Float item18Sqfse;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SCT_LRB.ITEM19_BQFSE
     *
     * @mbg.generated Tue Jan 03 14:17:25 CST 2017
     */
    private Float item19Bqfse;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SCT_LRB.ITEM19_SQFSE
     *
     * @mbg.generated Tue Jan 03 14:17:25 CST 2017
     */
    private Float item19Sqfse;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SCT_LRB.ITEM20_BQFSE
     *
     * @mbg.generated Tue Jan 03 14:17:25 CST 2017
     */
    private Float item20Bqfse;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SCT_LRB.ITEM20_SQFSE
     *
     * @mbg.generated Tue Jan 03 14:17:25 CST 2017
     */
    private Float item20Sqfse;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SCT_LRB.ITEM21_BQFSE
     *
     * @mbg.generated Tue Jan 03 14:17:25 CST 2017
     */
    private Float item21Bqfse;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SCT_LRB.ITEM21_SQFSE
     *
     * @mbg.generated Tue Jan 03 14:17:25 CST 2017
     */
    private Float item21Sqfse;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SCT_LRB.ITEM22_BQFSE
     *
     * @mbg.generated Tue Jan 03 14:17:25 CST 2017
     */
    private Float item22Bqfse;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SCT_LRB.ITEM22_SQFSE
     *
     * @mbg.generated Tue Jan 03 14:17:25 CST 2017
     */
    private Float item22Sqfse;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SCT_LRB.ITEM23_BQFSE
     *
     * @mbg.generated Tue Jan 03 14:17:25 CST 2017
     */
    private Float item23Bqfse;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SCT_LRB.ITEM23_SQFSE
     *
     * @mbg.generated Tue Jan 03 14:17:25 CST 2017
     */
    private Float item23Sqfse;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SCT_LRB.ITEM24_BQFSE
     *
     * @mbg.generated Tue Jan 03 14:17:25 CST 2017
     */
    private Float item24Bqfse;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SCT_LRB.ITEM24_SQFSE
     *
     * @mbg.generated Tue Jan 03 14:17:25 CST 2017
     */
    private Float item24Sqfse;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SCT_LRB.ITEM25_BQFSE
     *
     * @mbg.generated Tue Jan 03 14:17:25 CST 2017
     */
    private Float item25Bqfse;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SCT_LRB.ITEM25_SQFSE
     *
     * @mbg.generated Tue Jan 03 14:17:25 CST 2017
     */
    private Float item25Sqfse;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SCT_LRB.ITEM26_BQFSE
     *
     * @mbg.generated Tue Jan 03 14:17:25 CST 2017
     */
    private Float item26Bqfse;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SCT_LRB.ITEM26_SQFSE
     *
     * @mbg.generated Tue Jan 03 14:17:25 CST 2017
     */
    private Float item26Sqfse;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SCT_LRB.ITEM27_BQFSE
     *
     * @mbg.generated Tue Jan 03 14:17:25 CST 2017
     */
    private Float item27Bqfse;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SCT_LRB.ITEM27_SQFSE
     *
     * @mbg.generated Tue Jan 03 14:17:25 CST 2017
     */
    private Float item27Sqfse;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SCT_LRB.ITEM28_BQFSE
     *
     * @mbg.generated Tue Jan 03 14:17:25 CST 2017
     */
    private Float item28Bqfse;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SCT_LRB.ITEM28_SQFSE
     *
     * @mbg.generated Tue Jan 03 14:17:25 CST 2017
     */
    private Float item28Sqfse;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SCT_LRB.ITEM29_BQFSE
     *
     * @mbg.generated Tue Jan 03 14:17:25 CST 2017
     */
    private Float item29Bqfse;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SCT_LRB.ITEM29_SQFSE
     *
     * @mbg.generated Tue Jan 03 14:17:25 CST 2017
     */
    private Float item29Sqfse;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SCT_LRB.ITEM30_BQFSE
     *
     * @mbg.generated Tue Jan 03 14:17:25 CST 2017
     */
    private Float item30Bqfse;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SCT_LRB.ITEM30_SQFSE
     *
     * @mbg.generated Tue Jan 03 14:17:25 CST 2017
     */
    private Float item30Sqfse;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SCT_LRB.ITEM31_BQFSE
     *
     * @mbg.generated Tue Jan 03 14:17:25 CST 2017
     */
    private Float item31Bqfse;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SCT_LRB.ITEM31_SQFSE
     *
     * @mbg.generated Tue Jan 03 14:17:25 CST 2017
     */
    private Float item31Sqfse;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SCT_LRB.ITEM32_BQFSE
     *
     * @mbg.generated Tue Jan 03 14:17:25 CST 2017
     */
    private Float item32Bqfse;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SCT_LRB.ITEM32_SQFSE
     *
     * @mbg.generated Tue Jan 03 14:17:25 CST 2017
     */
    private Float item32Sqfse;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SCT_LRB.ITEM33_BQFSE
     *
     * @mbg.generated Tue Jan 03 14:17:25 CST 2017
     */
    private Float item33Bqfse;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SCT_LRB.ITEM33_SQFSE
     *
     * @mbg.generated Tue Jan 03 14:17:25 CST 2017
     */
    private Float item33Sqfse;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SCT_LRB.ITEM34_BQFSE
     *
     * @mbg.generated Tue Jan 03 14:17:25 CST 2017
     */
    private Float item34Bqfse;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SCT_LRB.ITEM34_SQFSE
     *
     * @mbg.generated Tue Jan 03 14:17:25 CST 2017
     */
    private Float item34Sqfse;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SCT_LRB.ITEM35_BQFSE
     *
     * @mbg.generated Tue Jan 03 14:17:25 CST 2017
     */
    private Float item35Bqfse;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SCT_LRB.ITEM35_SQFSE
     *
     * @mbg.generated Tue Jan 03 14:17:25 CST 2017
     */
    private Float item35Sqfse;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SCT_LRB.ITEM36_BQFSE
     *
     * @mbg.generated Tue Jan 03 14:17:25 CST 2017
     */
    private Float item36Bqfse;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SCT_LRB.ITEM36_SQFSE
     *
     * @mbg.generated Tue Jan 03 14:17:25 CST 2017
     */
    private Float item36Sqfse;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SCT_LRB.ITEM37_BQFSE
     *
     * @mbg.generated Tue Jan 03 14:17:25 CST 2017
     */
    private Float item37Bqfse;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SCT_LRB.ITEM37_SQFSE
     *
     * @mbg.generated Tue Jan 03 14:17:25 CST 2017
     */
    private Float item37Sqfse;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SCT_LRB.ITEM38_BQFSE
     *
     * @mbg.generated Tue Jan 03 14:17:25 CST 2017
     */
    private Float item38Bqfse;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SCT_LRB.ITEM38_SQFSE
     *
     * @mbg.generated Tue Jan 03 14:17:25 CST 2017
     */
    private Float item38Sqfse;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SCT_LRB.ITEM39_BQFSE
     *
     * @mbg.generated Tue Jan 03 14:17:25 CST 2017
     */
    private Float item39Bqfse;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SCT_LRB.ITEM39_SQFSE
     *
     * @mbg.generated Tue Jan 03 14:17:25 CST 2017
     */
    private Float item39Sqfse;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SCT_LRB.ITEM40_BQFSE
     *
     * @mbg.generated Tue Jan 03 14:17:25 CST 2017
     */
    private Float item40Bqfse;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SCT_LRB.ITEM40_SQFSE
     *
     * @mbg.generated Tue Jan 03 14:17:25 CST 2017
     */
    private Float item40Sqfse;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SCT_LRB.ITEM41_BQFSE
     *
     * @mbg.generated Tue Jan 03 14:17:25 CST 2017
     */
    private Float item41Bqfse;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SCT_LRB.ITEM41_SQFSE
     *
     * @mbg.generated Tue Jan 03 14:17:25 CST 2017
     */
    private Float item41Sqfse;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SCT_LRB.ITEM42_BQFSE
     *
     * @mbg.generated Tue Jan 03 14:17:25 CST 2017
     */
    private Float item42Bqfse;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SCT_LRB.ITEM42_SQFSE
     *
     * @mbg.generated Tue Jan 03 14:17:25 CST 2017
     */
    private Float item42Sqfse;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SCT_LRB.ITEM43_BQFSE
     *
     * @mbg.generated Tue Jan 03 14:17:25 CST 2017
     */
    private Float item43Bqfse;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SCT_LRB.ITEM43_SQFSE
     *
     * @mbg.generated Tue Jan 03 14:17:25 CST 2017
     */
    private Float item43Sqfse;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SCT_LRB.ITEM44_BQFSE
     *
     * @mbg.generated Tue Jan 03 14:17:25 CST 2017
     */
    private Float item44Bqfse;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SCT_LRB.ITEM44_SQFSE
     *
     * @mbg.generated Tue Jan 03 14:17:25 CST 2017
     */
    private Float item44Sqfse;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SCT_LRB.ITEM45_BQFSE
     *
     * @mbg.generated Tue Jan 03 14:17:25 CST 2017
     */
    private Float item45Bqfse;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SCT_LRB.ITEM45_SQFSE
     *
     * @mbg.generated Tue Jan 03 14:17:25 CST 2017
     */
    private Float item45Sqfse;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SCT_LRB.ITEM46_BQFSE
     *
     * @mbg.generated Tue Jan 03 14:17:25 CST 2017
     */
    private Float item46Bqfse;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SCT_LRB.ITEM46_SQFSE
     *
     * @mbg.generated Tue Jan 03 14:17:25 CST 2017
     */
    private Float item46Sqfse;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SCT_LRB.ITEM47_BQFSE
     *
     * @mbg.generated Tue Jan 03 14:17:25 CST 2017
     */
    private Float item47Bqfse;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SCT_LRB.ITEM47_SQFSE
     *
     * @mbg.generated Tue Jan 03 14:17:25 CST 2017
     */
    private Float item47Sqfse;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SCT_LRB.ITEM48_BQFSE
     *
     * @mbg.generated Tue Jan 03 14:17:25 CST 2017
     */
    private Float item48Bqfse;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SCT_LRB.ITEM48_SQFSE
     *
     * @mbg.generated Tue Jan 03 14:17:25 CST 2017
     */
    private Float item48Sqfse;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SCT_LRB.ITEM49_BQFSE
     *
     * @mbg.generated Tue Jan 03 14:17:25 CST 2017
     */
    private Float item49Bqfse;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SCT_LRB.ITEM49_SQFSE
     *
     * @mbg.generated Tue Jan 03 14:17:25 CST 2017
     */
    private Float item49Sqfse;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SCT_LRB.ITEM50_BQFSE
     *
     * @mbg.generated Tue Jan 03 14:17:25 CST 2017
     */
    private Float item50Bqfse;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SCT_LRB.ITEM50_SQFSE
     *
     * @mbg.generated Tue Jan 03 14:17:25 CST 2017
     */
    private Float item50Sqfse;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SCT_LRB.TBRQ
     *
     * @return the value of SCT_LRB.TBRQ
     *
     * @mbg.generated Tue Jan 03 14:17:25 CST 2017
     */
    public Date getTbrq() {
        return tbrq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SCT_LRB.TBRQ
     *
     * @param tbrq the value for SCT_LRB.TBRQ
     *
     * @mbg.generated Tue Jan 03 14:17:25 CST 2017
     */
    public void setTbrq(Date tbrq) {
        this.tbrq = tbrq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SCT_LRB.ITEM1_BQFSE
     *
     * @return the value of SCT_LRB.ITEM1_BQFSE
     *
     * @mbg.generated Tue Jan 03 14:17:25 CST 2017
     */
    public Float getItem1Bqfse() {
        return item1Bqfse;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SCT_LRB.ITEM1_BQFSE
     *
     * @param item1Bqfse the value for SCT_LRB.ITEM1_BQFSE
     *
     * @mbg.generated Tue Jan 03 14:17:25 CST 2017
     */
    public void setItem1Bqfse(Float item1Bqfse) {
        this.item1Bqfse = item1Bqfse;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SCT_LRB.ITEM1_SQFSE
     *
     * @return the value of SCT_LRB.ITEM1_SQFSE
     *
     * @mbg.generated Tue Jan 03 14:17:25 CST 2017
     */
    public Float getItem1Sqfse() {
        return item1Sqfse;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SCT_LRB.ITEM1_SQFSE
     *
     * @param item1Sqfse the value for SCT_LRB.ITEM1_SQFSE
     *
     * @mbg.generated Tue Jan 03 14:17:25 CST 2017
     */
    public void setItem1Sqfse(Float item1Sqfse) {
        this.item1Sqfse = item1Sqfse;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SCT_LRB.ITEM2_BQFSE
     *
     * @return the value of SCT_LRB.ITEM2_BQFSE
     *
     * @mbg.generated Tue Jan 03 14:17:25 CST 2017
     */
    public Float getItem2Bqfse() {
        return item2Bqfse;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SCT_LRB.ITEM2_BQFSE
     *
     * @param item2Bqfse the value for SCT_LRB.ITEM2_BQFSE
     *
     * @mbg.generated Tue Jan 03 14:17:25 CST 2017
     */
    public void setItem2Bqfse(Float item2Bqfse) {
        this.item2Bqfse = item2Bqfse;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SCT_LRB.ITEM2_SQFSE
     *
     * @return the value of SCT_LRB.ITEM2_SQFSE
     *
     * @mbg.generated Tue Jan 03 14:17:25 CST 2017
     */
    public Float getItem2Sqfse() {
        return item2Sqfse;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SCT_LRB.ITEM2_SQFSE
     *
     * @param item2Sqfse the value for SCT_LRB.ITEM2_SQFSE
     *
     * @mbg.generated Tue Jan 03 14:17:25 CST 2017
     */
    public void setItem2Sqfse(Float item2Sqfse) {
        this.item2Sqfse = item2Sqfse;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SCT_LRB.ITEM3_BQFSE
     *
     * @return the value of SCT_LRB.ITEM3_BQFSE
     *
     * @mbg.generated Tue Jan 03 14:17:25 CST 2017
     */
    public Float getItem3Bqfse() {
        return item3Bqfse;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SCT_LRB.ITEM3_BQFSE
     *
     * @param item3Bqfse the value for SCT_LRB.ITEM3_BQFSE
     *
     * @mbg.generated Tue Jan 03 14:17:25 CST 2017
     */
    public void setItem3Bqfse(Float item3Bqfse) {
        this.item3Bqfse = item3Bqfse;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SCT_LRB.ITEM3_SQFSE
     *
     * @return the value of SCT_LRB.ITEM3_SQFSE
     *
     * @mbg.generated Tue Jan 03 14:17:25 CST 2017
     */
    public Float getItem3Sqfse() {
        return item3Sqfse;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SCT_LRB.ITEM3_SQFSE
     *
     * @param item3Sqfse the value for SCT_LRB.ITEM3_SQFSE
     *
     * @mbg.generated Tue Jan 03 14:17:25 CST 2017
     */
    public void setItem3Sqfse(Float item3Sqfse) {
        this.item3Sqfse = item3Sqfse;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SCT_LRB.ITEM4_BQFSE
     *
     * @return the value of SCT_LRB.ITEM4_BQFSE
     *
     * @mbg.generated Tue Jan 03 14:17:25 CST 2017
     */
    public Float getItem4Bqfse() {
        return item4Bqfse;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SCT_LRB.ITEM4_BQFSE
     *
     * @param item4Bqfse the value for SCT_LRB.ITEM4_BQFSE
     *
     * @mbg.generated Tue Jan 03 14:17:25 CST 2017
     */
    public void setItem4Bqfse(Float item4Bqfse) {
        this.item4Bqfse = item4Bqfse;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SCT_LRB.ITEM4_SQFSE
     *
     * @return the value of SCT_LRB.ITEM4_SQFSE
     *
     * @mbg.generated Tue Jan 03 14:17:25 CST 2017
     */
    public Float getItem4Sqfse() {
        return item4Sqfse;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SCT_LRB.ITEM4_SQFSE
     *
     * @param item4Sqfse the value for SCT_LRB.ITEM4_SQFSE
     *
     * @mbg.generated Tue Jan 03 14:17:25 CST 2017
     */
    public void setItem4Sqfse(Float item4Sqfse) {
        this.item4Sqfse = item4Sqfse;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SCT_LRB.ITEM5_BQFSE
     *
     * @return the value of SCT_LRB.ITEM5_BQFSE
     *
     * @mbg.generated Tue Jan 03 14:17:25 CST 2017
     */
    public Float getItem5Bqfse() {
        return item5Bqfse;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SCT_LRB.ITEM5_BQFSE
     *
     * @param item5Bqfse the value for SCT_LRB.ITEM5_BQFSE
     *
     * @mbg.generated Tue Jan 03 14:17:25 CST 2017
     */
    public void setItem5Bqfse(Float item5Bqfse) {
        this.item5Bqfse = item5Bqfse;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SCT_LRB.ITEM5_SQFSE
     *
     * @return the value of SCT_LRB.ITEM5_SQFSE
     *
     * @mbg.generated Tue Jan 03 14:17:25 CST 2017
     */
    public Float getItem5Sqfse() {
        return item5Sqfse;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SCT_LRB.ITEM5_SQFSE
     *
     * @param item5Sqfse the value for SCT_LRB.ITEM5_SQFSE
     *
     * @mbg.generated Tue Jan 03 14:17:25 CST 2017
     */
    public void setItem5Sqfse(Float item5Sqfse) {
        this.item5Sqfse = item5Sqfse;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SCT_LRB.ITEM6_BQFSE
     *
     * @return the value of SCT_LRB.ITEM6_BQFSE
     *
     * @mbg.generated Tue Jan 03 14:17:25 CST 2017
     */
    public Float getItem6Bqfse() {
        return item6Bqfse;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SCT_LRB.ITEM6_BQFSE
     *
     * @param item6Bqfse the value for SCT_LRB.ITEM6_BQFSE
     *
     * @mbg.generated Tue Jan 03 14:17:25 CST 2017
     */
    public void setItem6Bqfse(Float item6Bqfse) {
        this.item6Bqfse = item6Bqfse;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SCT_LRB.ITEM6_SQFSE
     *
     * @return the value of SCT_LRB.ITEM6_SQFSE
     *
     * @mbg.generated Tue Jan 03 14:17:25 CST 2017
     */
    public Float getItem6Sqfse() {
        return item6Sqfse;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SCT_LRB.ITEM6_SQFSE
     *
     * @param item6Sqfse the value for SCT_LRB.ITEM6_SQFSE
     *
     * @mbg.generated Tue Jan 03 14:17:25 CST 2017
     */
    public void setItem6Sqfse(Float item6Sqfse) {
        this.item6Sqfse = item6Sqfse;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SCT_LRB.ITEM7_BQFSE
     *
     * @return the value of SCT_LRB.ITEM7_BQFSE
     *
     * @mbg.generated Tue Jan 03 14:17:25 CST 2017
     */
    public Float getItem7Bqfse() {
        return item7Bqfse;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SCT_LRB.ITEM7_BQFSE
     *
     * @param item7Bqfse the value for SCT_LRB.ITEM7_BQFSE
     *
     * @mbg.generated Tue Jan 03 14:17:25 CST 2017
     */
    public void setItem7Bqfse(Float item7Bqfse) {
        this.item7Bqfse = item7Bqfse;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SCT_LRB.ITEM7_SQFSE
     *
     * @return the value of SCT_LRB.ITEM7_SQFSE
     *
     * @mbg.generated Tue Jan 03 14:17:25 CST 2017
     */
    public Float getItem7Sqfse() {
        return item7Sqfse;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SCT_LRB.ITEM7_SQFSE
     *
     * @param item7Sqfse the value for SCT_LRB.ITEM7_SQFSE
     *
     * @mbg.generated Tue Jan 03 14:17:25 CST 2017
     */
    public void setItem7Sqfse(Float item7Sqfse) {
        this.item7Sqfse = item7Sqfse;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SCT_LRB.ITEM8_BQFSE
     *
     * @return the value of SCT_LRB.ITEM8_BQFSE
     *
     * @mbg.generated Tue Jan 03 14:17:25 CST 2017
     */
    public Float getItem8Bqfse() {
        return item8Bqfse;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SCT_LRB.ITEM8_BQFSE
     *
     * @param item8Bqfse the value for SCT_LRB.ITEM8_BQFSE
     *
     * @mbg.generated Tue Jan 03 14:17:25 CST 2017
     */
    public void setItem8Bqfse(Float item8Bqfse) {
        this.item8Bqfse = item8Bqfse;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SCT_LRB.ITEM8_SQFSE
     *
     * @return the value of SCT_LRB.ITEM8_SQFSE
     *
     * @mbg.generated Tue Jan 03 14:17:25 CST 2017
     */
    public Float getItem8Sqfse() {
        return item8Sqfse;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SCT_LRB.ITEM8_SQFSE
     *
     * @param item8Sqfse the value for SCT_LRB.ITEM8_SQFSE
     *
     * @mbg.generated Tue Jan 03 14:17:25 CST 2017
     */
    public void setItem8Sqfse(Float item8Sqfse) {
        this.item8Sqfse = item8Sqfse;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SCT_LRB.ITEM9_BQFSE
     *
     * @return the value of SCT_LRB.ITEM9_BQFSE
     *
     * @mbg.generated Tue Jan 03 14:17:25 CST 2017
     */
    public Float getItem9Bqfse() {
        return item9Bqfse;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SCT_LRB.ITEM9_BQFSE
     *
     * @param item9Bqfse the value for SCT_LRB.ITEM9_BQFSE
     *
     * @mbg.generated Tue Jan 03 14:17:25 CST 2017
     */
    public void setItem9Bqfse(Float item9Bqfse) {
        this.item9Bqfse = item9Bqfse;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SCT_LRB.ITEM9_SQFSE
     *
     * @return the value of SCT_LRB.ITEM9_SQFSE
     *
     * @mbg.generated Tue Jan 03 14:17:25 CST 2017
     */
    public Float getItem9Sqfse() {
        return item9Sqfse;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SCT_LRB.ITEM9_SQFSE
     *
     * @param item9Sqfse the value for SCT_LRB.ITEM9_SQFSE
     *
     * @mbg.generated Tue Jan 03 14:17:25 CST 2017
     */
    public void setItem9Sqfse(Float item9Sqfse) {
        this.item9Sqfse = item9Sqfse;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SCT_LRB.ITEM10_BQFSE
     *
     * @return the value of SCT_LRB.ITEM10_BQFSE
     *
     * @mbg.generated Tue Jan 03 14:17:25 CST 2017
     */
    public Float getItem10Bqfse() {
        return item10Bqfse;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SCT_LRB.ITEM10_BQFSE
     *
     * @param item10Bqfse the value for SCT_LRB.ITEM10_BQFSE
     *
     * @mbg.generated Tue Jan 03 14:17:25 CST 2017
     */
    public void setItem10Bqfse(Float item10Bqfse) {
        this.item10Bqfse = item10Bqfse;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SCT_LRB.ITEM10_SQFSE
     *
     * @return the value of SCT_LRB.ITEM10_SQFSE
     *
     * @mbg.generated Tue Jan 03 14:17:25 CST 2017
     */
    public Float getItem10Sqfse() {
        return item10Sqfse;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SCT_LRB.ITEM10_SQFSE
     *
     * @param item10Sqfse the value for SCT_LRB.ITEM10_SQFSE
     *
     * @mbg.generated Tue Jan 03 14:17:25 CST 2017
     */
    public void setItem10Sqfse(Float item10Sqfse) {
        this.item10Sqfse = item10Sqfse;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SCT_LRB.ITEM11_BQFSE
     *
     * @return the value of SCT_LRB.ITEM11_BQFSE
     *
     * @mbg.generated Tue Jan 03 14:17:25 CST 2017
     */
    public Float getItem11Bqfse() {
        return item11Bqfse;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SCT_LRB.ITEM11_BQFSE
     *
     * @param item11Bqfse the value for SCT_LRB.ITEM11_BQFSE
     *
     * @mbg.generated Tue Jan 03 14:17:25 CST 2017
     */
    public void setItem11Bqfse(Float item11Bqfse) {
        this.item11Bqfse = item11Bqfse;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SCT_LRB.ITEM11_SQFSE
     *
     * @return the value of SCT_LRB.ITEM11_SQFSE
     *
     * @mbg.generated Tue Jan 03 14:17:25 CST 2017
     */
    public Float getItem11Sqfse() {
        return item11Sqfse;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SCT_LRB.ITEM11_SQFSE
     *
     * @param item11Sqfse the value for SCT_LRB.ITEM11_SQFSE
     *
     * @mbg.generated Tue Jan 03 14:17:25 CST 2017
     */
    public void setItem11Sqfse(Float item11Sqfse) {
        this.item11Sqfse = item11Sqfse;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SCT_LRB.ITEM12_BQFSE
     *
     * @return the value of SCT_LRB.ITEM12_BQFSE
     *
     * @mbg.generated Tue Jan 03 14:17:25 CST 2017
     */
    public Float getItem12Bqfse() {
        return item12Bqfse;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SCT_LRB.ITEM12_BQFSE
     *
     * @param item12Bqfse the value for SCT_LRB.ITEM12_BQFSE
     *
     * @mbg.generated Tue Jan 03 14:17:25 CST 2017
     */
    public void setItem12Bqfse(Float item12Bqfse) {
        this.item12Bqfse = item12Bqfse;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SCT_LRB.ITEM12_SQFSE
     *
     * @return the value of SCT_LRB.ITEM12_SQFSE
     *
     * @mbg.generated Tue Jan 03 14:17:25 CST 2017
     */
    public Float getItem12Sqfse() {
        return item12Sqfse;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SCT_LRB.ITEM12_SQFSE
     *
     * @param item12Sqfse the value for SCT_LRB.ITEM12_SQFSE
     *
     * @mbg.generated Tue Jan 03 14:17:25 CST 2017
     */
    public void setItem12Sqfse(Float item12Sqfse) {
        this.item12Sqfse = item12Sqfse;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SCT_LRB.ITEM13_BQFSE
     *
     * @return the value of SCT_LRB.ITEM13_BQFSE
     *
     * @mbg.generated Tue Jan 03 14:17:25 CST 2017
     */
    public Float getItem13Bqfse() {
        return item13Bqfse;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SCT_LRB.ITEM13_BQFSE
     *
     * @param item13Bqfse the value for SCT_LRB.ITEM13_BQFSE
     *
     * @mbg.generated Tue Jan 03 14:17:25 CST 2017
     */
    public void setItem13Bqfse(Float item13Bqfse) {
        this.item13Bqfse = item13Bqfse;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SCT_LRB.ITEM13_SQFSE
     *
     * @return the value of SCT_LRB.ITEM13_SQFSE
     *
     * @mbg.generated Tue Jan 03 14:17:25 CST 2017
     */
    public Float getItem13Sqfse() {
        return item13Sqfse;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SCT_LRB.ITEM13_SQFSE
     *
     * @param item13Sqfse the value for SCT_LRB.ITEM13_SQFSE
     *
     * @mbg.generated Tue Jan 03 14:17:25 CST 2017
     */
    public void setItem13Sqfse(Float item13Sqfse) {
        this.item13Sqfse = item13Sqfse;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SCT_LRB.ITEM14_BQFSE
     *
     * @return the value of SCT_LRB.ITEM14_BQFSE
     *
     * @mbg.generated Tue Jan 03 14:17:25 CST 2017
     */
    public Float getItem14Bqfse() {
        return item14Bqfse;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SCT_LRB.ITEM14_BQFSE
     *
     * @param item14Bqfse the value for SCT_LRB.ITEM14_BQFSE
     *
     * @mbg.generated Tue Jan 03 14:17:25 CST 2017
     */
    public void setItem14Bqfse(Float item14Bqfse) {
        this.item14Bqfse = item14Bqfse;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SCT_LRB.ITEM14_SQFSE
     *
     * @return the value of SCT_LRB.ITEM14_SQFSE
     *
     * @mbg.generated Tue Jan 03 14:17:25 CST 2017
     */
    public Float getItem14Sqfse() {
        return item14Sqfse;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SCT_LRB.ITEM14_SQFSE
     *
     * @param item14Sqfse the value for SCT_LRB.ITEM14_SQFSE
     *
     * @mbg.generated Tue Jan 03 14:17:25 CST 2017
     */
    public void setItem14Sqfse(Float item14Sqfse) {
        this.item14Sqfse = item14Sqfse;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SCT_LRB.ITEM15_BQFSE
     *
     * @return the value of SCT_LRB.ITEM15_BQFSE
     *
     * @mbg.generated Tue Jan 03 14:17:25 CST 2017
     */
    public Float getItem15Bqfse() {
        return item15Bqfse;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SCT_LRB.ITEM15_BQFSE
     *
     * @param item15Bqfse the value for SCT_LRB.ITEM15_BQFSE
     *
     * @mbg.generated Tue Jan 03 14:17:25 CST 2017
     */
    public void setItem15Bqfse(Float item15Bqfse) {
        this.item15Bqfse = item15Bqfse;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SCT_LRB.ITEM15_SQFSE
     *
     * @return the value of SCT_LRB.ITEM15_SQFSE
     *
     * @mbg.generated Tue Jan 03 14:17:25 CST 2017
     */
    public Float getItem15Sqfse() {
        return item15Sqfse;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SCT_LRB.ITEM15_SQFSE
     *
     * @param item15Sqfse the value for SCT_LRB.ITEM15_SQFSE
     *
     * @mbg.generated Tue Jan 03 14:17:25 CST 2017
     */
    public void setItem15Sqfse(Float item15Sqfse) {
        this.item15Sqfse = item15Sqfse;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SCT_LRB.ITEM16_BQFSE
     *
     * @return the value of SCT_LRB.ITEM16_BQFSE
     *
     * @mbg.generated Tue Jan 03 14:17:25 CST 2017
     */
    public Float getItem16Bqfse() {
        return item16Bqfse;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SCT_LRB.ITEM16_BQFSE
     *
     * @param item16Bqfse the value for SCT_LRB.ITEM16_BQFSE
     *
     * @mbg.generated Tue Jan 03 14:17:25 CST 2017
     */
    public void setItem16Bqfse(Float item16Bqfse) {
        this.item16Bqfse = item16Bqfse;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SCT_LRB.ITEM16_SQFSE
     *
     * @return the value of SCT_LRB.ITEM16_SQFSE
     *
     * @mbg.generated Tue Jan 03 14:17:25 CST 2017
     */
    public Float getItem16Sqfse() {
        return item16Sqfse;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SCT_LRB.ITEM16_SQFSE
     *
     * @param item16Sqfse the value for SCT_LRB.ITEM16_SQFSE
     *
     * @mbg.generated Tue Jan 03 14:17:25 CST 2017
     */
    public void setItem16Sqfse(Float item16Sqfse) {
        this.item16Sqfse = item16Sqfse;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SCT_LRB.ITEM17_BQFSE
     *
     * @return the value of SCT_LRB.ITEM17_BQFSE
     *
     * @mbg.generated Tue Jan 03 14:17:25 CST 2017
     */
    public Float getItem17Bqfse() {
        return item17Bqfse;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SCT_LRB.ITEM17_BQFSE
     *
     * @param item17Bqfse the value for SCT_LRB.ITEM17_BQFSE
     *
     * @mbg.generated Tue Jan 03 14:17:25 CST 2017
     */
    public void setItem17Bqfse(Float item17Bqfse) {
        this.item17Bqfse = item17Bqfse;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SCT_LRB.ITEM17_SQFSE
     *
     * @return the value of SCT_LRB.ITEM17_SQFSE
     *
     * @mbg.generated Tue Jan 03 14:17:25 CST 2017
     */
    public Float getItem17Sqfse() {
        return item17Sqfse;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SCT_LRB.ITEM17_SQFSE
     *
     * @param item17Sqfse the value for SCT_LRB.ITEM17_SQFSE
     *
     * @mbg.generated Tue Jan 03 14:17:25 CST 2017
     */
    public void setItem17Sqfse(Float item17Sqfse) {
        this.item17Sqfse = item17Sqfse;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SCT_LRB.ITEM18_BQFSE
     *
     * @return the value of SCT_LRB.ITEM18_BQFSE
     *
     * @mbg.generated Tue Jan 03 14:17:25 CST 2017
     */
    public Float getItem18Bqfse() {
        return item18Bqfse;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SCT_LRB.ITEM18_BQFSE
     *
     * @param item18Bqfse the value for SCT_LRB.ITEM18_BQFSE
     *
     * @mbg.generated Tue Jan 03 14:17:25 CST 2017
     */
    public void setItem18Bqfse(Float item18Bqfse) {
        this.item18Bqfse = item18Bqfse;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SCT_LRB.ITEM18_SQFSE
     *
     * @return the value of SCT_LRB.ITEM18_SQFSE
     *
     * @mbg.generated Tue Jan 03 14:17:25 CST 2017
     */
    public Float getItem18Sqfse() {
        return item18Sqfse;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SCT_LRB.ITEM18_SQFSE
     *
     * @param item18Sqfse the value for SCT_LRB.ITEM18_SQFSE
     *
     * @mbg.generated Tue Jan 03 14:17:25 CST 2017
     */
    public void setItem18Sqfse(Float item18Sqfse) {
        this.item18Sqfse = item18Sqfse;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SCT_LRB.ITEM19_BQFSE
     *
     * @return the value of SCT_LRB.ITEM19_BQFSE
     *
     * @mbg.generated Tue Jan 03 14:17:25 CST 2017
     */
    public Float getItem19Bqfse() {
        return item19Bqfse;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SCT_LRB.ITEM19_BQFSE
     *
     * @param item19Bqfse the value for SCT_LRB.ITEM19_BQFSE
     *
     * @mbg.generated Tue Jan 03 14:17:25 CST 2017
     */
    public void setItem19Bqfse(Float item19Bqfse) {
        this.item19Bqfse = item19Bqfse;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SCT_LRB.ITEM19_SQFSE
     *
     * @return the value of SCT_LRB.ITEM19_SQFSE
     *
     * @mbg.generated Tue Jan 03 14:17:25 CST 2017
     */
    public Float getItem19Sqfse() {
        return item19Sqfse;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SCT_LRB.ITEM19_SQFSE
     *
     * @param item19Sqfse the value for SCT_LRB.ITEM19_SQFSE
     *
     * @mbg.generated Tue Jan 03 14:17:25 CST 2017
     */
    public void setItem19Sqfse(Float item19Sqfse) {
        this.item19Sqfse = item19Sqfse;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SCT_LRB.ITEM20_BQFSE
     *
     * @return the value of SCT_LRB.ITEM20_BQFSE
     *
     * @mbg.generated Tue Jan 03 14:17:25 CST 2017
     */
    public Float getItem20Bqfse() {
        return item20Bqfse;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SCT_LRB.ITEM20_BQFSE
     *
     * @param item20Bqfse the value for SCT_LRB.ITEM20_BQFSE
     *
     * @mbg.generated Tue Jan 03 14:17:25 CST 2017
     */
    public void setItem20Bqfse(Float item20Bqfse) {
        this.item20Bqfse = item20Bqfse;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SCT_LRB.ITEM20_SQFSE
     *
     * @return the value of SCT_LRB.ITEM20_SQFSE
     *
     * @mbg.generated Tue Jan 03 14:17:25 CST 2017
     */
    public Float getItem20Sqfse() {
        return item20Sqfse;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SCT_LRB.ITEM20_SQFSE
     *
     * @param item20Sqfse the value for SCT_LRB.ITEM20_SQFSE
     *
     * @mbg.generated Tue Jan 03 14:17:25 CST 2017
     */
    public void setItem20Sqfse(Float item20Sqfse) {
        this.item20Sqfse = item20Sqfse;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SCT_LRB.ITEM21_BQFSE
     *
     * @return the value of SCT_LRB.ITEM21_BQFSE
     *
     * @mbg.generated Tue Jan 03 14:17:25 CST 2017
     */
    public Float getItem21Bqfse() {
        return item21Bqfse;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SCT_LRB.ITEM21_BQFSE
     *
     * @param item21Bqfse the value for SCT_LRB.ITEM21_BQFSE
     *
     * @mbg.generated Tue Jan 03 14:17:25 CST 2017
     */
    public void setItem21Bqfse(Float item21Bqfse) {
        this.item21Bqfse = item21Bqfse;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SCT_LRB.ITEM21_SQFSE
     *
     * @return the value of SCT_LRB.ITEM21_SQFSE
     *
     * @mbg.generated Tue Jan 03 14:17:25 CST 2017
     */
    public Float getItem21Sqfse() {
        return item21Sqfse;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SCT_LRB.ITEM21_SQFSE
     *
     * @param item21Sqfse the value for SCT_LRB.ITEM21_SQFSE
     *
     * @mbg.generated Tue Jan 03 14:17:25 CST 2017
     */
    public void setItem21Sqfse(Float item21Sqfse) {
        this.item21Sqfse = item21Sqfse;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SCT_LRB.ITEM22_BQFSE
     *
     * @return the value of SCT_LRB.ITEM22_BQFSE
     *
     * @mbg.generated Tue Jan 03 14:17:25 CST 2017
     */
    public Float getItem22Bqfse() {
        return item22Bqfse;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SCT_LRB.ITEM22_BQFSE
     *
     * @param item22Bqfse the value for SCT_LRB.ITEM22_BQFSE
     *
     * @mbg.generated Tue Jan 03 14:17:25 CST 2017
     */
    public void setItem22Bqfse(Float item22Bqfse) {
        this.item22Bqfse = item22Bqfse;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SCT_LRB.ITEM22_SQFSE
     *
     * @return the value of SCT_LRB.ITEM22_SQFSE
     *
     * @mbg.generated Tue Jan 03 14:17:25 CST 2017
     */
    public Float getItem22Sqfse() {
        return item22Sqfse;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SCT_LRB.ITEM22_SQFSE
     *
     * @param item22Sqfse the value for SCT_LRB.ITEM22_SQFSE
     *
     * @mbg.generated Tue Jan 03 14:17:25 CST 2017
     */
    public void setItem22Sqfse(Float item22Sqfse) {
        this.item22Sqfse = item22Sqfse;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SCT_LRB.ITEM23_BQFSE
     *
     * @return the value of SCT_LRB.ITEM23_BQFSE
     *
     * @mbg.generated Tue Jan 03 14:17:25 CST 2017
     */
    public Float getItem23Bqfse() {
        return item23Bqfse;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SCT_LRB.ITEM23_BQFSE
     *
     * @param item23Bqfse the value for SCT_LRB.ITEM23_BQFSE
     *
     * @mbg.generated Tue Jan 03 14:17:25 CST 2017
     */
    public void setItem23Bqfse(Float item23Bqfse) {
        this.item23Bqfse = item23Bqfse;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SCT_LRB.ITEM23_SQFSE
     *
     * @return the value of SCT_LRB.ITEM23_SQFSE
     *
     * @mbg.generated Tue Jan 03 14:17:25 CST 2017
     */
    public Float getItem23Sqfse() {
        return item23Sqfse;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SCT_LRB.ITEM23_SQFSE
     *
     * @param item23Sqfse the value for SCT_LRB.ITEM23_SQFSE
     *
     * @mbg.generated Tue Jan 03 14:17:25 CST 2017
     */
    public void setItem23Sqfse(Float item23Sqfse) {
        this.item23Sqfse = item23Sqfse;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SCT_LRB.ITEM24_BQFSE
     *
     * @return the value of SCT_LRB.ITEM24_BQFSE
     *
     * @mbg.generated Tue Jan 03 14:17:25 CST 2017
     */
    public Float getItem24Bqfse() {
        return item24Bqfse;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SCT_LRB.ITEM24_BQFSE
     *
     * @param item24Bqfse the value for SCT_LRB.ITEM24_BQFSE
     *
     * @mbg.generated Tue Jan 03 14:17:25 CST 2017
     */
    public void setItem24Bqfse(Float item24Bqfse) {
        this.item24Bqfse = item24Bqfse;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SCT_LRB.ITEM24_SQFSE
     *
     * @return the value of SCT_LRB.ITEM24_SQFSE
     *
     * @mbg.generated Tue Jan 03 14:17:25 CST 2017
     */
    public Float getItem24Sqfse() {
        return item24Sqfse;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SCT_LRB.ITEM24_SQFSE
     *
     * @param item24Sqfse the value for SCT_LRB.ITEM24_SQFSE
     *
     * @mbg.generated Tue Jan 03 14:17:25 CST 2017
     */
    public void setItem24Sqfse(Float item24Sqfse) {
        this.item24Sqfse = item24Sqfse;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SCT_LRB.ITEM25_BQFSE
     *
     * @return the value of SCT_LRB.ITEM25_BQFSE
     *
     * @mbg.generated Tue Jan 03 14:17:25 CST 2017
     */
    public Float getItem25Bqfse() {
        return item25Bqfse;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SCT_LRB.ITEM25_BQFSE
     *
     * @param item25Bqfse the value for SCT_LRB.ITEM25_BQFSE
     *
     * @mbg.generated Tue Jan 03 14:17:25 CST 2017
     */
    public void setItem25Bqfse(Float item25Bqfse) {
        this.item25Bqfse = item25Bqfse;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SCT_LRB.ITEM25_SQFSE
     *
     * @return the value of SCT_LRB.ITEM25_SQFSE
     *
     * @mbg.generated Tue Jan 03 14:17:25 CST 2017
     */
    public Float getItem25Sqfse() {
        return item25Sqfse;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SCT_LRB.ITEM25_SQFSE
     *
     * @param item25Sqfse the value for SCT_LRB.ITEM25_SQFSE
     *
     * @mbg.generated Tue Jan 03 14:17:25 CST 2017
     */
    public void setItem25Sqfse(Float item25Sqfse) {
        this.item25Sqfse = item25Sqfse;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SCT_LRB.ITEM26_BQFSE
     *
     * @return the value of SCT_LRB.ITEM26_BQFSE
     *
     * @mbg.generated Tue Jan 03 14:17:25 CST 2017
     */
    public Float getItem26Bqfse() {
        return item26Bqfse;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SCT_LRB.ITEM26_BQFSE
     *
     * @param item26Bqfse the value for SCT_LRB.ITEM26_BQFSE
     *
     * @mbg.generated Tue Jan 03 14:17:25 CST 2017
     */
    public void setItem26Bqfse(Float item26Bqfse) {
        this.item26Bqfse = item26Bqfse;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SCT_LRB.ITEM26_SQFSE
     *
     * @return the value of SCT_LRB.ITEM26_SQFSE
     *
     * @mbg.generated Tue Jan 03 14:17:25 CST 2017
     */
    public Float getItem26Sqfse() {
        return item26Sqfse;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SCT_LRB.ITEM26_SQFSE
     *
     * @param item26Sqfse the value for SCT_LRB.ITEM26_SQFSE
     *
     * @mbg.generated Tue Jan 03 14:17:25 CST 2017
     */
    public void setItem26Sqfse(Float item26Sqfse) {
        this.item26Sqfse = item26Sqfse;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SCT_LRB.ITEM27_BQFSE
     *
     * @return the value of SCT_LRB.ITEM27_BQFSE
     *
     * @mbg.generated Tue Jan 03 14:17:25 CST 2017
     */
    public Float getItem27Bqfse() {
        return item27Bqfse;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SCT_LRB.ITEM27_BQFSE
     *
     * @param item27Bqfse the value for SCT_LRB.ITEM27_BQFSE
     *
     * @mbg.generated Tue Jan 03 14:17:25 CST 2017
     */
    public void setItem27Bqfse(Float item27Bqfse) {
        this.item27Bqfse = item27Bqfse;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SCT_LRB.ITEM27_SQFSE
     *
     * @return the value of SCT_LRB.ITEM27_SQFSE
     *
     * @mbg.generated Tue Jan 03 14:17:25 CST 2017
     */
    public Float getItem27Sqfse() {
        return item27Sqfse;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SCT_LRB.ITEM27_SQFSE
     *
     * @param item27Sqfse the value for SCT_LRB.ITEM27_SQFSE
     *
     * @mbg.generated Tue Jan 03 14:17:25 CST 2017
     */
    public void setItem27Sqfse(Float item27Sqfse) {
        this.item27Sqfse = item27Sqfse;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SCT_LRB.ITEM28_BQFSE
     *
     * @return the value of SCT_LRB.ITEM28_BQFSE
     *
     * @mbg.generated Tue Jan 03 14:17:25 CST 2017
     */
    public Float getItem28Bqfse() {
        return item28Bqfse;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SCT_LRB.ITEM28_BQFSE
     *
     * @param item28Bqfse the value for SCT_LRB.ITEM28_BQFSE
     *
     * @mbg.generated Tue Jan 03 14:17:25 CST 2017
     */
    public void setItem28Bqfse(Float item28Bqfse) {
        this.item28Bqfse = item28Bqfse;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SCT_LRB.ITEM28_SQFSE
     *
     * @return the value of SCT_LRB.ITEM28_SQFSE
     *
     * @mbg.generated Tue Jan 03 14:17:25 CST 2017
     */
    public Float getItem28Sqfse() {
        return item28Sqfse;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SCT_LRB.ITEM28_SQFSE
     *
     * @param item28Sqfse the value for SCT_LRB.ITEM28_SQFSE
     *
     * @mbg.generated Tue Jan 03 14:17:25 CST 2017
     */
    public void setItem28Sqfse(Float item28Sqfse) {
        this.item28Sqfse = item28Sqfse;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SCT_LRB.ITEM29_BQFSE
     *
     * @return the value of SCT_LRB.ITEM29_BQFSE
     *
     * @mbg.generated Tue Jan 03 14:17:25 CST 2017
     */
    public Float getItem29Bqfse() {
        return item29Bqfse;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SCT_LRB.ITEM29_BQFSE
     *
     * @param item29Bqfse the value for SCT_LRB.ITEM29_BQFSE
     *
     * @mbg.generated Tue Jan 03 14:17:25 CST 2017
     */
    public void setItem29Bqfse(Float item29Bqfse) {
        this.item29Bqfse = item29Bqfse;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SCT_LRB.ITEM29_SQFSE
     *
     * @return the value of SCT_LRB.ITEM29_SQFSE
     *
     * @mbg.generated Tue Jan 03 14:17:25 CST 2017
     */
    public Float getItem29Sqfse() {
        return item29Sqfse;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SCT_LRB.ITEM29_SQFSE
     *
     * @param item29Sqfse the value for SCT_LRB.ITEM29_SQFSE
     *
     * @mbg.generated Tue Jan 03 14:17:25 CST 2017
     */
    public void setItem29Sqfse(Float item29Sqfse) {
        this.item29Sqfse = item29Sqfse;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SCT_LRB.ITEM30_BQFSE
     *
     * @return the value of SCT_LRB.ITEM30_BQFSE
     *
     * @mbg.generated Tue Jan 03 14:17:25 CST 2017
     */
    public Float getItem30Bqfse() {
        return item30Bqfse;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SCT_LRB.ITEM30_BQFSE
     *
     * @param item30Bqfse the value for SCT_LRB.ITEM30_BQFSE
     *
     * @mbg.generated Tue Jan 03 14:17:25 CST 2017
     */
    public void setItem30Bqfse(Float item30Bqfse) {
        this.item30Bqfse = item30Bqfse;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SCT_LRB.ITEM30_SQFSE
     *
     * @return the value of SCT_LRB.ITEM30_SQFSE
     *
     * @mbg.generated Tue Jan 03 14:17:25 CST 2017
     */
    public Float getItem30Sqfse() {
        return item30Sqfse;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SCT_LRB.ITEM30_SQFSE
     *
     * @param item30Sqfse the value for SCT_LRB.ITEM30_SQFSE
     *
     * @mbg.generated Tue Jan 03 14:17:25 CST 2017
     */
    public void setItem30Sqfse(Float item30Sqfse) {
        this.item30Sqfse = item30Sqfse;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SCT_LRB.ITEM31_BQFSE
     *
     * @return the value of SCT_LRB.ITEM31_BQFSE
     *
     * @mbg.generated Tue Jan 03 14:17:25 CST 2017
     */
    public Float getItem31Bqfse() {
        return item31Bqfse;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SCT_LRB.ITEM31_BQFSE
     *
     * @param item31Bqfse the value for SCT_LRB.ITEM31_BQFSE
     *
     * @mbg.generated Tue Jan 03 14:17:25 CST 2017
     */
    public void setItem31Bqfse(Float item31Bqfse) {
        this.item31Bqfse = item31Bqfse;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SCT_LRB.ITEM31_SQFSE
     *
     * @return the value of SCT_LRB.ITEM31_SQFSE
     *
     * @mbg.generated Tue Jan 03 14:17:25 CST 2017
     */
    public Float getItem31Sqfse() {
        return item31Sqfse;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SCT_LRB.ITEM31_SQFSE
     *
     * @param item31Sqfse the value for SCT_LRB.ITEM31_SQFSE
     *
     * @mbg.generated Tue Jan 03 14:17:25 CST 2017
     */
    public void setItem31Sqfse(Float item31Sqfse) {
        this.item31Sqfse = item31Sqfse;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SCT_LRB.ITEM32_BQFSE
     *
     * @return the value of SCT_LRB.ITEM32_BQFSE
     *
     * @mbg.generated Tue Jan 03 14:17:25 CST 2017
     */
    public Float getItem32Bqfse() {
        return item32Bqfse;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SCT_LRB.ITEM32_BQFSE
     *
     * @param item32Bqfse the value for SCT_LRB.ITEM32_BQFSE
     *
     * @mbg.generated Tue Jan 03 14:17:25 CST 2017
     */
    public void setItem32Bqfse(Float item32Bqfse) {
        this.item32Bqfse = item32Bqfse;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SCT_LRB.ITEM32_SQFSE
     *
     * @return the value of SCT_LRB.ITEM32_SQFSE
     *
     * @mbg.generated Tue Jan 03 14:17:25 CST 2017
     */
    public Float getItem32Sqfse() {
        return item32Sqfse;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SCT_LRB.ITEM32_SQFSE
     *
     * @param item32Sqfse the value for SCT_LRB.ITEM32_SQFSE
     *
     * @mbg.generated Tue Jan 03 14:17:25 CST 2017
     */
    public void setItem32Sqfse(Float item32Sqfse) {
        this.item32Sqfse = item32Sqfse;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SCT_LRB.ITEM33_BQFSE
     *
     * @return the value of SCT_LRB.ITEM33_BQFSE
     *
     * @mbg.generated Tue Jan 03 14:17:25 CST 2017
     */
    public Float getItem33Bqfse() {
        return item33Bqfse;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SCT_LRB.ITEM33_BQFSE
     *
     * @param item33Bqfse the value for SCT_LRB.ITEM33_BQFSE
     *
     * @mbg.generated Tue Jan 03 14:17:25 CST 2017
     */
    public void setItem33Bqfse(Float item33Bqfse) {
        this.item33Bqfse = item33Bqfse;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SCT_LRB.ITEM33_SQFSE
     *
     * @return the value of SCT_LRB.ITEM33_SQFSE
     *
     * @mbg.generated Tue Jan 03 14:17:25 CST 2017
     */
    public Float getItem33Sqfse() {
        return item33Sqfse;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SCT_LRB.ITEM33_SQFSE
     *
     * @param item33Sqfse the value for SCT_LRB.ITEM33_SQFSE
     *
     * @mbg.generated Tue Jan 03 14:17:25 CST 2017
     */
    public void setItem33Sqfse(Float item33Sqfse) {
        this.item33Sqfse = item33Sqfse;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SCT_LRB.ITEM34_BQFSE
     *
     * @return the value of SCT_LRB.ITEM34_BQFSE
     *
     * @mbg.generated Tue Jan 03 14:17:25 CST 2017
     */
    public Float getItem34Bqfse() {
        return item34Bqfse;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SCT_LRB.ITEM34_BQFSE
     *
     * @param item34Bqfse the value for SCT_LRB.ITEM34_BQFSE
     *
     * @mbg.generated Tue Jan 03 14:17:25 CST 2017
     */
    public void setItem34Bqfse(Float item34Bqfse) {
        this.item34Bqfse = item34Bqfse;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SCT_LRB.ITEM34_SQFSE
     *
     * @return the value of SCT_LRB.ITEM34_SQFSE
     *
     * @mbg.generated Tue Jan 03 14:17:25 CST 2017
     */
    public Float getItem34Sqfse() {
        return item34Sqfse;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SCT_LRB.ITEM34_SQFSE
     *
     * @param item34Sqfse the value for SCT_LRB.ITEM34_SQFSE
     *
     * @mbg.generated Tue Jan 03 14:17:25 CST 2017
     */
    public void setItem34Sqfse(Float item34Sqfse) {
        this.item34Sqfse = item34Sqfse;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SCT_LRB.ITEM35_BQFSE
     *
     * @return the value of SCT_LRB.ITEM35_BQFSE
     *
     * @mbg.generated Tue Jan 03 14:17:25 CST 2017
     */
    public Float getItem35Bqfse() {
        return item35Bqfse;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SCT_LRB.ITEM35_BQFSE
     *
     * @param item35Bqfse the value for SCT_LRB.ITEM35_BQFSE
     *
     * @mbg.generated Tue Jan 03 14:17:25 CST 2017
     */
    public void setItem35Bqfse(Float item35Bqfse) {
        this.item35Bqfse = item35Bqfse;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SCT_LRB.ITEM35_SQFSE
     *
     * @return the value of SCT_LRB.ITEM35_SQFSE
     *
     * @mbg.generated Tue Jan 03 14:17:25 CST 2017
     */
    public Float getItem35Sqfse() {
        return item35Sqfse;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SCT_LRB.ITEM35_SQFSE
     *
     * @param item35Sqfse the value for SCT_LRB.ITEM35_SQFSE
     *
     * @mbg.generated Tue Jan 03 14:17:25 CST 2017
     */
    public void setItem35Sqfse(Float item35Sqfse) {
        this.item35Sqfse = item35Sqfse;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SCT_LRB.ITEM36_BQFSE
     *
     * @return the value of SCT_LRB.ITEM36_BQFSE
     *
     * @mbg.generated Tue Jan 03 14:17:25 CST 2017
     */
    public Float getItem36Bqfse() {
        return item36Bqfse;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SCT_LRB.ITEM36_BQFSE
     *
     * @param item36Bqfse the value for SCT_LRB.ITEM36_BQFSE
     *
     * @mbg.generated Tue Jan 03 14:17:25 CST 2017
     */
    public void setItem36Bqfse(Float item36Bqfse) {
        this.item36Bqfse = item36Bqfse;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SCT_LRB.ITEM36_SQFSE
     *
     * @return the value of SCT_LRB.ITEM36_SQFSE
     *
     * @mbg.generated Tue Jan 03 14:17:25 CST 2017
     */
    public Float getItem36Sqfse() {
        return item36Sqfse;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SCT_LRB.ITEM36_SQFSE
     *
     * @param item36Sqfse the value for SCT_LRB.ITEM36_SQFSE
     *
     * @mbg.generated Tue Jan 03 14:17:25 CST 2017
     */
    public void setItem36Sqfse(Float item36Sqfse) {
        this.item36Sqfse = item36Sqfse;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SCT_LRB.ITEM37_BQFSE
     *
     * @return the value of SCT_LRB.ITEM37_BQFSE
     *
     * @mbg.generated Tue Jan 03 14:17:25 CST 2017
     */
    public Float getItem37Bqfse() {
        return item37Bqfse;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SCT_LRB.ITEM37_BQFSE
     *
     * @param item37Bqfse the value for SCT_LRB.ITEM37_BQFSE
     *
     * @mbg.generated Tue Jan 03 14:17:25 CST 2017
     */
    public void setItem37Bqfse(Float item37Bqfse) {
        this.item37Bqfse = item37Bqfse;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SCT_LRB.ITEM37_SQFSE
     *
     * @return the value of SCT_LRB.ITEM37_SQFSE
     *
     * @mbg.generated Tue Jan 03 14:17:25 CST 2017
     */
    public Float getItem37Sqfse() {
        return item37Sqfse;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SCT_LRB.ITEM37_SQFSE
     *
     * @param item37Sqfse the value for SCT_LRB.ITEM37_SQFSE
     *
     * @mbg.generated Tue Jan 03 14:17:25 CST 2017
     */
    public void setItem37Sqfse(Float item37Sqfse) {
        this.item37Sqfse = item37Sqfse;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SCT_LRB.ITEM38_BQFSE
     *
     * @return the value of SCT_LRB.ITEM38_BQFSE
     *
     * @mbg.generated Tue Jan 03 14:17:25 CST 2017
     */
    public Float getItem38Bqfse() {
        return item38Bqfse;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SCT_LRB.ITEM38_BQFSE
     *
     * @param item38Bqfse the value for SCT_LRB.ITEM38_BQFSE
     *
     * @mbg.generated Tue Jan 03 14:17:25 CST 2017
     */
    public void setItem38Bqfse(Float item38Bqfse) {
        this.item38Bqfse = item38Bqfse;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SCT_LRB.ITEM38_SQFSE
     *
     * @return the value of SCT_LRB.ITEM38_SQFSE
     *
     * @mbg.generated Tue Jan 03 14:17:25 CST 2017
     */
    public Float getItem38Sqfse() {
        return item38Sqfse;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SCT_LRB.ITEM38_SQFSE
     *
     * @param item38Sqfse the value for SCT_LRB.ITEM38_SQFSE
     *
     * @mbg.generated Tue Jan 03 14:17:25 CST 2017
     */
    public void setItem38Sqfse(Float item38Sqfse) {
        this.item38Sqfse = item38Sqfse;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SCT_LRB.ITEM39_BQFSE
     *
     * @return the value of SCT_LRB.ITEM39_BQFSE
     *
     * @mbg.generated Tue Jan 03 14:17:25 CST 2017
     */
    public Float getItem39Bqfse() {
        return item39Bqfse;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SCT_LRB.ITEM39_BQFSE
     *
     * @param item39Bqfse the value for SCT_LRB.ITEM39_BQFSE
     *
     * @mbg.generated Tue Jan 03 14:17:25 CST 2017
     */
    public void setItem39Bqfse(Float item39Bqfse) {
        this.item39Bqfse = item39Bqfse;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SCT_LRB.ITEM39_SQFSE
     *
     * @return the value of SCT_LRB.ITEM39_SQFSE
     *
     * @mbg.generated Tue Jan 03 14:17:25 CST 2017
     */
    public Float getItem39Sqfse() {
        return item39Sqfse;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SCT_LRB.ITEM39_SQFSE
     *
     * @param item39Sqfse the value for SCT_LRB.ITEM39_SQFSE
     *
     * @mbg.generated Tue Jan 03 14:17:25 CST 2017
     */
    public void setItem39Sqfse(Float item39Sqfse) {
        this.item39Sqfse = item39Sqfse;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SCT_LRB.ITEM40_BQFSE
     *
     * @return the value of SCT_LRB.ITEM40_BQFSE
     *
     * @mbg.generated Tue Jan 03 14:17:25 CST 2017
     */
    public Float getItem40Bqfse() {
        return item40Bqfse;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SCT_LRB.ITEM40_BQFSE
     *
     * @param item40Bqfse the value for SCT_LRB.ITEM40_BQFSE
     *
     * @mbg.generated Tue Jan 03 14:17:25 CST 2017
     */
    public void setItem40Bqfse(Float item40Bqfse) {
        this.item40Bqfse = item40Bqfse;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SCT_LRB.ITEM40_SQFSE
     *
     * @return the value of SCT_LRB.ITEM40_SQFSE
     *
     * @mbg.generated Tue Jan 03 14:17:25 CST 2017
     */
    public Float getItem40Sqfse() {
        return item40Sqfse;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SCT_LRB.ITEM40_SQFSE
     *
     * @param item40Sqfse the value for SCT_LRB.ITEM40_SQFSE
     *
     * @mbg.generated Tue Jan 03 14:17:25 CST 2017
     */
    public void setItem40Sqfse(Float item40Sqfse) {
        this.item40Sqfse = item40Sqfse;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SCT_LRB.ITEM41_BQFSE
     *
     * @return the value of SCT_LRB.ITEM41_BQFSE
     *
     * @mbg.generated Tue Jan 03 14:17:25 CST 2017
     */
    public Float getItem41Bqfse() {
        return item41Bqfse;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SCT_LRB.ITEM41_BQFSE
     *
     * @param item41Bqfse the value for SCT_LRB.ITEM41_BQFSE
     *
     * @mbg.generated Tue Jan 03 14:17:25 CST 2017
     */
    public void setItem41Bqfse(Float item41Bqfse) {
        this.item41Bqfse = item41Bqfse;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SCT_LRB.ITEM41_SQFSE
     *
     * @return the value of SCT_LRB.ITEM41_SQFSE
     *
     * @mbg.generated Tue Jan 03 14:17:25 CST 2017
     */
    public Float getItem41Sqfse() {
        return item41Sqfse;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SCT_LRB.ITEM41_SQFSE
     *
     * @param item41Sqfse the value for SCT_LRB.ITEM41_SQFSE
     *
     * @mbg.generated Tue Jan 03 14:17:25 CST 2017
     */
    public void setItem41Sqfse(Float item41Sqfse) {
        this.item41Sqfse = item41Sqfse;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SCT_LRB.ITEM42_BQFSE
     *
     * @return the value of SCT_LRB.ITEM42_BQFSE
     *
     * @mbg.generated Tue Jan 03 14:17:25 CST 2017
     */
    public Float getItem42Bqfse() {
        return item42Bqfse;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SCT_LRB.ITEM42_BQFSE
     *
     * @param item42Bqfse the value for SCT_LRB.ITEM42_BQFSE
     *
     * @mbg.generated Tue Jan 03 14:17:25 CST 2017
     */
    public void setItem42Bqfse(Float item42Bqfse) {
        this.item42Bqfse = item42Bqfse;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SCT_LRB.ITEM42_SQFSE
     *
     * @return the value of SCT_LRB.ITEM42_SQFSE
     *
     * @mbg.generated Tue Jan 03 14:17:25 CST 2017
     */
    public Float getItem42Sqfse() {
        return item42Sqfse;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SCT_LRB.ITEM42_SQFSE
     *
     * @param item42Sqfse the value for SCT_LRB.ITEM42_SQFSE
     *
     * @mbg.generated Tue Jan 03 14:17:25 CST 2017
     */
    public void setItem42Sqfse(Float item42Sqfse) {
        this.item42Sqfse = item42Sqfse;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SCT_LRB.ITEM43_BQFSE
     *
     * @return the value of SCT_LRB.ITEM43_BQFSE
     *
     * @mbg.generated Tue Jan 03 14:17:25 CST 2017
     */
    public Float getItem43Bqfse() {
        return item43Bqfse;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SCT_LRB.ITEM43_BQFSE
     *
     * @param item43Bqfse the value for SCT_LRB.ITEM43_BQFSE
     *
     * @mbg.generated Tue Jan 03 14:17:25 CST 2017
     */
    public void setItem43Bqfse(Float item43Bqfse) {
        this.item43Bqfse = item43Bqfse;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SCT_LRB.ITEM43_SQFSE
     *
     * @return the value of SCT_LRB.ITEM43_SQFSE
     *
     * @mbg.generated Tue Jan 03 14:17:25 CST 2017
     */
    public Float getItem43Sqfse() {
        return item43Sqfse;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SCT_LRB.ITEM43_SQFSE
     *
     * @param item43Sqfse the value for SCT_LRB.ITEM43_SQFSE
     *
     * @mbg.generated Tue Jan 03 14:17:25 CST 2017
     */
    public void setItem43Sqfse(Float item43Sqfse) {
        this.item43Sqfse = item43Sqfse;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SCT_LRB.ITEM44_BQFSE
     *
     * @return the value of SCT_LRB.ITEM44_BQFSE
     *
     * @mbg.generated Tue Jan 03 14:17:25 CST 2017
     */
    public Float getItem44Bqfse() {
        return item44Bqfse;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SCT_LRB.ITEM44_BQFSE
     *
     * @param item44Bqfse the value for SCT_LRB.ITEM44_BQFSE
     *
     * @mbg.generated Tue Jan 03 14:17:25 CST 2017
     */
    public void setItem44Bqfse(Float item44Bqfse) {
        this.item44Bqfse = item44Bqfse;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SCT_LRB.ITEM44_SQFSE
     *
     * @return the value of SCT_LRB.ITEM44_SQFSE
     *
     * @mbg.generated Tue Jan 03 14:17:25 CST 2017
     */
    public Float getItem44Sqfse() {
        return item44Sqfse;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SCT_LRB.ITEM44_SQFSE
     *
     * @param item44Sqfse the value for SCT_LRB.ITEM44_SQFSE
     *
     * @mbg.generated Tue Jan 03 14:17:25 CST 2017
     */
    public void setItem44Sqfse(Float item44Sqfse) {
        this.item44Sqfse = item44Sqfse;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SCT_LRB.ITEM45_BQFSE
     *
     * @return the value of SCT_LRB.ITEM45_BQFSE
     *
     * @mbg.generated Tue Jan 03 14:17:25 CST 2017
     */
    public Float getItem45Bqfse() {
        return item45Bqfse;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SCT_LRB.ITEM45_BQFSE
     *
     * @param item45Bqfse the value for SCT_LRB.ITEM45_BQFSE
     *
     * @mbg.generated Tue Jan 03 14:17:25 CST 2017
     */
    public void setItem45Bqfse(Float item45Bqfse) {
        this.item45Bqfse = item45Bqfse;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SCT_LRB.ITEM45_SQFSE
     *
     * @return the value of SCT_LRB.ITEM45_SQFSE
     *
     * @mbg.generated Tue Jan 03 14:17:25 CST 2017
     */
    public Float getItem45Sqfse() {
        return item45Sqfse;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SCT_LRB.ITEM45_SQFSE
     *
     * @param item45Sqfse the value for SCT_LRB.ITEM45_SQFSE
     *
     * @mbg.generated Tue Jan 03 14:17:25 CST 2017
     */
    public void setItem45Sqfse(Float item45Sqfse) {
        this.item45Sqfse = item45Sqfse;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SCT_LRB.ITEM46_BQFSE
     *
     * @return the value of SCT_LRB.ITEM46_BQFSE
     *
     * @mbg.generated Tue Jan 03 14:17:25 CST 2017
     */
    public Float getItem46Bqfse() {
        return item46Bqfse;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SCT_LRB.ITEM46_BQFSE
     *
     * @param item46Bqfse the value for SCT_LRB.ITEM46_BQFSE
     *
     * @mbg.generated Tue Jan 03 14:17:25 CST 2017
     */
    public void setItem46Bqfse(Float item46Bqfse) {
        this.item46Bqfse = item46Bqfse;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SCT_LRB.ITEM46_SQFSE
     *
     * @return the value of SCT_LRB.ITEM46_SQFSE
     *
     * @mbg.generated Tue Jan 03 14:17:25 CST 2017
     */
    public Float getItem46Sqfse() {
        return item46Sqfse;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SCT_LRB.ITEM46_SQFSE
     *
     * @param item46Sqfse the value for SCT_LRB.ITEM46_SQFSE
     *
     * @mbg.generated Tue Jan 03 14:17:25 CST 2017
     */
    public void setItem46Sqfse(Float item46Sqfse) {
        this.item46Sqfse = item46Sqfse;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SCT_LRB.ITEM47_BQFSE
     *
     * @return the value of SCT_LRB.ITEM47_BQFSE
     *
     * @mbg.generated Tue Jan 03 14:17:25 CST 2017
     */
    public Float getItem47Bqfse() {
        return item47Bqfse;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SCT_LRB.ITEM47_BQFSE
     *
     * @param item47Bqfse the value for SCT_LRB.ITEM47_BQFSE
     *
     * @mbg.generated Tue Jan 03 14:17:25 CST 2017
     */
    public void setItem47Bqfse(Float item47Bqfse) {
        this.item47Bqfse = item47Bqfse;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SCT_LRB.ITEM47_SQFSE
     *
     * @return the value of SCT_LRB.ITEM47_SQFSE
     *
     * @mbg.generated Tue Jan 03 14:17:25 CST 2017
     */
    public Float getItem47Sqfse() {
        return item47Sqfse;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SCT_LRB.ITEM47_SQFSE
     *
     * @param item47Sqfse the value for SCT_LRB.ITEM47_SQFSE
     *
     * @mbg.generated Tue Jan 03 14:17:25 CST 2017
     */
    public void setItem47Sqfse(Float item47Sqfse) {
        this.item47Sqfse = item47Sqfse;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SCT_LRB.ITEM48_BQFSE
     *
     * @return the value of SCT_LRB.ITEM48_BQFSE
     *
     * @mbg.generated Tue Jan 03 14:17:25 CST 2017
     */
    public Float getItem48Bqfse() {
        return item48Bqfse;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SCT_LRB.ITEM48_BQFSE
     *
     * @param item48Bqfse the value for SCT_LRB.ITEM48_BQFSE
     *
     * @mbg.generated Tue Jan 03 14:17:25 CST 2017
     */
    public void setItem48Bqfse(Float item48Bqfse) {
        this.item48Bqfse = item48Bqfse;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SCT_LRB.ITEM48_SQFSE
     *
     * @return the value of SCT_LRB.ITEM48_SQFSE
     *
     * @mbg.generated Tue Jan 03 14:17:25 CST 2017
     */
    public Float getItem48Sqfse() {
        return item48Sqfse;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SCT_LRB.ITEM48_SQFSE
     *
     * @param item48Sqfse the value for SCT_LRB.ITEM48_SQFSE
     *
     * @mbg.generated Tue Jan 03 14:17:25 CST 2017
     */
    public void setItem48Sqfse(Float item48Sqfse) {
        this.item48Sqfse = item48Sqfse;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SCT_LRB.ITEM49_BQFSE
     *
     * @return the value of SCT_LRB.ITEM49_BQFSE
     *
     * @mbg.generated Tue Jan 03 14:17:25 CST 2017
     */
    public Float getItem49Bqfse() {
        return item49Bqfse;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SCT_LRB.ITEM49_BQFSE
     *
     * @param item49Bqfse the value for SCT_LRB.ITEM49_BQFSE
     *
     * @mbg.generated Tue Jan 03 14:17:25 CST 2017
     */
    public void setItem49Bqfse(Float item49Bqfse) {
        this.item49Bqfse = item49Bqfse;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SCT_LRB.ITEM49_SQFSE
     *
     * @return the value of SCT_LRB.ITEM49_SQFSE
     *
     * @mbg.generated Tue Jan 03 14:17:25 CST 2017
     */
    public Float getItem49Sqfse() {
        return item49Sqfse;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SCT_LRB.ITEM49_SQFSE
     *
     * @param item49Sqfse the value for SCT_LRB.ITEM49_SQFSE
     *
     * @mbg.generated Tue Jan 03 14:17:25 CST 2017
     */
    public void setItem49Sqfse(Float item49Sqfse) {
        this.item49Sqfse = item49Sqfse;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SCT_LRB.ITEM50_BQFSE
     *
     * @return the value of SCT_LRB.ITEM50_BQFSE
     *
     * @mbg.generated Tue Jan 03 14:17:25 CST 2017
     */
    public Float getItem50Bqfse() {
        return item50Bqfse;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SCT_LRB.ITEM50_BQFSE
     *
     * @param item50Bqfse the value for SCT_LRB.ITEM50_BQFSE
     *
     * @mbg.generated Tue Jan 03 14:17:25 CST 2017
     */
    public void setItem50Bqfse(Float item50Bqfse) {
        this.item50Bqfse = item50Bqfse;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SCT_LRB.ITEM50_SQFSE
     *
     * @return the value of SCT_LRB.ITEM50_SQFSE
     *
     * @mbg.generated Tue Jan 03 14:17:25 CST 2017
     */
    public Float getItem50Sqfse() {
        return item50Sqfse;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SCT_LRB.ITEM50_SQFSE
     *
     * @param item50Sqfse the value for SCT_LRB.ITEM50_SQFSE
     *
     * @mbg.generated Tue Jan 03 14:17:25 CST 2017
     */
    public void setItem50Sqfse(Float item50Sqfse) {
        this.item50Sqfse = item50Sqfse;
    }
}