package com.kysoft.cpsi.zcb.entity;

import java.util.Date;

public class SctXzcf extends SctXzcfKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SCT_XZCF.TBRQ
     *
     * @mbg.generated Tue Jan 03 14:17:25 CST 2017
     */
    private Date tbrq;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SCT_XZCF.CFJDSWH
     *
     * @mbg.generated Tue Jan 03 14:17:25 CST 2017
     */
    private String cfjdswh;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SCT_XZCF.WFXWLX
     *
     * @mbg.generated Tue Jan 03 14:17:25 CST 2017
     */
    private String wfxwlx;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SCT_XZCF.XZCFNR
     *
     * @mbg.generated Tue Jan 03 14:17:25 CST 2017
     */
    private String xzcfnr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SCT_XZCF.ZCCFJDJG
     *
     * @mbg.generated Tue Jan 03 14:17:25 CST 2017
     */
    private String zccfjdjg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SCT_XZCF.CFRQ
     *
     * @mbg.generated Tue Jan 03 14:17:25 CST 2017
     */
    private Date cfrq;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SCT_XZCF.TBRQ
     *
     * @return the value of SCT_XZCF.TBRQ
     *
     * @mbg.generated Tue Jan 03 14:17:25 CST 2017
     */
    public Date getTbrq() {
        return tbrq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SCT_XZCF.TBRQ
     *
     * @param tbrq the value for SCT_XZCF.TBRQ
     *
     * @mbg.generated Tue Jan 03 14:17:25 CST 2017
     */
    public void setTbrq(Date tbrq) {
        this.tbrq = tbrq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SCT_XZCF.CFJDSWH
     *
     * @return the value of SCT_XZCF.CFJDSWH
     *
     * @mbg.generated Tue Jan 03 14:17:25 CST 2017
     */
    public String getCfjdswh() {
        return cfjdswh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SCT_XZCF.CFJDSWH
     *
     * @param cfjdswh the value for SCT_XZCF.CFJDSWH
     *
     * @mbg.generated Tue Jan 03 14:17:25 CST 2017
     */
    public void setCfjdswh(String cfjdswh) {
        this.cfjdswh = cfjdswh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SCT_XZCF.WFXWLX
     *
     * @return the value of SCT_XZCF.WFXWLX
     *
     * @mbg.generated Tue Jan 03 14:17:25 CST 2017
     */
    public String getWfxwlx() {
        return wfxwlx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SCT_XZCF.WFXWLX
     *
     * @param wfxwlx the value for SCT_XZCF.WFXWLX
     *
     * @mbg.generated Tue Jan 03 14:17:25 CST 2017
     */
    public void setWfxwlx(String wfxwlx) {
        this.wfxwlx = wfxwlx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SCT_XZCF.XZCFNR
     *
     * @return the value of SCT_XZCF.XZCFNR
     *
     * @mbg.generated Tue Jan 03 14:17:25 CST 2017
     */
    public String getXzcfnr() {
        return xzcfnr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SCT_XZCF.XZCFNR
     *
     * @param xzcfnr the value for SCT_XZCF.XZCFNR
     *
     * @mbg.generated Tue Jan 03 14:17:25 CST 2017
     */
    public void setXzcfnr(String xzcfnr) {
        this.xzcfnr = xzcfnr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SCT_XZCF.ZCCFJDJG
     *
     * @return the value of SCT_XZCF.ZCCFJDJG
     *
     * @mbg.generated Tue Jan 03 14:17:25 CST 2017
     */
    public String getZccfjdjg() {
        return zccfjdjg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SCT_XZCF.ZCCFJDJG
     *
     * @param zccfjdjg the value for SCT_XZCF.ZCCFJDJG
     *
     * @mbg.generated Tue Jan 03 14:17:25 CST 2017
     */
    public void setZccfjdjg(String zccfjdjg) {
        this.zccfjdjg = zccfjdjg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SCT_XZCF.CFRQ
     *
     * @return the value of SCT_XZCF.CFRQ
     *
     * @mbg.generated Tue Jan 03 14:17:25 CST 2017
     */
    public Date getCfrq() {
        return cfrq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SCT_XZCF.CFRQ
     *
     * @param cfrq the value for SCT_XZCF.CFRQ
     *
     * @mbg.generated Tue Jan 03 14:17:25 CST 2017
     */
    public void setCfrq(Date cfrq) {
        this.cfrq = cfrq;
    }
}