package com.kysoft.cpsi.zcb.entity;

public class SctZcfzbKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SCT_ZCFZB.XYDM
     *
     * @mbg.generated Tue Jan 03 14:17:25 CST 2017
     */
    private String xydm;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SCT_ZCFZB.ND
     *
     * @mbg.generated Tue Jan 03 14:17:25 CST 2017
     */
    private Integer nd;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SCT_ZCFZB.XYDM
     *
     * @return the value of SCT_ZCFZB.XYDM
     *
     * @mbg.generated Tue Jan 03 14:17:25 CST 2017
     */
    public String getXydm() {
        return xydm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SCT_ZCFZB.XYDM
     *
     * @param xydm the value for SCT_ZCFZB.XYDM
     *
     * @mbg.generated Tue Jan 03 14:17:25 CST 2017
     */
    public void setXydm(String xydm) {
        this.xydm = xydm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SCT_ZCFZB.ND
     *
     * @return the value of SCT_ZCFZB.ND
     *
     * @mbg.generated Tue Jan 03 14:17:25 CST 2017
     */
    public Integer getNd() {
        return nd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SCT_ZCFZB.ND
     *
     * @param nd the value for SCT_ZCFZB.ND
     *
     * @mbg.generated Tue Jan 03 14:17:25 CST 2017
     */
    public void setNd(Integer nd) {
        this.nd = nd;
    }
}