package com.kysoft.cpsi.zcb.entity;

public class SctDwdbKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SCT_DWDB.XYDM
     *
     * @mbg.generated Tue Jan 03 14:17:25 CST 2017
     */
    private String xydm;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SCT_DWDB.ND
     *
     * @mbg.generated Tue Jan 03 14:17:25 CST 2017
     */
    private Integer nd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SCT_DWDB.XH
     *
     * @mbg.generated Tue Jan 03 14:17:25 CST 2017
     */
    private Integer xh;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SCT_DWDB.XYDM
     *
     * @return the value of SCT_DWDB.XYDM
     *
     * @mbg.generated Tue Jan 03 14:17:25 CST 2017
     */
    public String getXydm() {
        return xydm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SCT_DWDB.XYDM
     *
     * @param xydm the value for SCT_DWDB.XYDM
     *
     * @mbg.generated Tue Jan 03 14:17:25 CST 2017
     */
    public void setXydm(String xydm) {
        this.xydm = xydm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SCT_DWDB.ND
     *
     * @return the value of SCT_DWDB.ND
     *
     * @mbg.generated Tue Jan 03 14:17:25 CST 2017
     */
    public Integer getNd() {
        return nd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SCT_DWDB.ND
     *
     * @param nd the value for SCT_DWDB.ND
     *
     * @mbg.generated Tue Jan 03 14:17:25 CST 2017
     */
    public void setNd(Integer nd) {
        this.nd = nd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SCT_DWDB.XH
     *
     * @return the value of SCT_DWDB.XH
     *
     * @mbg.generated Tue Jan 03 14:17:25 CST 2017
     */
    public Integer getXh() {
        return xh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SCT_DWDB.XH
     *
     * @param xh the value for SCT_DWDB.XH
     *
     * @mbg.generated Tue Jan 03 14:17:25 CST 2017
     */
    public void setXh(Integer xh) {
        this.xh = xh;
    }
}