package com.kysoft.cpsi.enterprise.mapper;

import com.kysoft.cpsi.enterprise.entity.Zfry;

public interface ZfryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_ZFRY
     *
     * @mbggenerated Tue May 03 17:59:53 CST 2016
     */
    int insert(Zfry record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_ZFRY
     *
     * @mbggenerated Tue May 03 17:59:53 CST 2016
     */
    int insertSelective(Zfry record);
}