package com.kysoft.cpsi.task.mapper;

import com.kysoft.cpsi.task.entity.Hcrw;

import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

public interface HcrwMapper {
    /**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table T_HCRW
	 * @mbggenerated  Thu Jun 23 11:57:37 CST 2016
	 */
	int deleteByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table T_HCRW
	 * @mbggenerated  Thu Jun 23 11:57:37 CST 2016
	 */
	int insert(Hcrw record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table T_HCRW
	 * @mbggenerated  Thu Jun 23 11:57:37 CST 2016
	 */
	int insertSelective(Hcrw record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table T_HCRW
	 * @mbggenerated  Thu Jun 23 11:57:37 CST 2016
	 */
	Hcrw selectByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table T_HCRW
	 * @mbggenerated  Thu Jun 23 11:57:37 CST 2016
	 */
	int updateByPrimaryKeySelective(Hcrw record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table T_HCRW
	 * @mbggenerated  Thu Jun 23 11:57:37 CST 2016
	 */
	int updateByPrimaryKey(Hcrw record);

	//根据�?查单位查询任务列�?--3101
    List<Hcrw> queryForOrg(Map<String, Object> param);

    //根据信用代码查询任务列表--2101
    List<Hcrw> queryForXydm(Map<String, Object> param);

    //根据�?查人员查询任务列�?--5101
    List<Hcrw> queryForAuditor(Map<String, Object> param);

    List<Hcrw> queryForPlan(Map<String, Object> param);

    Integer selectCountByPlanId(String planId);

    void pullData(Map<String, Object> param);

    void updateLoadedByPrimaryKey(String hcrwId);

    List<Hcrw> query(Map<String, Object> param);

    List<Map<String, Object>> queryTongJiFenXi(Map<String, Object> params);

	void updateAccept(@Param("taskIds") List<String> taskIds, @Param("userId")String userId, @Param("userName")String userName);
	
	void updateUnAccept(@Param("taskIds") List<String> taskIds);

	Integer selectYrlsByPlanId(String planId);
}