package com.kysoft.cpsi.task.mapper;

import com.kysoft.cpsi.task.entity.HcrwTj;
import com.kysoft.cpsi.task.entity.HcrwTjKey;

public interface HcrwTjMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_HCRW_TJ
     *
     * @mbggenerated Mon May 23 07:56:37 CST 2016
     */
    int deleteByPrimaryKey(HcrwTjKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_HCRW_TJ
     *
     * @mbggenerated Mon May 23 07:56:37 CST 2016
     */
    int insert(HcrwTj record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_HCRW_TJ
     *
     * @mbggenerated Mon May 23 07:56:37 CST 2016
     */
    int insertSelective(HcrwTj record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_HCRW_TJ
     *
     * @mbggenerated Mon May 23 07:56:37 CST 2016
     */
    HcrwTj selectByPrimaryKey(HcrwTjKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_HCRW_TJ
     *
     * @mbggenerated Mon May 23 07:56:37 CST 2016
     */
    int updateByPrimaryKeySelective(HcrwTj record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_HCRW_TJ
     *
     * @mbggenerated Mon May 23 07:56:37 CST 2016
     */
    int updateByPrimaryKey(HcrwTj record);
}