package com.kysoft.cpsi.task.mapper;

import java.util.List;
import java.util.Map;

import com.kysoft.cpsi.task.entity.Hcrw;
import com.kysoft.cpsi.task.entity.HcrwTj;
import com.kysoft.cpsi.task.entity.HcrwTjKey;

public interface HcrwTjMapper {
    /**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table T_HCRW_TJ
	 * @mbggenerated  Mon May 23 15:20:12 CST 2016
	 */
	int deleteByPrimaryKey(HcrwTjKey key);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table T_HCRW_TJ
	 * @mbggenerated  Mon May 23 15:20:12 CST 2016
	 */
	int insert(HcrwTj record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table T_HCRW_TJ
	 * @mbggenerated  Mon May 23 15:20:12 CST 2016
	 */
	int insertSelective(HcrwTj record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table T_HCRW_TJ
	 * @mbggenerated  Mon May 23 15:20:12 CST 2016
	 */
	HcrwTj selectByPrimaryKey(HcrwTjKey key);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table T_HCRW_TJ
	 * @mbggenerated  Mon May 23 15:20:12 CST 2016
	 */
	int updateByPrimaryKeySelective(HcrwTj record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table T_HCRW_TJ
	 * @mbggenerated  Mon May 23 15:20:12 CST 2016
	 */
	int updateByPrimaryKey(HcrwTj record);

	//根据核查单位查询任务统计列表--3102
    List<HcrwTj> queryForOrg(Map<String, Object> param);
}