package com.kysoft.cpsi.task.mapper;

import java.util.List;
import java.util.Map;

import com.kysoft.cpsi.task.entity.Hcrw;
import com.kysoft.cpsi.task.entity.Hcsxjg;
import com.kysoft.cpsi.task.entity.HcsxjgKey;

public interface HcsxjgMapper {
    /**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table T_HCSXJG
	 * @mbggenerated  Mon May 23 09:16:18 CST 2016
	 */
	int deleteByPrimaryKey(HcsxjgKey key);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table T_HCSXJG
	 * @mbggenerated  Mon May 23 09:16:18 CST 2016
	 */
	int insert(Hcsxjg record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table T_HCSXJG
	 * @mbggenerated  Mon May 23 09:16:18 CST 2016
	 */
	int insertSelective(Hcsxjg record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table T_HCSXJG
	 * @mbggenerated  Mon May 23 09:16:18 CST 2016
	 */
	Hcsxjg selectByPrimaryKey(HcsxjgKey key);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table T_HCSXJG
	 * @mbggenerated  Mon May 23 09:16:18 CST 2016
	 */
	int updateByPrimaryKeySelective(Hcsxjg record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table T_HCSXJG
	 * @mbggenerated  Mon May 23 09:16:18 CST 2016
	 */
	int updateByPrimaryKey(Hcsxjg record);

	List<Hcsxjg> queryForTask(Map<String, Object> param);
}