package com.kysoft.cpsi.task.mapper;

import org.apache.ibatis.annotations.Param;

import com.kysoft.cpsi.task.entity.JhSxKey;

public interface JhSxMapper {
    /**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table T_HCJH_HCSX
	 * @mbggenerated  Tue May 24 10:30:15 CST 2016
	 */
	int deleteByPrimaryKey(JhSxKey key);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table T_HCJH_HCSX
	 * @mbggenerated  Tue May 24 10:30:15 CST 2016
	 */
	int insert(JhSxKey record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table T_HCJH_HCSX
	 * @mbggenerated  Tue May 24 10:30:15 CST 2016
	 */
	int insertSelective(JhSxKey record);

	void insertBatch(@Param("hcjhId")String hcjhId, @Param("hcsxIds")String[] hcsxIds);

	void deleteBatch(@Param("hcjhId")String hcjhId, @Param("hcsxIds")String[] hcsxIds);
}