package com.kysoft.cpsi.repo.mapper;

import com.kysoft.cpsi.repo.entity.Hccl;

import java.util.List;
import java.util.Map;

public interface HcclMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table T_HCCL
	 * @mbggenerated  Mon Aug 08 09:14:15 CST 2016
	 */
	int deleteByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table T_HCCL
	 * @mbggenerated  Mon Aug 08 09:14:15 CST 2016
	 */
	int insert(Hccl record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table T_HCCL
	 * @mbggenerated  Mon Aug 08 09:14:15 CST 2016
	 */
	int insertSelective(Hccl record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table T_HCCL
	 * @mbggenerated  Mon Aug 08 09:14:15 CST 2016
	 */
	Hccl selectByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table T_HCCL
	 * @mbggenerated  Mon Aug 08 09:14:15 CST 2016
	 */
	int updateByPrimaryKeySelective(Hccl record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table T_HCCL
	 * @mbggenerated  Mon Aug 08 09:14:15 CST 2016
	 */
	int updateByPrimaryKey(Hccl record);

	List<Hccl> selectByHcsxId(String hcsxId);

	List<Hccl> queryForAuditItem(Map<String, Object> param);
	
	/*查询被检查单位需要上传的�?查材�?*/
    List<Map<String, Object>> queryForTask(Map<String, Object> params);
    
	
    /*查询被检查单位需要上传的附加�?查材�?*/
    List<Map<String, Object>> queryForTask2(String hcrwId);

	List<Map<String, Object>> getDXNHcsx(Map<String, Object> params);
}