package com.kysoft.cpsi.repo.mapper;

import com.kysoft.cpsi.repo.entity.Hccl;

public interface HcclMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_HCCL
     *
     * @mbggenerated Fri May 20 11:20:44 CST 2016
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_HCCL
     *
     * @mbggenerated Fri May 20 11:20:44 CST 2016
     */
    int insert(Hccl record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_HCCL
     *
     * @mbggenerated Fri May 20 11:20:44 CST 2016
     */
    int insertSelective(Hccl record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_HCCL
     *
     * @mbggenerated Fri May 20 11:20:44 CST 2016
     */
    Hccl selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_HCCL
     *
     * @mbggenerated Fri May 20 11:20:44 CST 2016
     */
    int updateByPrimaryKeySelective(Hccl record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_HCCL
     *
     * @mbggenerated Fri May 20 11:20:44 CST 2016
     */
    int updateByPrimaryKey(Hccl record);
}