package com.kysoft.cpsi.repo.mapper;

import java.util.List;
import java.util.Map;

import com.kysoft.cpsi.repo.entity.Hccl;

public interface HcclMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table T_HCCL
	 * @mbggenerated  Thu May 26 21:05:28 CST 2016
	 */
	int deleteByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table T_HCCL
	 * @mbggenerated  Thu May 26 21:05:28 CST 2016
	 */
	int insert(Hccl record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table T_HCCL
	 * @mbggenerated  Thu May 26 21:05:28 CST 2016
	 */
	int insertSelective(Hccl record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table T_HCCL
	 * @mbggenerated  Thu May 26 21:05:28 CST 2016
	 */
	Hccl selectByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table T_HCCL
	 * @mbggenerated  Thu May 26 21:05:28 CST 2016
	 */
	int updateByPrimaryKeySelective(Hccl record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table T_HCCL
	 * @mbggenerated  Thu May 26 21:05:28 CST 2016
	 */
	int updateByPrimaryKey(Hccl record);


	List<Hccl> selectByHcsxId(String hcsxId);

	List<Hccl> queryForAuditItem(Map<String, Object> param);
	
	/*查询被检查单位需要上传的检查材料*/
    List<Map<String, Object>> queryForTask(Map<String, Object> params);
}