package com.kysoft.cpsi.repo.mapper;

import com.kysoft.cpsi.repo.entity.Hcsx;
import org.apache.ibatis.annotations.Param;

import java.util.List;
import java.util.Map;

public interface HcsxMapper {
    

//	List<Hcsx> selectByJhId(String hcjhId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table T_HCSX
	 * @mbggenerated  Tue Jun 21 08:45:05 CST 2016
	 */
	int deleteByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table T_HCSX
	 * @mbggenerated  Tue Jun 21 08:45:05 CST 2016
	 */
	int insert(Hcsx record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table T_HCSX
	 * @mbggenerated  Tue Jun 21 08:45:05 CST 2016
	 */
	int insertSelective(Hcsx record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table T_HCSX
	 * @mbggenerated  Tue Jun 21 08:45:05 CST 2016
	 */
	Hcsx selectByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table T_HCSX
	 * @mbggenerated  Tue Jun 21 08:45:05 CST 2016
	 */
	int updateByPrimaryKeySelective(Hcsx record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table T_HCSX
	 * @mbggenerated  Tue Jun 21 08:45:05 CST 2016
	 */
	int updateByPrimaryKey(Hcsx record);

	List<Hcsx> query(Map<String, Object> params);

	List<Hcsx> queryForPlan(Map<String, Object> params);
	
	List<Hcsx> queryForPlanCandidate(Map<String, Object> params);

	List<Hcsx> selectByTaskId(String hcrwId);

	List<Map> getHcsxCode(String hcrwId);

	void updateHcclByPrimaryKey(@Param("hcsxId") String hcsxId, @Param("hcclInHcsx") String hcclInHcsx);

	void updateDisable(@Param("hcsxId")String hcsxId, @Param("disableFlag")Integer disableFlag, @Param("zxsm")String zxsm);

	List<String> selectAvailableAuditItemId(@Param("hcjhId") String hcjhId, @Param("nr") Integer nr);

	List<Map> getJsHcsxCode();
}