package com.kysoft.cpsi.repo.mapper;

import java.util.List;

import com.kysoft.cpsi.repo.entity.Hcsx;

public interface HcsxMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_HCSX
     *
     * @mbggenerated Fri May 20 11:20:44 CST 2016
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_HCSX
     *
     * @mbggenerated Fri May 20 11:20:44 CST 2016
     */
    int insert(Hcsx record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_HCSX
     *
     * @mbggenerated Fri May 20 11:20:44 CST 2016
     */
    int insertSelective(Hcsx record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_HCSX
     *
     * @mbggenerated Fri May 20 11:20:44 CST 2016
     */
    Hcsx selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_HCSX
     *
     * @mbggenerated Fri May 20 11:20:44 CST 2016
     */
    int updateByPrimaryKeySelective(Hcsx record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_HCSX
     *
     * @mbggenerated Fri May 20 11:20:44 CST 2016
     */
    int updateByPrimaryKey(Hcsx record);

	List<Hcsx> selectByJhId(String string);
}