package com.kysoft.cpsi.repo.mapper;

import com.kysoft.cpsi.repo.entity.Zfry;

public interface ZfryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_ZFRY
     *
     * @mbggenerated Fri May 20 11:20:44 CST 2016
     */
    int deleteByPrimaryKey(String code);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_ZFRY
     *
     * @mbggenerated Fri May 20 11:20:44 CST 2016
     */
    int insert(Zfry record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_ZFRY
     *
     * @mbggenerated Fri May 20 11:20:44 CST 2016
     */
    int insertSelective(Zfry record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_ZFRY
     *
     * @mbggenerated Fri May 20 11:20:44 CST 2016
     */
    Zfry selectByPrimaryKey(String code);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_ZFRY
     *
     * @mbggenerated Fri May 20 11:20:44 CST 2016
     */
    int updateByPrimaryKeySelective(Zfry record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_ZFRY
     *
     * @mbggenerated Fri May 20 11:20:44 CST 2016
     */
    int updateByPrimaryKey(Zfry record);
}