package com.kysoft.cpsi.repo.mapper;

import com.kysoft.cpsi.repo.entity.Zfry;

import java.util.List;
import java.util.Map;

public interface ZfryMapper {
    /**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table T_ZFRY
	 * @mbggenerated  Mon Jun 20 18:16:29 CST 2016
	 */
	int deleteByPrimaryKey(String code);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table T_ZFRY
	 * @mbggenerated  Mon Jun 20 18:16:29 CST 2016
	 */
	int insert(Zfry record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table T_ZFRY
	 * @mbggenerated  Mon Jun 20 18:16:29 CST 2016
	 */
	int insertSelective(Zfry record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table T_ZFRY
	 * @mbggenerated  Mon Jun 20 18:16:29 CST 2016
	 */
	Zfry selectByPrimaryKey(String code);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table T_ZFRY
	 * @mbggenerated  Mon Jun 20 18:16:29 CST 2016
	 */
	int updateByPrimaryKeySelective(Zfry record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table T_ZFRY
	 * @mbggenerated  Mon Jun 20 18:16:29 CST 2016
	 */
	int updateByPrimaryKey(Zfry record);

	List<Zfry> query(Map<String, Object> params);
}