package com.kysoft.cpsi.found.entity;

public class Bm {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column T_BM.ID
	 * @mbggenerated  Mon May 23 18:08:31 CST 2016
	 */
	private String id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column T_BM.NAME
	 * @mbggenerated  Mon May 23 18:08:31 CST 2016
	 */
	private String name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column T_BM.LXR
	 * @mbggenerated  Mon May 23 18:08:31 CST 2016
	 */
	private String lxr;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column T_BM.LXDH
	 * @mbggenerated  Mon May 23 18:08:31 CST 2016
	 */
	private String lxdh;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column T_BM.GSXXFL
	 * @mbggenerated  Mon May 23 18:08:31 CST 2016
	 */
	private Integer gsxxfl;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column T_BM.ORG_ID
	 * @mbggenerated  Mon May 23 18:08:31 CST 2016
	 */
	private String orgId;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column T_BM.ID
	 * @return  the value of T_BM.ID
	 * @mbggenerated  Mon May 23 18:08:31 CST 2016
	 */
	public String getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column T_BM.ID
	 * @param id  the value for T_BM.ID
	 * @mbggenerated  Mon May 23 18:08:31 CST 2016
	 */
	public void setId(String id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column T_BM.NAME
	 * @return  the value of T_BM.NAME
	 * @mbggenerated  Mon May 23 18:08:31 CST 2016
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column T_BM.NAME
	 * @param name  the value for T_BM.NAME
	 * @mbggenerated  Mon May 23 18:08:31 CST 2016
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column T_BM.LXR
	 * @return  the value of T_BM.LXR
	 * @mbggenerated  Mon May 23 18:08:31 CST 2016
	 */
	public String getLxr() {
		return lxr;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column T_BM.LXR
	 * @param lxr  the value for T_BM.LXR
	 * @mbggenerated  Mon May 23 18:08:31 CST 2016
	 */
	public void setLxr(String lxr) {
		this.lxr = lxr;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column T_BM.LXDH
	 * @return  the value of T_BM.LXDH
	 * @mbggenerated  Mon May 23 18:08:31 CST 2016
	 */
	public String getLxdh() {
		return lxdh;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column T_BM.LXDH
	 * @param lxdh  the value for T_BM.LXDH
	 * @mbggenerated  Mon May 23 18:08:31 CST 2016
	 */
	public void setLxdh(String lxdh) {
		this.lxdh = lxdh;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column T_BM.GSXXFL
	 * @return  the value of T_BM.GSXXFL
	 * @mbggenerated  Mon May 23 18:08:31 CST 2016
	 */
	public Integer getGsxxfl() {
		return gsxxfl;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column T_BM.GSXXFL
	 * @param gsxxfl  the value for T_BM.GSXXFL
	 * @mbggenerated  Mon May 23 18:08:31 CST 2016
	 */
	public void setGsxxfl(Integer gsxxfl) {
		this.gsxxfl = gsxxfl;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column T_BM.ORG_ID
	 * @return  the value of T_BM.ORG_ID
	 * @mbggenerated  Mon May 23 18:08:31 CST 2016
	 */
	public String getOrgId() {
		return orgId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column T_BM.ORG_ID
	 * @param orgId  the value for T_BM.ORG_ID
	 * @mbggenerated  Mon May 23 18:08:31 CST 2016
	 */
	public void setOrgId(String orgId) {
		this.orgId = orgId;
	}
}