package com.kysoft.cpsi.audit.mapper;

import com.kysoft.cpsi.audit.entity.AnnualReport;

public interface AnnualReportMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table T_NB
	 * @mbggenerated  Mon May 30 14:49:40 CST 2016
	 */
	int deleteByPrimaryKey(String hcrwId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table T_NB
	 * @mbggenerated  Mon May 30 14:49:40 CST 2016
	 */
	int insert(AnnualReport record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table T_NB
	 * @mbggenerated  Mon May 30 14:49:40 CST 2016
	 */
	int insertSelective(AnnualReport record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table T_NB
	 * @mbggenerated  Mon May 30 14:49:40 CST 2016
	 */
	AnnualReport selectByPrimaryKey(String hcrwId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table T_NB
	 * @mbggenerated  Mon May 30 14:49:40 CST 2016
	 */
	int updateByPrimaryKeySelective(AnnualReport record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table T_NB
	 * @mbggenerated  Mon May 30 14:49:40 CST 2016
	 */
	int updateByPrimaryKey(AnnualReport record);
	
	AnnualReport selectByPrimaryKey2(String hcrwId);
}