package com.kysoft.cpsi.audit.mapper;

import org.apache.ibatis.annotations.Delete;

import com.kysoft.cpsi.audit.entity.AnnualReport;
import com.kysoft.cpsi.audit.entity.AnnualReportKey;

public interface AnnualReportMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table T_NB
	 * @mbg.generated  Mon Jan 09 11:26:18 CST 2017
	 */
	int deleteByPrimaryKey(AnnualReportKey key);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table T_NB
	 * @mbg.generated  Mon Jan 09 11:26:18 CST 2017
	 */
	int insert(AnnualReport record);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table T_NB
	 * @mbg.generated  Mon Jan 09 11:26:18 CST 2017
	 */
	int insertSelective(AnnualReport record);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table T_NB
	 * @mbg.generated  Mon Jan 09 11:26:18 CST 2017
	 */
	AnnualReport selectByPrimaryKey(AnnualReportKey key);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table T_NB
	 * @mbg.generated  Mon Jan 09 11:26:18 CST 2017
	 */
	int updateByPrimaryKeySelective(AnnualReport record);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table T_NB
	 * @mbg.generated  Mon Jan 09 11:26:18 CST 2017
	 */
	int updateByPrimaryKey(AnnualReport record);

	AnnualReport selectByHcrwId(String hcrwId);
	AnnualReport selectByHcrwId2(String hcrwId);
	AnnualReport selectByHcrwId3(String hcrwId);

	@Delete("DELETE from T_NB_BD where (xydm,nd) in(select a.hcdw_xydm,b.nd from t_hcrw a,t_hcrw_nd b where a.id=b.hcrw_id and a.id=#{hcrwId}) and SJLY = 2")
	//T_NB_BD导入数据前先删除之前导入的数来源标志2)
	void deleteByTaskId2(String hcrwId);

	//T_NB_BD导入数据来源标志2
	void insert2(AnnualReport ar);
	
}