package com.kysoft.cpsi.audit.mapper;

import java.util.List;

import com.kysoft.cpsi.audit.entity.Gqbg;

public interface GqbgMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table T_NB_GQBG
	 * @mbggenerated  Mon May 30 19:05:06 CST 2016
	 */
	int deleteByPrimaryKey(String id);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table T_NB_GQBG
	 * @mbggenerated  Mon May 30 19:05:06 CST 2016
	 */
	int insert(Gqbg record);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table T_NB_GQBG
	 * @mbggenerated  Mon May 30 19:05:06 CST 2016
	 */
	int insertSelective(Gqbg record);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table T_NB_GQBG
	 * @mbggenerated  Mon May 30 19:05:06 CST 2016
	 */
	Gqbg selectByPrimaryKey(String id);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table T_NB_GQBG
	 * @mbggenerated  Mon May 30 19:05:06 CST 2016
	 */
	int updateByPrimaryKeySelective(Gqbg record);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table T_NB_GQBG
	 * @mbggenerated  Mon May 30 19:05:06 CST 2016
	 */
	int updateByPrimaryKey(Gqbg record);
	List<Gqbg> selectByTaskId(String hcrwId);
	List<Gqbg> selectByTaskId2(String hcrwId);
}