package com.kysoft.cpsi.audit.mapper;

import java.util.List;

import com.kysoft.cpsi.audit.entity.Guarantee;
import com.kysoft.cpsi.audit.entity.GuaranteeKey;

public interface GuaranteeMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table T_NB_DWDB
	 * @mbggenerated  Mon May 30 19:14:20 CST 2016
	 */
	int deleteByPrimaryKey(GuaranteeKey key);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table T_NB_DWDB
	 * @mbggenerated  Mon May 30 19:14:20 CST 2016
	 */
	int insert(Guarantee record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table T_NB_DWDB
	 * @mbggenerated  Mon May 30 19:14:20 CST 2016
	 */
	int insertSelective(Guarantee record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table T_NB_DWDB
	 * @mbggenerated  Mon May 30 19:14:20 CST 2016
	 */
	Guarantee selectByPrimaryKey(GuaranteeKey key);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table T_NB_DWDB
	 * @mbggenerated  Mon May 30 19:14:20 CST 2016
	 */
	int updateByPrimaryKeySelective(Guarantee record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table T_NB_DWDB
	 * @mbggenerated  Mon May 30 19:14:20 CST 2016
	 */
	int updateByPrimaryKey(Guarantee record);

	List<Guarantee> selectByTaskId(String hcrwId);
	List<Guarantee> selectByTaskId2(String hcrwId);
}