package com.kysoft.cpsi.audit.mapper;

import com.kysoft.cpsi.audit.entity.Guarantee;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface GuaranteeMapper {
    /**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table T_NB_DWDB
	 * @mbg.generated  Mon Jan 09 11:26:18 CST 2017
	 */
	int deleteByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table T_NB_DWDB
	 * @mbg.generated  Mon Jan 09 11:26:18 CST 2017
	 */
	int insert(Guarantee record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table T_NB_DWDB
	 * @mbg.generated  Mon Jan 09 11:26:18 CST 2017
	 */
	int insertSelective(Guarantee record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table T_NB_DWDB
	 * @mbg.generated  Mon Jan 09 11:26:18 CST 2017
	 */
	Guarantee selectByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table T_NB_DWDB
	 * @mbg.generated  Mon Jan 09 11:26:18 CST 2017
	 */
	int updateByPrimaryKeySelective(Guarantee record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table T_NB_DWDB
	 * @mbg.generated  Mon Jan 09 11:26:18 CST 2017
	 */
	int updateByPrimaryKey(Guarantee record);

	List<Guarantee> selectByTaskId(String hcrwId);

    List<Guarantee> selectByTaskId2(String hcrwId);
    List<Guarantee> selectByTaskId3(String hcrwId);

    @Delete("delete from T_NB_BD_DWDB where (xydm,nd) in(select a.hcdw_xydm,b.nd from t_hcrw a,t_hcrw_nd b where a.id=b.hcrw_id and a.id=#{hcrwId}) and sjly=2")
	void deleteByTaskId2(String hcrwId);
    @Delete("delete from T_NB_BD_DWDB where xydm=(select a.hcdw_xydm from t_hcrw a where a.id=#{hcrwId}) and nd=#{nd} and sjly=2")
	void deleteByTaskIdNd(@Param("hcrwId")String hcrwId, @Param("nd")Integer nd);

	void insert2(Guarantee guarantee);

}