package com.kysoft.cpsi.audit.mapper;

import java.util.List;
import java.util.Map;

import com.kysoft.cpsi.audit.entity.JsGqbg;
import com.kysoft.cpsi.audit.entity.JsGqbgKey;
import com.kysoft.cpsi.audit.entity.JsLicense;

public interface JsGqbgMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table T_JS_GQBG
	 * @mbggenerated  Thu Aug 11 14:58:43 CST 2016
	 */
	int deleteByPrimaryKey(JsGqbgKey key);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table T_JS_GQBG
	 * @mbggenerated  Thu Aug 11 14:58:43 CST 2016
	 */
	int insert(JsGqbg record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table T_JS_GQBG
	 * @mbggenerated  Thu Aug 11 14:58:43 CST 2016
	 */
	int insertSelective(JsGqbg record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table T_JS_GQBG
	 * @mbggenerated  Thu Aug 11 14:58:43 CST 2016
	 */
	JsGqbg selectByPrimaryKey(JsGqbgKey key);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table T_JS_GQBG
	 * @mbggenerated  Thu Aug 11 14:58:43 CST 2016
	 */
	int updateByPrimaryKeySelective(JsGqbg record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table T_JS_GQBG
	 * @mbggenerated  Thu Aug 11 14:58:43 CST 2016
	 */
	int updateByPrimaryKey(JsGqbg record);

	List<JsGqbg> query(Map<String,Object> param);
	List<JsGqbg> queryBD(Map<String,Object> param);

}