package com.kysoft.cpsi.audit.mapper;

import com.kysoft.cpsi.audit.entity.JsLicense;
import com.kysoft.cpsi.audit.entity.JsLicenseKey;

import java.util.List;
import java.util.Map;

public interface JsLicenseMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table T_JS_XZXK
	 * @mbggenerated  Thu Aug 11 14:58:43 CST 2016
	 */
	int deleteByPrimaryKey(JsLicenseKey key);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table T_JS_XZXK
	 * @mbggenerated  Thu Aug 11 14:58:43 CST 2016
	 */
	int insert(JsLicense record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table T_JS_XZXK
	 * @mbggenerated  Thu Aug 11 14:58:43 CST 2016
	 */
	int insertSelective(JsLicense record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table T_JS_XZXK
	 * @mbggenerated  Thu Aug 11 14:58:43 CST 2016
	 */
	JsLicense selectByPrimaryKey(JsLicenseKey key);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table T_JS_XZXK
	 * @mbggenerated  Thu Aug 11 14:58:43 CST 2016
	 */
	int updateByPrimaryKeySelective(JsLicense record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table T_JS_XZXK
	 * @mbggenerated  Thu Aug 11 14:58:43 CST 2016
	 */
	int updateByPrimaryKey(JsLicense record);

	List<JsLicense> query(Map<String,Object> param);
	List<JsLicense> queryBD(Map<String,Object> param);
}