package com.kysoft.cpsi.audit.mapper;

import com.kysoft.cpsi.audit.entity.JsLicense;
import com.kysoft.cpsi.audit.entity.JsLicenseKey;
import org.apache.ibatis.annotations.Delete;

import java.util.List;
import java.util.Map;

public interface JsLicenseMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table T_JS_XZXK
	 * @mbggenerated  Thu Aug 11 14:58:43 CST 2016
	 */
	int deleteByPrimaryKey(JsLicenseKey key);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table T_JS_XZXK
	 * @mbggenerated  Thu Aug 11 14:58:43 CST 2016
	 */
	int insert(JsLicense record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table T_JS_XZXK
	 * @mbggenerated  Thu Aug 11 14:58:43 CST 2016
	 */
	int insertSelective(JsLicense record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table T_JS_XZXK
	 * @mbggenerated  Thu Aug 11 14:58:43 CST 2016
	 */
	JsLicense selectByPrimaryKey(JsLicenseKey key);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table T_JS_XZXK
	 * @mbggenerated  Thu Aug 11 14:58:43 CST 2016
	 */
	int updateByPrimaryKeySelective(JsLicense record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table T_JS_XZXK
	 * @mbggenerated  Thu Aug 11 14:58:43 CST 2016
	 */
	int updateByPrimaryKey(JsLicense record);

	List<JsLicense> query(Map<String,Object> param);
	List<JsLicense> queryBD(Map<String,Object> param);

	@Delete("delete from T_JS_BD_XZXK where HCRW_ID = #{taskId,jdbcType=VARCHAR} and sjly=5")
	void deleteByTaskId2(String taskId);

	void insert2(JsLicense jsLicense);
}