package com.kysoft.cpsi.audit.mapper;

import com.kysoft.cpsi.audit.entity.JsStockholderContribution;
import com.kysoft.cpsi.audit.entity.JsStockholderContributionKey;
import org.apache.ibatis.annotations.Delete;

import java.util.List;
import java.util.Map;

public interface JsStockholderContributionMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table T_JS_GDCZ
	 * @mbggenerated  Thu Aug 11 14:58:43 CST 2016
	 */
	int deleteByPrimaryKey(JsStockholderContributionKey key);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table T_JS_GDCZ
	 * @mbggenerated  Thu Aug 11 14:58:43 CST 2016
	 */
	int insert(JsStockholderContribution record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table T_JS_GDCZ
	 * @mbggenerated  Thu Aug 11 14:58:43 CST 2016
	 */
	int insertSelective(JsStockholderContribution record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table T_JS_GDCZ
	 * @mbggenerated  Thu Aug 11 14:58:43 CST 2016
	 */
	JsStockholderContribution selectByPrimaryKey(JsStockholderContributionKey key);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table T_JS_GDCZ
	 * @mbggenerated  Thu Aug 11 14:58:43 CST 2016
	 */
	int updateByPrimaryKeySelective(JsStockholderContribution record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table T_JS_GDCZ
	 * @mbggenerated  Thu Aug 11 14:58:43 CST 2016
	 */
	int updateByPrimaryKey(JsStockholderContribution record);

	List<JsStockholderContribution> query(Map<String,Object> param);
	List<JsStockholderContribution> queryBD(Map<String,Object> param);

	@Delete("delete from T_JS_BD_GDCZ where HCRW_ID = #{taskId,jdbcType=VARCHAR} and sjly=5")
	void deleteByTaskId2(String taskId);

	void insert2(JsStockholderContribution jsStockholderContribution);
}