package com.kysoft.cpsi.audit.mapper;

import com.kysoft.cpsi.audit.entity.JsXzcf;
import com.kysoft.cpsi.audit.entity.JsXzcfKey;
import org.apache.ibatis.annotations.Delete;

import java.util.List;
import java.util.Map;

public interface JsXzcfMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table T_JS_XZCF
	 * @mbg.generated  Mon Jan 09 11:29:39 CST 2017
	 */
	int deleteByPrimaryKey(JsXzcfKey key);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table T_JS_XZCF
	 * @mbg.generated  Mon Jan 09 11:29:39 CST 2017
	 */
	int insert(JsXzcf record);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table T_JS_XZCF
	 * @mbg.generated  Mon Jan 09 11:29:39 CST 2017
	 */
	int insertSelective(JsXzcf record);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table T_JS_XZCF
	 * @mbg.generated  Mon Jan 09 11:29:39 CST 2017
	 */
	JsXzcf selectByPrimaryKey(JsXzcfKey key);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table T_JS_XZCF
	 * @mbg.generated  Mon Jan 09 11:29:39 CST 2017
	 */
	int updateByPrimaryKeySelective(JsXzcf record);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table T_JS_XZCF
	 * @mbg.generated  Mon Jan 09 11:29:39 CST 2017
	 */
	int updateByPrimaryKey(JsXzcf record);
	List<JsXzcf> query(Map<String,Object> param);
	List<JsXzcf> queryBD(Map<String,Object> param);

	@Delete("delete from T_JS_BD_XZCF where xydm=(select a.hcdw_xydm from t_hcrw a where a.id=#{hcrwId}) and sjly=5")
	void deleteByTaskId2(String hcrwId);

	void insert2(JsXzcf jsXzcf);
}