package com.kysoft.cpsi.audit.mapper;

import com.kysoft.cpsi.audit.entity.JsZscq;
import com.kysoft.cpsi.audit.entity.JsZscqKey;
import org.apache.ibatis.annotations.Delete;

import java.util.List;
import java.util.Map;

public interface JsZscqMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table T_JS_ZSCQ
	 * @mbg.generated  Mon Jan 09 11:29:39 CST 2017
	 */
	int deleteByPrimaryKey(JsZscqKey key);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table T_JS_ZSCQ
	 * @mbg.generated  Mon Jan 09 11:29:39 CST 2017
	 */
	int insert(JsZscq record);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table T_JS_ZSCQ
	 * @mbg.generated  Mon Jan 09 11:29:39 CST 2017
	 */
	int insertSelective(JsZscq record);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table T_JS_ZSCQ
	 * @mbg.generated  Mon Jan 09 11:29:39 CST 2017
	 */
	JsZscq selectByPrimaryKey(JsZscqKey key);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table T_JS_ZSCQ
	 * @mbg.generated  Mon Jan 09 11:29:39 CST 2017
	 */
	int updateByPrimaryKeySelective(JsZscq record);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table T_JS_ZSCQ
	 * @mbg.generated  Mon Jan 09 11:29:39 CST 2017
	 */
	int updateByPrimaryKey(JsZscq record);
	List<JsZscq> query(Map<String,Object> param);
	List<JsZscq> queryBD(Map<String,Object> param);

	@Delete("delete from T_JS_BD_ZSCQ where xydm=(select a.hcdw_xydm from t_hcrw a where a.id=#{hcrwId}) and sjly=5")
	void deleteByTaskId2(String hcrwId);

	void insert2(JsZscq jsZscq);
}