package com.kysoft.cpsi.audit.mapper;

import com.kysoft.cpsi.audit.entity.License;

import java.util.List;

public interface LicenseMapper {

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table T_NB_XZXK
     *
     * @mbggenerated Tue May 31 10:35:29 CST 2016
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table T_NB_XZXK
     *
     * @mbggenerated Tue May 31 10:35:29 CST 2016
     */
    int insert(License record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table T_NB_XZXK
     *
     * @mbggenerated Tue May 31 10:35:29 CST 2016
     */
    int insertSelective(License record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table T_NB_XZXK
     *
     * @mbggenerated Tue May 31 10:35:29 CST 2016
     */
    License selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table T_NB_XZXK
     *
     * @mbggenerated Tue May 31 10:35:29 CST 2016
     */
    int updateByPrimaryKeySelective(License record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table T_NB_XZXK
     *
     * @mbggenerated Tue May 31 10:35:29 CST 2016
     */
    int updateByPrimaryKey(License record);

    List<License> selectByTaskId(String hcrwId);

    List<License> selectByTaskId2(String hcrwId);

}