package com.kysoft.cpsi.audit.mapper;

import com.kysoft.cpsi.audit.entity.LoginToken;

public interface LoginTokenMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table T_TOKEN
	 * @mbggenerated  Wed Jun 01 14:24:56 CST 2016
	 */
	int deleteByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table T_TOKEN
	 * @mbggenerated  Wed Jun 01 14:24:56 CST 2016
	 */
	int insert(LoginToken record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table T_TOKEN
	 * @mbggenerated  Wed Jun 01 14:24:56 CST 2016
	 */
	int insertSelective(LoginToken record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table T_TOKEN
	 * @mbggenerated  Wed Jun 01 14:24:56 CST 2016
	 */
	LoginToken selectByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table T_TOKEN
	 * @mbggenerated  Wed Jun 01 14:24:56 CST 2016
	 */
	int updateByPrimaryKeySelective(LoginToken record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table T_TOKEN
	 * @mbggenerated  Wed Jun 01 14:24:56 CST 2016
	 */
	int updateByPrimaryKey(LoginToken record);
}