package com.kysoft.cpsi.audit.mapper;

import com.kysoft.cpsi.audit.entity.StockholderContribution;

import java.util.List;

import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Update;

public interface StockholderContributionMapper {

    /**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table T_NB_GDCZ
	 * @mbggenerated  Sat Jun 25 09:54:30 CST 2016
	 */
	int deleteByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table T_NB_GDCZ
	 * @mbggenerated  Sat Jun 25 09:54:30 CST 2016
	 */
	int insert(StockholderContribution record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table T_NB_GDCZ
	 * @mbggenerated  Sat Jun 25 09:54:30 CST 2016
	 */
	int insertSelective(StockholderContribution record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table T_NB_GDCZ
	 * @mbggenerated  Sat Jun 25 09:54:30 CST 2016
	 */
	StockholderContribution selectByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table T_NB_GDCZ
	 * @mbggenerated  Sat Jun 25 09:54:30 CST 2016
	 */
	int updateByPrimaryKeySelective(StockholderContribution record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table T_NB_GDCZ
	 * @mbggenerated  Sat Jun 25 09:54:30 CST 2016
	 */
	int updateByPrimaryKey(StockholderContribution record);

	List<StockholderContribution> selectByTaskId(String hcrwId);

    List<StockholderContribution> selectByTaskId2(String hcrwId);

    
	@Delete("delete from T_NB_BD_GDCZ where HCRW_ID = #{taskId,jdbcType=VARCHAR}")
	void deleteByTaskId(String taskId);

}