drop table gov_nbcc_jh_qy;
create table gov_nbcc_jh_qy(
  XH varchar2(100),
  JHXH varchar2(100),
  NBXH varchar2(100),
  ZCH varchar2(100),
  QYMC varchar2(100),
  FDDBR varchar2(100),
  QYLXDL varchar2(100),
  DJJG varchar2(100),
  GXDW varchar2(100),
  XCR varchar2(100),
  XCSJ varchar2(100),
  WCBJ varchar2(100),
  ND varchar2(100)
);
comment on table gov_nbcc_jh_qy is '抽查企业名单';
comment on column gov_nbcc_jh_qy.XH is '序号';
comment on column gov_nbcc_jh_qy.JHXH is '计划序号';
comment on column gov_nbcc_jh_qy.NBXH is '内部序号';
comment on column gov_nbcc_jh_qy.ZCH is '注册号';
comment on column gov_nbcc_jh_qy.QYMC is '企业名称';
comment on column gov_nbcc_jh_qy.FDDBR is '负责人';
comment on column gov_nbcc_jh_qy.QYLXDL is '企业类型大类';
comment on column gov_nbcc_jh_qy.DJJG is '登记机关';
comment on column gov_nbcc_jh_qy.GXDW is '管辖单位';
comment on column gov_nbcc_jh_qy.XCR is '检查人';
comment on column gov_nbcc_jh_qy.XCSJ is '巡查时间';
comment on column gov_nbcc_jh_qy.WCBJ is '序号';
comment on column gov_nbcc_jh_qy.ND is '年度';

drop table bm_djjg;
create table bm_djjg(
  code varchar2(100),
  content varchar2(100),
  djjgjc varchar2(100),
  sjcode varchar2(100)
);
comment on table bm_djjg is '登记机关';
comment on column bm_djjg.code is '单位编码';
comment on column bm_djjg.content is '单位名称';
comment on column bm_djjg.djjgjc is '登记机关简称';
comment on column bm_djjg.sjcode is '上级单位编码';

drop table bm_gxdw;
create table bm_gxdw(
  code varchar2(100),
  content varchar2(100)
);
comment on table bm_gxdw is '管辖单位';
comment on column bm_gxdw.code is '管辖单位编码';
comment on column bm_gxdw.content is '管辖单位名称';

drop table bm_hy;
create table bm_hy(
  code varchar2(100),content varchar2(100),ml varchar2(100)
);
comment on table bm_hy is '行业';
comment on column bm_hy.code is '行业编码';
comment on column bm_hy.content is '行业名称';
comment on column bm_hy.ml is '';

drop table v_ajgs;
create table v_ajgs(
  AJBH varchar2(100),
  CZRY varchar2(100),
  CZSJ varchar2(100),
  TYPE varchar2(100),
  SHZT varchar2(100),
  SHYJ varchar2(100),
  YJMS varchar2(100),
  NBXH varchar2(100),
  YJMSCS varchar2(100),
  YJMSFS varchar2(100),
  PENDECNO varchar2(100),
  ILLEGACTTYPE varchar2(1000),
  PENTYPE varchar2(100),
  PENAM varchar2(100),
  FORFAM varchar2(100),
  PENAUTH varchar2(100),
  PENDECISSDATE varchar2(100),
  UNITNAME varchar2(100),
  REGNO varchar2(100),
  LEREP varchar2(100),
  XZCFNR varchar2(4000),
  CSTUYJ varchar2(100),
  TUBZ varchar2(100),
  AJZT varchar2(100),
  UPTIME varchar2(100),
  UPNAME varchar2(100),
  OTHERPROVINCE varchar2(100),
  ENTDOMINATION varchar2(100),
  DSRID varchar2(100),
  GSBH varchar2(100)
);
comment on table v_ajgs is '即时_行政处罚';
comment on column V_AJGS.AJBH is '案件编号';
comment on column V_AJGS.CZRY is '';
comment on column V_AJGS.CZSJ is '';
comment on column V_AJGS.TYPE is '';
comment on column V_AJGS.SHZT is '';
comment on column V_AJGS.SHYJ is '';
comment on column V_AJGS.YJMS is '';
comment on column V_AJGS.NBXH is '内部序号';
comment on column V_AJGS.YJMSCS is '';
comment on column V_AJGS.YJMSFS is '';
comment on column V_AJGS.PENDECNO is '处罚单编号';
comment on column V_AJGS.ILLEGACTTYPE is '处罚原因  ';
comment on column V_AJGS.PENTYPE is '';
comment on column V_AJGS.PENAM is '';
comment on column V_AJGS.FORFAM is '';
comment on column V_AJGS.PENAUTH is '';
comment on column V_AJGS.PENDECISSDATE is '';
comment on column V_AJGS.UNITNAME is '';
comment on column V_AJGS.REGNO is '';
comment on column V_AJGS.LEREP is '';
comment on column V_AJGS.XZCFNR is '行政处罚内容';
comment on column V_AJGS.CSTUYJ is '';
comment on column V_AJGS.TUBZ is '';
comment on column V_AJGS.AJZT is '';
comment on column V_AJGS.UPTIME is '';
comment on column V_AJGS.UPNAME is '';
comment on column V_AJGS.OTHERPROVINCE is '';
comment on column V_AJGS.ENTDOMINATION is '';
comment on column V_AJGS.DSRID is '';
comment on column V_AJGS.GSBH is '';

drop table v_qy_bgnrdb;
create table v_qy_bgnrdb(
  BFXH varchar2(100),
  XH varchar2(100),
  SEQ varchar2(100),
  NBXH varchar2(100),
  ALT varchar2(100),
  ALTBE varchar2(1000),
  ALTAF varchar2(1000),
  BGCS varchar2(100),
  HZRQ varchar2(100),
  WZGF varchar2(100),
  NZGF varchar2(100),
  BGNRS varchar2(1000),
  BGHNRS varchar2(1000),
  ALTDATE varchar2(100)
);
comment on table v_qy_bgnrdb is '即时_企业_股权变更';
comment on column V_QY_BGNRDB.BFXH is '';
comment on column V_QY_BGNRDB.XH is '';
comment on column V_QY_BGNRDB.SEQ is '';
comment on column V_QY_BGNRDB.NBXH is '';
comment on column V_QY_BGNRDB.ALT is '';
comment on column V_QY_BGNRDB.ALTBE is '';
comment on column V_QY_BGNRDB.ALTAF is '';
comment on column V_QY_BGNRDB.BGCS is '';
comment on column V_QY_BGNRDB.HZRQ is '';
comment on column V_QY_BGNRDB.WZGF is '';
comment on column V_QY_BGNRDB.NZGF is '';
comment on column V_QY_BGNRDB.BGNRS is '';
comment on column V_QY_BGNRDB.BGHNRS is '';
comment on column V_QY_BGNRDB.ALTDATE is '';

drop table v_qy_qycfxx;
create table v_qy_qycfxx(
  XH varchar2(100),
  NBXH varchar2(100),
  PENTYPE varchar2(100),
  PENAM varchar2(100),
  PENDECNO varchar2(1000),
  WFNR varchar2(100),
  PENDECISSDATE varchar2(100),
  CFSFLX varchar2(100),
  PENAUTH varchar2(100),
  ZXQK varchar2(100),
  LYDQ varchar2(100),
  LRRQ varchar2(100),
  CJFS varchar2(100),
  SHDW varchar2(100),
  SHR varchar2(100),
  SHRQ varchar2(100),
  QYMC varchar2(100),
  WFLX varchar2(100),
  SFSX varchar2(100),
  WFZLMS varchar2(100),
  WFZLXL varchar2(100),
  WFZLXLMS varchar2(100),
  ILLEGACTTYPE varchar2(100),
  SFGS varchar2(100),
  FORFAM varchar2(100),
  BZ varchar2(100)
);
comment on table v_qy_qycfxx is '即时_企业公示_处罚信息';
comment on column V_QY_QYCFXX.XH is '';
comment on column V_QY_QYCFXX.NBXH is '内部序号';
comment on column V_QY_QYCFXX.PENTYPE is '';
comment on column V_QY_QYCFXX.PENAM is '';
comment on column V_QY_QYCFXX.PENDECNO is '处罚单编号';
comment on column V_QY_QYCFXX.WFNR is '';
comment on column V_QY_QYCFXX.PENDECISSDATE is '处罚日期';
comment on column V_QY_QYCFXX.CFSFLX is '';
comment on column V_QY_QYCFXX.PENAUTH is '';
comment on column V_QY_QYCFXX.ZXQK is '';
comment on column V_QY_QYCFXX.LYDQ is '';
comment on column V_QY_QYCFXX.LRRQ is '录入日期';
comment on column V_QY_QYCFXX.CJFS is '';
comment on column V_QY_QYCFXX.SHDW is '';
comment on column V_QY_QYCFXX.SHR is '';
comment on column V_QY_QYCFXX.SHRQ is '';
comment on column V_QY_QYCFXX.QYMC is '企业名称';
comment on column V_QY_QYCFXX.WFLX is '';
comment on column V_QY_QYCFXX.SFSX is '';
comment on column V_QY_QYCFXX.WFZLMS is '';
comment on column V_QY_QYCFXX.WFZLXL is '';
comment on column V_QY_QYCFXX.WFZLXLMS is '';
comment on column V_QY_QYCFXX.ILLEGACTTYPE is '违法类型';
comment on column V_QY_QYCFXX.SFGS is '';
comment on column V_QY_QYCFXX.FORFAM is '';
comment on column V_QY_QYCFXX.BZ is '';

drop table gov_nbcc_jh;
create table gov_nbcc_jh(
  JHXH varchar2(100),
  ND varchar2(100),
  DJJG varchar2(100),
  JHLX varchar2(100),
  JHMC varchar2(100),
  KSSJ varchar2(100),
  JSSJ varchar2(100),
  JHNR varchar2(100),
  JHZT varchar2(100),
  JSBJ varchar2(100),
  CCQYS varchar2(100),
  WWC varchar2(100),
  YWC varchar2(100),
  ZC varchar2(100),
  YC varchar2(100),
  CREATOR varchar2(100),
  CREATETIME varchar2(100),
  QYLXDL varchar2(100),
  HY varchar2(100),
  CLRQQ varchar2(100),
  CLRQZ varchar2(100),
  CCZT varchar2(100),
  CCDJJG varchar2(100),
  CCDJJG_KC varchar2(100),
  CCWH varchar2(100),
  CCBL varchar2(100),
  QYLX varchar2(100),
  CLRQJD varchar2(100),
  SFNB varchar2(100),
  NBND varchar2(100)
);
comment on table GOV_NBCC_JH is '计划任务';
comment on column GOV_NBCC_JH.JHXH is '计划序号';
comment on column GOV_NBCC_JH.ND is '计划年度';
comment on column GOV_NBCC_JH.DJJG is '登记机关';
comment on column GOV_NBCC_JH.JHLX is '计划类型';
comment on column GOV_NBCC_JH.JHMC is '计划名称';
comment on column GOV_NBCC_JH.KSSJ is '开始时间';
comment on column GOV_NBCC_JH.JSSJ is '结束时间';
comment on column GOV_NBCC_JH.JHNR is '计划内容';
comment on column GOV_NBCC_JH.JHZT is '计划状态';
comment on column GOV_NBCC_JH.JSBJ is '';
comment on column GOV_NBCC_JH.CCQYS is '抽查企业数';
comment on column GOV_NBCC_JH.WWC is '未完成';
comment on column GOV_NBCC_JH.YWC is '应完成';
comment on column GOV_NBCC_JH.ZC is '';
comment on column GOV_NBCC_JH.YC is '';
comment on column GOV_NBCC_JH.CREATOR is '';
comment on column GOV_NBCC_JH.CREATETIME is '计划生成时间';
comment on column GOV_NBCC_JH.QYLXDL is '企业类型大类';
comment on column GOV_NBCC_JH.HY is '行业';
comment on column GOV_NBCC_JH.CLRQQ is '成立起始日';
comment on column GOV_NBCC_JH.CLRQZ is '成立终止日';
comment on column GOV_NBCC_JH.CCZT is '抽查状态';
comment on column GOV_NBCC_JH.CCDJJG is '抽查登记机关';
comment on column GOV_NBCC_JH.CCDJJG_KC is '';
comment on column GOV_NBCC_JH.CCWH is '抽查文号';
comment on column GOV_NBCC_JH.CCBL is '';
comment on column GOV_NBCC_JH.QYLX is '企业类型';
comment on column GOV_NBCC_JH.CLRQJD is '处理日期节点';
comment on column GOV_NBCC_JH.SFNB is '';
comment on column GOV_NBCC_JH.NBND is '年报年度';

drop table v_nnb_fgdj;
create table v_nnb_fgdj(
  NBXH varchar2(100),
  ND varchar2(100),
  XH varchar2(100),
  PARINS varchar2(100),
  DZZZJFS varchar2(100),
  NUMPARM varchar2(100),
  BNZJBZ varchar2(100),
  RESPARMSIGN varchar2(100),
  RESPARSECSIGN varchar2(100),
  CJSJ varchar2(100),
  ZJSJ varchar2(100),
  QYLX varchar2(100),
  DJZDYBZ varchar2(100),
  BNXZDYRS varchar2(100)
);
comment on table V_NNB_FGDJ is '年报_非公党建';
comment on column V_NNB_FGDJ.NBXH is '内部序号';
comment on column V_NNB_FGDJ.ND is '年度';
comment on column V_NNB_FGDJ.XH is '';
comment on column V_NNB_FGDJ.PARINS is '';
comment on column V_NNB_FGDJ.DZZZJFS is '';
comment on column V_NNB_FGDJ.NUMPARM is '党员人数';
comment on column V_NNB_FGDJ.BNZJBZ is '';
comment on column V_NNB_FGDJ.RESPARMSIGN is '';
comment on column V_NNB_FGDJ.RESPARSECSIGN is '';
comment on column V_NNB_FGDJ.CJSJ is '';
comment on column V_NNB_FGDJ.ZJSJ is '组建时间';
comment on column V_NNB_FGDJ.QYLX is '';
comment on column V_NNB_FGDJ.DJZDYBZ is '';
comment on column V_NNB_FGDJ.BNXZDYRS is '';

drop table v_nnb_fqczqk;
create table v_nnb_fqczqk(
  NBXH varchar2(100),
  ND varchar2(100),
  SEQ varchar2(100),
  CZQS varchar2(100),
  QXJZ varchar2(100),
  YCZE varchar2(100),
  SJCZE varchar2(100),
  SJCZSJ varchar2(100),
  YCZEMY varchar2(100),
  WFYCZEMY varchar2(100),
  SJCZEMY varchar2(100),
  WFSJCZEMY varchar2(100)
);
comment on table V_NNB_FQCZQK is '年报_股东出资情况';
comment on column V_NNB_FQCZQK.NBXH is '内部序号';
comment on column V_NNB_FQCZQK.ND is '年度';
comment on column V_NNB_FQCZQK.SEQ is '';
comment on column V_NNB_FQCZQK.CZQS is '出资起始时间';
comment on column V_NNB_FQCZQK.QXJZ is '出资结束时间';
comment on column V_NNB_FQCZQK.YCZE is '应出资额';
comment on column V_NNB_FQCZQK.SJCZE is '实际出资额';
comment on column V_NNB_FQCZQK.SJCZSJ is '实际出资时间';
comment on column V_NNB_FQCZQK.YCZEMY is '应出资金额';
comment on column V_NNB_FQCZQK.WFYCZEMY is '';
comment on column V_NNB_FQCZQK.SJCZEMY is '实际出资额';
comment on column V_NNB_FQCZQK.WFSJCZEMY is '';

drop table v_nnb_gqbg;
create table v_nnb_gqbg(
  NBXH varchar2(100),
  ND varchar2(100),
  XH varchar2(100),
  INV varchar2(100),
  ALTDATE varchar2(100),
  TRANSAMPR varchar2(100),
  TRANSAMOR varchar2(100)
);
comment on table V_NNB_GQBG is '年报_股权变更';
comment on column V_NNB_GQBG.NBXH is '内部序号';
comment on column V_NNB_GQBG.ND is '年度';
comment on column V_NNB_GQBG.XH is '';
comment on column V_NNB_GQBG.INV is '股东名称';
comment on column V_NNB_GQBG.ALTDATE is '变更时间';
comment on column V_NNB_GQBG.TRANSAMPR is '变更前股权比例';
comment on column V_NNB_GQBG.TRANSAMOR is '变更后股权比例';

drop table v_nnb_jbqk;
create table v_nnb_jbqk(
  FQR VARCHAR2 (4000),
  YYZK VARCHAR2 (100),
  ZYYWXM VARCHAR2 (4000),
  BZSM VARCHAR2 (4000),
  ZCXS VARCHAR2 (100),
  YWFW VARCHAR2 (4000),
  REGNO VARCHAR2 (100),
  LSQY VARCHAR2 (100),
  NBXH VARCHAR2 (100),
  ND VARCHAR2 (100),
  ZS VARCHAR2 (4000),
  FDDBR VARCHAR2 (100),
  YQMC VARCHAR2 (1000),
  YYQX_QS VARCHAR2 (100),
  YYQX_JZ VARCHAR2 (100),
  ZCZJ VARCHAR2 (100),
  QYLX VARCHAR2 (100),
  JYFS_JYFW VARCHAR2 (4000),
  JYCS VARCHAR2 (100),
  SSZB VARCHAR2 (100),
  JYFW VARCHAR2 (4000),
  JYFS VARCHAR2 (100),
  CYRS VARCHAR2 (100),
  CZFS VARCHAR2 (100),
  QZXK VARCHAR2 (100),
  YBJY VARCHAR2 (100),
  JYLB VARCHAR2 (100),
  SSHY VARCHAR2 (100),
  CLRQ VARCHAR2 (100),
  BELONG_EPNAME VARCHAR2 (100),
  BELONG_EPZCH VARCHAR2 (100),
  BELONG_EPZS VARCHAR2 (100),
  JYFWDJXKZ VARCHAR2 (4000),
  JYFWDJXKZNR VARCHAR2 (4000),
  JYFWQZXKXM VARCHAR2 (4000),
  JYFWQZXKXMNR VARCHAR2 (4000),
  JYFWYBDJXM VARCHAR2 (4000),
  JYFWYBDJXMNR VARCHAR2 (4000),
  GDXMSFBG VARCHAR2 (100),
  GDAQJCZE VARCHAR2 (100),
  ZCSFXG VARCHAR2 (100),
  ZCSFBA VARCHAR2 (100),
  ZCSJQK VARCHAR2 (4000),
  DSSFBD VARCHAR2 (100),
  DSSFBA VARCHAR2 (100),
  DSSJQK VARCHAR2 (4000),
  JSSFBD VARCHAR2 (100),
  JSSFBA VARCHAR2 (100),
  JSSJQK VARCHAR2 (4000),
  JLSFBD VARCHAR2 (100),
  JLSFBA VARCHAR2 (100),
  JLSJQK VARCHAR2 (4000),
  SFYFGS VARCHAR2 (100),
  FGSSFBD VARCHAR2 (100),
  FGSSFBA VARCHAR2 (100),
  FGSSJQK VARCHAR2 (4000),
  SFQS VARCHAR2 (100),
  QSZSFBD VARCHAR2 (100),
  QSZSFBA VARCHAR2 (100),
  QSZSJQK VARCHAR2 (4000),
  JYXMQZXZXK VARCHAR2 (100),
  QZXZXKSFYX VARCHAR2 (100),
  GDSFBD VARCHAR2 (100),
  GDSFBA VARCHAR2 (100),
  GDSJQK VARCHAR2 (4000),
  DSJSSFBG VARCHAR2 (100),
  DSJSSFBA VARCHAR2 (100),
  DSJSSJQK VARCHAR2 (4000),
  ZGBMSFBG VARCHAR2 (100),
  ZGBMSFBA VARCHAR2 (100),
  ZGBMSJQK VARCHAR2 (4000),
  TZZEMY VARCHAR2 (100),
  ZCZBMY VARCHAR2 (100),
  ZFRJMY VARCHAR2 (100),
  WFRJMY VARCHAR2 (100),
  SSZBMY VARCHAR2 (100),
  ZFSJMY VARCHAR2 (100),
  WFSJMY VARCHAR2 (100),
  WQSFCX VARCHAR2 (100),
  WQCXQX VARCHAR2 (100),
  ZXSWHHRSFBD VARCHAR2 (100),
  ZXSWHHRSFBA VARCHAR2 (100),
  HHRSFBD VARCHAR2 (100),
  HHRSFBA VARCHAR2 (100),
  HHRCZSFBD VARCHAR2 (100),
  HHRCZSFBA VARCHAR2 (100),
  GBDQ VARCHAR2 (100)
);
comment on table V_NNB_JBQK is '年报_基本情况';
comment on column V_NNB_JBQK.FQR is '';
comment on column V_NNB_JBQK.YYZK is '';
comment on column V_NNB_JBQK.ZYYWXM is '';
comment on column V_NNB_JBQK.BZSM is '';
comment on column V_NNB_JBQK.ZCXS is '';
comment on column V_NNB_JBQK.YWFW is '';
comment on column V_NNB_JBQK.REGNO is '';
comment on column V_NNB_JBQK.LSQY is '';
comment on column V_NNB_JBQK.NBXH is '内部序号';
comment on column V_NNB_JBQK.ND is '年报年度';
comment on column V_NNB_JBQK.ZS is '地址';
comment on column V_NNB_JBQK.FDDBR is '负责人';
comment on column V_NNB_JBQK.YQMC is '企业名称';
comment on column V_NNB_JBQK.YYQX_QS is '营业期限_起始';
comment on column V_NNB_JBQK.YYQX_JZ is '营业期限_终止';
comment on column V_NNB_JBQK.ZCZJ is '注册资金';
comment on column V_NNB_JBQK.QYLX is '企业类型';
comment on column V_NNB_JBQK.JYFS_JYFW is '';
comment on column V_NNB_JBQK.JYCS is '';
comment on column V_NNB_JBQK.SSZB is '';
comment on column V_NNB_JBQK.JYFW is '经营范围';
comment on column V_NNB_JBQK.JYFS is '';
comment on column V_NNB_JBQK.CYRS is '';
comment on column V_NNB_JBQK.CZFS is '';
comment on column V_NNB_JBQK.QZXK is '';
comment on column V_NNB_JBQK.YBJY is '';
comment on column V_NNB_JBQK.JYLB is '';
comment on column V_NNB_JBQK.SSHY is '';
comment on column V_NNB_JBQK.CLRQ is '';
comment on column V_NNB_JBQK.BELONG_EPNAME is '';
comment on column V_NNB_JBQK.BELONG_EPZCH is '';
comment on column V_NNB_JBQK.BELONG_EPZS is '';
comment on column V_NNB_JBQK.JYFWDJXKZ is '';
comment on column V_NNB_JBQK.JYFWDJXKZNR is '';
comment on column V_NNB_JBQK.JYFWQZXKXM is '';
comment on column V_NNB_JBQK.JYFWQZXKXMNR is '';
comment on column V_NNB_JBQK.JYFWYBDJXM is '';
comment on column V_NNB_JBQK.JYFWYBDJXMNR is '';
comment on column V_NNB_JBQK.GDXMSFBG is '';
comment on column V_NNB_JBQK.GDAQJCZE is '';
comment on column V_NNB_JBQK.ZCSFXG is '';
comment on column V_NNB_JBQK.ZCSFBA is '';
comment on column V_NNB_JBQK.ZCSJQK is '';
comment on column V_NNB_JBQK.DSSFBD is '';
comment on column V_NNB_JBQK.DSSFBA is '';
comment on column V_NNB_JBQK.DSSJQK is '';
comment on column V_NNB_JBQK.JSSFBD is '';
comment on column V_NNB_JBQK.JSSFBA is '';
comment on column V_NNB_JBQK.JSSJQK is '';
comment on column V_NNB_JBQK.JLSFBD is '';
comment on column V_NNB_JBQK.JLSFBA is '';
comment on column V_NNB_JBQK.JLSJQK is '';
comment on column V_NNB_JBQK.SFYFGS is '';
comment on column V_NNB_JBQK.FGSSFBD is '';
comment on column V_NNB_JBQK.FGSSFBA is '';
comment on column V_NNB_JBQK.FGSSJQK is '';
comment on column V_NNB_JBQK.SFQS is '';
comment on column V_NNB_JBQK.QSZSFBD is '';
comment on column V_NNB_JBQK.QSZSFBA is '';
comment on column V_NNB_JBQK.QSZSJQK is '';
comment on column V_NNB_JBQK.JYXMQZXZXK is '';
comment on column V_NNB_JBQK.QZXZXKSFYX is '';
comment on column V_NNB_JBQK.GDSFBD is '';
comment on column V_NNB_JBQK.GDSFBA is '';
comment on column V_NNB_JBQK.GDSJQK is '';
comment on column V_NNB_JBQK.DSJSSFBG is '';
comment on column V_NNB_JBQK.DSJSSFBA is '';
comment on column V_NNB_JBQK.DSJSSJQK is '';
comment on column V_NNB_JBQK.ZGBMSFBG is '';
comment on column V_NNB_JBQK.ZGBMSFBA is '';
comment on column V_NNB_JBQK.ZGBMSJQK is '';
comment on column V_NNB_JBQK.TZZEMY is '';
comment on column V_NNB_JBQK.ZCZBMY is '';
comment on column V_NNB_JBQK.ZFRJMY is '';
comment on column V_NNB_JBQK.WFRJMY is '';
comment on column V_NNB_JBQK.SSZBMY is '';
comment on column V_NNB_JBQK.ZFSJMY is '';
comment on column V_NNB_JBQK.WFSJMY is '';
comment on column V_NNB_JBQK.WQSFCX is '';
comment on column V_NNB_JBQK.WQCXQX is '';
comment on column V_NNB_JBQK.ZXSWHHRSFBD is '';
comment on column V_NNB_JBQK.ZXSWHHRSFBA is '';
comment on column V_NNB_JBQK.HHRSFBD is '';
comment on column V_NNB_JBQK.HHRSFBA is '';
comment on column V_NNB_JBQK.HHRCZSFBD is '';
comment on column V_NNB_JBQK.HHRCZSFBA is '';
comment on column V_NNB_JBQK.GBDQ is '';

drop table v_nnb_jyqk;
create table v_nnb_jyqk(
  NBXH VARCHAR2 (100),
  ND VARCHAR2 (100),
  YYE VARCHAR2 (100),
  FWYYSL VARCHAR2 (100),
  GNXSE VARCHAR2 (100),
  FWYYE VARCHAR2 (100),
  NSZE VARCHAR2 (100),
  GS VARCHAR2 (100),
  LRZE VARCHAR2 (100),
  SHLR VARCHAR2 (100),
  ZCZE VARCHAR2 (100),
  CQTZ VARCHAR2 (100),
  FZZE VARCHAR2 (100),
  CQFZ VARCHAR2 (100),
  YWJYQ VARCHAR2 (100),
  SZJWTZ VARCHAR2 (100),
  JCKDL VARCHAR2 (100),
  JCKZY VARCHAR2 (100),
  DNTZ VARCHAR2 (100),
  DWTZ VARCHAR2 (100),
  YZJGMC VARCHAR2 (100),
  YYZK VARCHAR2 (100),
  TCKYRQ VARCHAR2 (100),
  KSJFZCSCDYY VARCHAR2 (1000),
  SFCBJYGL VARCHAR2 (100),
  CBBQYDCBQYMC VARCHAR2 (100),
  QJCZYY VARCHAR2 (100),
  GYZCCZE VARCHAR2 (100),
  KS VARCHAR2 (100)
);
comment on table V_NNB_JYQK is '年报_经营情况';
comment on column V_NNB_JYQK.NBXH is '内部序号';
comment on column V_NNB_JYQK.ND is '年度';
comment on column V_NNB_JYQK.YYE is '营业额';
comment on column V_NNB_JYQK.FWYYSL is '';
comment on column V_NNB_JYQK.GNXSE is '主营业务营业额';
comment on column V_NNB_JYQK.FWYYE is '';
comment on column V_NNB_JYQK.NSZE is '纳税总额';
comment on column V_NNB_JYQK.GS is '个税';
comment on column V_NNB_JYQK.LRZE is '利润总额';
comment on column V_NNB_JYQK.SHLR is '税后利润';
comment on column V_NNB_JYQK.ZCZE is '资产总额';
comment on column V_NNB_JYQK.CQTZ is '产权投资';
comment on column V_NNB_JYQK.FZZE is '负债总额';
comment on column V_NNB_JYQK.CQFZ is '';
comment on column V_NNB_JYQK.YWJYQ is '';
comment on column V_NNB_JYQK.SZJWTZ is '';
comment on column V_NNB_JYQK.JCKDL is '';
comment on column V_NNB_JYQK.JCKZY is '';
comment on column V_NNB_JYQK.DNTZ is '';
comment on column V_NNB_JYQK.DWTZ is '';
comment on column V_NNB_JYQK.YZJGMC is '验资机构名称';
comment on column V_NNB_JYQK.YYZK is '';
comment on column V_NNB_JYQK.TCKYRQ is '';
comment on column V_NNB_JYQK.KSJFZCSCDYY is '';
comment on column V_NNB_JYQK.SFCBJYGL is '';
comment on column V_NNB_JYQK.CBBQYDCBQYMC is '';
comment on column V_NNB_JYQK.QJCZYY is '';
comment on column V_NNB_JYQK.GYZCCZE is '';
comment on column V_NNB_JYQK.KS is '';

drop table v_nnb_wzxx;
create table v_nnb_wzxx(
  NBXH VARCHAR2 (100),
  ND VARCHAR2 (100),
  SEQ VARCHAR2 (100),
  WEBSITNAME VARCHAR2 (100),
  DOMAIN VARCHAR2 (100),
  WEBTYPE VARCHAR2 (100),
  SFWSLZ VARCHAR2 (100)
);
comment on table v_nnb_wzxx is '年报_网址网店';
comment on column V_NNB_WZXX.NBXH is '内部序号';
comment on column V_NNB_WZXX.ND is '年报年度';
comment on column V_NNB_WZXX.SEQ is '';
comment on column V_NNB_WZXX.WEBSITNAME is '网址名称';
comment on column V_NNB_WZXX.DOMAIN is '网址';
comment on column V_NNB_WZXX.WEBTYPE is '网站类型';
comment on column V_NNB_WZXX.SFWSLZ is '';

drop table bm_qylx;
create table bm_qylx(
  code VARCHAR2 (100),content VARCHAR2 (100),qylxdl VARCHAR2 (100)
);
comment on table bm_qylx is '企业类型';
comment on column bm_qylx.code is '编码';
comment on column bm_qylx.content is '企业类型';
comment on column bm_qylx.qylxdl is '企业类型大类';

drop table v_xt_user;
create table v_xt_user(
  user_name VARCHAR2 (100),full_name VARCHAR2 (100),gh VARCHAR2 (100),gxdwdm VARCHAR2 (100),djjg VARCHAR2 (100),zfzh VARCHAR2 (100)
);
comment on table v_xt_user is '执法人员名单';
comment on column v_xt_user.user_name is '用户代码';
comment on column v_xt_user.full_name is '姓名';
comment on column v_xt_user.gh is '工号';
comment on column v_xt_user.gxdwdm is '管辖单位代码';
comment on column v_xt_user.djjg is '登记机关';
comment on column v_xt_user.zfzh is '执法证号';

/**
导入数据之后，生成测试数据
 */
INSERT INTO SXGS.HZ_DWTZ
(PRIPID,XH,INTENTNAME,REGNO,DZ,TZFS,CONTOAM,POSPROP,KG)
  SELECT  NBXH PRIPID, TRUNC(UEXT_RANDOM.VALUE(1,2)) XH, UEXT_RANDOM.STRING('A',100) INTENTNAME, UEXT_RANDOM.STRING('P',32) REGNO,
          UEXT_RANDOM.STRING('P',80) DZ, UEXT_RANDOM.STRING('P',10) TZFS, UEXT_RANDOM.VALUE(1,10) CONTOAM, UEXT_RANDOM.VALUE(1,10) POSPROP, UEXT_RANDOM.STRING('P',1) KG
  FROM ZTJG.GOV_NBCC_JH_QY WHERE JHXH=255 and NBXH not in(select pripid from SXGS.HZ_DWTZ);
INSERT INTO SXGS.HZ_FGDJ
(PRIPID,XH,DZZJZ,DZZZJFS,DYRS,BNZJBZ,FRDYBZ,FRDZZSJBZ,CJSJ,ZJSJ,QYLX,DJZDYBZ,BNXZDYRS,DJQKYHS,DJHSSJ)
  SELECT  NBXH PRIPID, UEXT_RANDOM.VALUE(1,10) XH, TRUNC(UEXT_RANDOM.VALUE(1,3)) DZZJZ, TRUNC(UEXT_RANDOM.VALUE(1,3)) DZZZJFS,
          TRUNC(UEXT_RANDOM.VALUE(1,10)) DYRS, TRUNC(UEXT_RANDOM.VALUE(1,3)) BNZJBZ, TRUNC(UEXT_RANDOM.VALUE(1,3)) FRDYBZ, TRUNC(UEXT_RANDOM.VALUE(1,3)) FRDZZSJBZ, UEXT_RANDOM.RANDOM_DATE(900) CJSJ,
          UEXT_RANDOM.RANDOM_DATE(900) ZJSJ, UEXT_RANDOM.STRING('P',10) QYLX, TRUNC(UEXT_RANDOM.VALUE(1,3)) DJZDYBZ, TRUNC(UEXT_RANDOM.VALUE(1,10)) BNXZDYRS, TRUNC(UEXT_RANDOM.VALUE(1,3)) DJQKYHS,
          UEXT_RANDOM.RANDOM_DATE(900) DJHSSJ
  FROM ZTJG.GOV_NBCC_JH_QY WHERE JHXH=255 and NBXH not in(select pripid from SXGS.HZ_FGDJ);
INSERT INTO SXGS.HZ_QYHZNR
(PRIPID,ENTNAME,GRPSHFORM,DOM,OPLOC,POSTALCODE,TEL,CZ,EMAIL,LEREP,SFZJHM,ENTTYPE,QYLXDL,INDUSTRYPHY,EMPNUM,REGCAP,REGCAPUSD,ZJLY,CURRENCY,HL,OPSCOPE,PTBUSSCOPE,OPFORM,JYCSMJ,
 TSLXBS,JTBZ,DAWZ,PCOMNAME,CALCULATIONMETHOD,REGNO,ZZFBS,HZRQ,HZJG,HZTZSWH,ESTDATE,REGORG,SANDATE,PZWH,EXAAUTH,SWDJZH,DWDJZH,YZJG,OPFROM,OPTO,ZZYXQXQSRQ,ZZYXQXJZRQ,ZZFBYXQXZ,
 DAH,ZYKHYH,ZYKHYHZH,DEPINCHA,LOCALADM,DW1,DW2,MJ,QYTYDM,BZSM,GBDQ,OPSTATE,SJNBXH,SXDBGJ,WJFZRYS,GATRYS,ZFRYS,DJGLYWLX,JDDW,JDDWDH,PZJGDSZXM,PZJGFDSZXM,PZJGZJLXM,PZJGTJZJMC,
 PZJGDZ,PCOMREGNO,CONGRO,TZZESFCZ,FORREGCAP,FORREGCAPUSD,DOMEREGCAP,DOMEREGCAPUSD,CONGROUSD,RECCAP,RECCAPUSD,WFCYRS,CZDJZH,HGZCDJH,WHDJZH,FOROPSCOPE,XMZE,XMZEMY,XMNR,XMMC,
 GWZCZB,HTQXQ,HTQXZ,JSRYS,GLRYS,SCYWRYS,LIMPARNUM,FORDOM,TOWN,KYLB,GPSSGGRS,PARNUM,EXENUM,ORIREGNO,QYMC_OLD,SCONFORM,BGZXRQ,LDZJ,GDZJ,DOMPRORIGHT,GLPH,XZJD,TSDM1,TSDM2,TSDM3,
 JTCYS,BGXTS,JFKH,ZYSB,COMPFORM,JYXS,ZZSX,JWH,GSWZ,CREDLEVEL,BLXY,JGSD,JGSDDJJG,FPBZ,THLY,DZZZFFZT,SLTZSWH,FORCAPINDCODE,ECOTECDEVZONE,DOMDISTRICT,PROTYPE,ABUITEMCO,INSFORM,
 OPEACTTYPE,HYPOTAXIS,CBUITEM,FORREGECAP,PARFORM,HIGHINDUSTRY,YWFW,GXSYRS,HYFL,NZSY,MIDPREINDCODE,ZJZZ,TSJYLB,BGDXRQ,FORRECCAP,FORRECCAPUSD,DOMERECCAP,DOMERECCAPUSD,ZRR,GLWG,
 XCZ,JYQK,PZJGWWMC,PZJGZRXS,GJJDJJG,CONFORM,ZZDYSX,DZLX,SWDJZ,ZZJGDMZ,SWDJZCJSJ,ZZJGDMZCJSJ,DSDJZ,DSDJZCJSJ,INDUSTRYCO,FXDJ,TDJYQY,ZZXX,WZ,FAX,DOMEREGCAPCUR,FORREGCAPCUR,
 DOMERECCAPCUR,FORRECCAPCUR,ZFRJCZEMYBL,FORREGCAPINVPROP,DOMERECCAPCONPROP,FORRECCAPCONPROP,ZB,REGCAPRMB,RECCAPRMB,DOMEREGCAPINVPROP,ITEMOFOPORCPRO,CONOFCONTRPRO,GXJG,GQBGLX,
 GQFE,HBCZE,TZZRS,NAME_ID,WPDB,BBTZZ,KYWFRJCZE,UNISCID,YIEDISTRICT,PROLOC,DOM_PROVINCE,DOM_CITY,DOM_DISTRICT,DOM_LOCATION,PROLOC_PROVINCE,PROLOC_CITY,PROLOC_DISTRICT,
 PROLOC_LOCATION,JTUNISCID)
  SELECT  NBXH PRIPID, UEXT_RANDOM.STRING('P',100) ENTNAME, UEXT_RANDOM.STRING('P',100) GRPSHFORM, UEXT_RANDOM.STRING('P',200) DOM,
          UEXT_RANDOM.STRING('P',200) OPLOC, UEXT_RANDOM.STRING('P',6) POSTALCODE, UEXT_RANDOM.STRING('P',50) TEL, UEXT_RANDOM.STRING('P',20) CZ, UEXT_RANDOM.STRING('P',40) EMAIL,
          UEXT_RANDOM.STRING('P',200) LEREP, UEXT_RANDOM.STRING('P',40) SFZJHM, UEXT_RANDOM.STRING('P',10) ENTTYPE, UEXT_RANDOM.STRING('P',10) QYLXDL, UEXT_RANDOM.STRING('P',6) INDUSTRYPHY,
          UEXT_RANDOM.VALUE(1,10) EMPNUM, UEXT_RANDOM.VALUE(1,10) REGCAP, UEXT_RANDOM.VALUE(1,10) REGCAPUSD, UEXT_RANDOM.STRING('P',500) ZJLY, UEXT_RANDOM.STRING('P',10) CURRENCY,
          UEXT_RANDOM.VALUE(1,10) HL, UEXT_RANDOM.STRING('P',2100) OPSCOPE, UEXT_RANDOM.STRING('P',1000) PTBUSSCOPE, UEXT_RANDOM.STRING('P',4000) OPFORM, UEXT_RANDOM.VALUE(1,10) JYCSMJ,
          UEXT_RANDOM.STRING('P',20) TSLXBS, UEXT_RANDOM.STRING('P',10) JTBZ, UEXT_RANDOM.STRING('P',20) DAWZ, UEXT_RANDOM.STRING('P',100) PCOMNAME,
          UEXT_RANDOM.STRING('P',10) CALCULATIONMETHOD, UEXT_RANDOM.STRING('P',26) REGNO, UEXT_RANDOM.VALUE(1,10) ZZFBS, UEXT_RANDOM.RANDOM_DATE(900) HZRQ, UEXT_RANDOM.STRING('P',10) HZJG,
          UEXT_RANDOM.STRING('P',40) HZTZSWH, UEXT_RANDOM.RANDOM_DATE(900) ESTDATE, UEXT_RANDOM.STRING('P',10) REGORG, UEXT_RANDOM.RANDOM_DATE(900) SANDATE, UEXT_RANDOM.STRING('P',100) PZWH,
          UEXT_RANDOM.STRING('P',100) EXAAUTH, UEXT_RANDOM.STRING('P',40) SWDJZH, UEXT_RANDOM.STRING('P',40) DWDJZH, UEXT_RANDOM.STRING('P',100) YZJG, UEXT_RANDOM.RANDOM_DATE(900) OPFROM,
          UEXT_RANDOM.RANDOM_DATE(900) OPTO, UEXT_RANDOM.RANDOM_DATE(900) ZZYXQXQSRQ, UEXT_RANDOM.RANDOM_DATE(900) ZZYXQXJZRQ, UEXT_RANDOM.RANDOM_DATE(900) ZZFBYXQXZ,
          UEXT_RANDOM.STRING('P',20) DAH, UEXT_RANDOM.STRING('P',100) ZYKHYH, UEXT_RANDOM.STRING('P',40) ZYKHYHZH, UEXT_RANDOM.STRING('P',100) DEPINCHA, UEXT_RANDOM.STRING('P',10) LOCALADM,
          UEXT_RANDOM.STRING('P',10) DW1, UEXT_RANDOM.STRING('P',10) DW2, UEXT_RANDOM.STRING('P',10) MJ, UEXT_RANDOM.STRING('P',26) QYTYDM, UEXT_RANDOM.STRING('P',1000) BZSM,
          UEXT_RANDOM.STRING('P',10) GBDQ, UEXT_RANDOM.STRING('P',2) OPSTATE, UEXT_RANDOM.STRING('P',32) SJNBXH, UEXT_RANDOM.STRING('P',10) SXDBGJ, UEXT_RANDOM.VALUE(1,10) WJFZRYS,
          UEXT_RANDOM.VALUE(1,10) GATRYS, UEXT_RANDOM.VALUE(1,10) ZFRYS, UEXT_RANDOM.STRING('P',10) DJGLYWLX, UEXT_RANDOM.STRING('P',100) JDDW, UEXT_RANDOM.STRING('P',20) JDDWDH,
          UEXT_RANDOM.STRING('P',80) PZJGDSZXM, UEXT_RANDOM.STRING('P',80) PZJGFDSZXM, UEXT_RANDOM.STRING('P',80) PZJGZJLXM, UEXT_RANDOM.STRING('P',100) PZJGTJZJMC,
          UEXT_RANDOM.STRING('P',100) PZJGDZ, UEXT_RANDOM.STRING('P',100) PCOMREGNO, UEXT_RANDOM.VALUE(1,10) CONGRO, UEXT_RANDOM.VALUE(1,2) TZZESFCZ, UEXT_RANDOM.VALUE(1,10) FORREGCAP,
          UEXT_RANDOM.VALUE(1,10) FORREGCAPUSD, UEXT_RANDOM.VALUE(1,10) DOMEREGCAP, UEXT_RANDOM.VALUE(1,10) DOMEREGCAPUSD, UEXT_RANDOM.VALUE(1,10) CONGROUSD, UEXT_RANDOM.VALUE(1,10) RECCAP,
          UEXT_RANDOM.VALUE(1,10) RECCAPUSD, UEXT_RANDOM.VALUE(1,10) WFCYRS, UEXT_RANDOM.STRING('P',40) CZDJZH, UEXT_RANDOM.STRING('P',40) HGZCDJH, UEXT_RANDOM.STRING('P',20) WHDJZH,
          UEXT_RANDOM.STRING('P',500) FOROPSCOPE, UEXT_RANDOM.VALUE(1,10) XMZE, UEXT_RANDOM.VALUE(1,10) XMZEMY, UEXT_RANDOM.STRING('P',500) XMNR, UEXT_RANDOM.STRING('P',80) XMMC,
          UEXT_RANDOM.VALUE(1,10) GWZCZB, UEXT_RANDOM.RANDOM_DATE(900) HTQXQ, UEXT_RANDOM.RANDOM_DATE(900) HTQXZ, UEXT_RANDOM.VALUE(1,10) JSRYS, UEXT_RANDOM.VALUE(1,10) GLRYS,
          UEXT_RANDOM.VALUE(1,10) SCYWRYS, UEXT_RANDOM.VALUE(1,10) LIMPARNUM, UEXT_RANDOM.STRING('P',70) FORDOM, UEXT_RANDOM.STRING('P',10) TOWN, UEXT_RANDOM.STRING('P',10) KYLB,
          UEXT_RANDOM.VALUE(1,10) GPSSGGRS, UEXT_RANDOM.VALUE(1,10) PARNUM, UEXT_RANDOM.VALUE(1,10) EXENUM, UEXT_RANDOM.STRING('P',200) ORIREGNO, UEXT_RANDOM.STRING('P',400) QYMC_OLD,
          UEXT_RANDOM.STRING('P',10) SCONFORM, UEXT_RANDOM.RANDOM_DATE(900) BGZXRQ, UEXT_RANDOM.VALUE(1,10) LDZJ, UEXT_RANDOM.VALUE(1,10) GDZJ, UEXT_RANDOM.STRING('P',200) DOMPRORIGHT,
          UEXT_RANDOM.STRING('P',10) GLPH, UEXT_RANDOM.STRING('P',100) XZJD, UEXT_RANDOM.STRING('P',10) TSDM1, UEXT_RANDOM.STRING('P',10) TSDM2, UEXT_RANDOM.STRING('P',200) TSDM3,
          UEXT_RANDOM.VALUE(1,10) JTCYS, UEXT_RANDOM.VALUE(1,10) BGXTS, UEXT_RANDOM.STRING('P',10) JFKH, UEXT_RANDOM.STRING('P',100) ZYSB, UEXT_RANDOM.STRING('P',10) COMPFORM,
          UEXT_RANDOM.STRING('P',10) JYXS, UEXT_RANDOM.STRING('P',10) ZZSX, UEXT_RANDOM.STRING('P',10) JWH, UEXT_RANDOM.STRING('P',100) GSWZ, UEXT_RANDOM.STRING('P',20) CREDLEVEL,
          UEXT_RANDOM.STRING('P',20) BLXY, UEXT_RANDOM.STRING('P',60) JGSD, UEXT_RANDOM.STRING('P',10) JGSDDJJG, TRUNC(UEXT_RANDOM.VALUE(1,3)) FPBZ, UEXT_RANDOM.STRING('P',1000) THLY,
          UEXT_RANDOM.STRING('P',10) DZZZFFZT, UEXT_RANDOM.STRING('P',60) SLTZSWH, UEXT_RANDOM.STRING('P',500) FORCAPINDCODE, UEXT_RANDOM.STRING('P',5) ECOTECDEVZONE,
          UEXT_RANDOM.STRING('P',10) DOMDISTRICT, UEXT_RANDOM.STRING('P',6) PROTYPE, UEXT_RANDOM.STRING('P',2000) ABUITEMCO, UEXT_RANDOM.STRING('P',2) INSFORM,
          UEXT_RANDOM.STRING('P',2) OPEACTTYPE, UEXT_RANDOM.STRING('P',2) HYPOTAXIS, UEXT_RANDOM.STRING('P',2000) CBUITEM, UEXT_RANDOM.VALUE(1,10) FORREGECAP,
          UEXT_RANDOM.STRING('P',4) PARFORM, UEXT_RANDOM.STRING('P',4) HIGHINDUSTRY, UEXT_RANDOM.STRING('P',50) YWFW, UEXT_RANDOM.VALUE(1,10) GXSYRS, UEXT_RANDOM.STRING('P',3) HYFL,
          UEXT_RANDOM.STRING('P',100) NZSY, UEXT_RANDOM.STRING('P',4) MIDPREINDCODE, UEXT_RANDOM.STRING('P',10) ZJZZ, UEXT_RANDOM.STRING('P',500) TSJYLB,
          UEXT_RANDOM.RANDOM_DATE(900) BGDXRQ, UEXT_RANDOM.VALUE(1,10) FORRECCAP, UEXT_RANDOM.VALUE(1,10) FORRECCAPUSD, UEXT_RANDOM.VALUE(1,10) DOMERECCAP,
          UEXT_RANDOM.VALUE(1,10) DOMERECCAPUSD, UEXT_RANDOM.STRING('P',1000) ZRR, UEXT_RANDOM.STRING('P',20) GLWG, UEXT_RANDOM.STRING('P',10) XCZ, UEXT_RANDOM.STRING('P',2) JYQK,
          UEXT_RANDOM.STRING('P',100) PZJGWWMC, TRUNC(UEXT_RANDOM.VALUE(1,3)) PZJGZRXS, UEXT_RANDOM.STRING('P',6) GJJDJJG, UEXT_RANDOM.STRING('P',2) CONFORM,
          UEXT_RANDOM.STRING('P',50) ZZDYSX, UEXT_RANDOM.STRING('P',4) DZLX, UEXT_RANDOM.STRING('P',20) SWDJZ, UEXT_RANDOM.STRING('P',20) ZZJGDMZ, UEXT_RANDOM.RANDOM_DATE(900) SWDJZCJSJ,
          UEXT_RANDOM.RANDOM_DATE(900) ZZJGDMZCJSJ, UEXT_RANDOM.STRING('P',20) DSDJZ, UEXT_RANDOM.RANDOM_DATE(900) DSDJZCJSJ, UEXT_RANDOM.STRING('P',10) INDUSTRYCO,
          UEXT_RANDOM.STRING('P',10) FXDJ, UEXT_RANDOM.STRING('P',10) TDJYQY, UEXT_RANDOM.STRING('P',200) ZZXX, UEXT_RANDOM.STRING('P',100) WZ, UEXT_RANDOM.STRING('P',50) FAX,
          UEXT_RANDOM.STRING('P',10) DOMEREGCAPCUR, UEXT_RANDOM.STRING('P',10) FORREGCAPCUR, UEXT_RANDOM.STRING('P',10) DOMERECCAPCUR, UEXT_RANDOM.STRING('P',10) FORRECCAPCUR,
          UEXT_RANDOM.VALUE(1,10) ZFRJCZEMYBL, UEXT_RANDOM.VALUE(1,10) FORREGCAPINVPROP, UEXT_RANDOM.VALUE(1,10) DOMERECCAPCONPROP, UEXT_RANDOM.VALUE(1,10) FORRECCAPCONPROP,
          UEXT_RANDOM.STRING('P',10) ZB, UEXT_RANDOM.VALUE(1,10) REGCAPRMB, UEXT_RANDOM.VALUE(1,10) RECCAPRMB, UEXT_RANDOM.VALUE(1,10) DOMEREGCAPINVPROP,
          UEXT_RANDOM.STRING('P',1000) ITEMOFOPORCPRO, UEXT_RANDOM.STRING('P',1000) CONOFCONTRPRO, UEXT_RANDOM.STRING('P',8) GXJG, UEXT_RANDOM.STRING('P',10) GQBGLX,
          UEXT_RANDOM.STRING('P',10) GQFE, UEXT_RANDOM.VALUE(1,10) HBCZE, UEXT_RANDOM.VALUE(1,10) TZZRS, UEXT_RANDOM.STRING('P',32) NAME_ID, UEXT_RANDOM.STRING('P',50) WPDB,
          UEXT_RANDOM.STRING('P',100) BBTZZ, UEXT_RANDOM.VALUE(1,10) KYWFRJCZE, UEXT_RANDOM.STRING('P',18) UNISCID, UEXT_RANDOM.STRING('P',6) YIEDISTRICT,
          UEXT_RANDOM.STRING('P',200) PROLOC, UEXT_RANDOM.STRING('P',10) DOM_PROVINCE, UEXT_RANDOM.STRING('P',20) DOM_CITY, UEXT_RANDOM.STRING('P',50) DOM_DISTRICT,
          UEXT_RANDOM.STRING('P',120) DOM_LOCATION, UEXT_RANDOM.STRING('P',10) PROLOC_PROVINCE, UEXT_RANDOM.STRING('P',20) PROLOC_CITY, UEXT_RANDOM.STRING('P',50) PROLOC_DISTRICT,
          UEXT_RANDOM.STRING('P',120) PROLOC_LOCATION, UEXT_RANDOM.STRING('P',18) JTUNISCID
  FROM ZTJG.GOV_NBCC_JH_QY WHERE JHXH=255 and NBXH not in(select pripid from SXGS.HZ_QYHZNR);
INSERT INTO SXGS.HZ_QYTZF
(PRIPID,SBXH,TZFLX,INVTYPE,SUBCONAM,SUBCONAMUSD,SUBCONPROP,BZSM,CURRENCY,HL,BYXZRYY,SFYXZR,CONFORM,FHBCZ,ZWBZ,CZQS,BSNBXH,INV,ZCH,GBDQ,DOM,QYLX,FDDBR,JYJZRQ,JYQSRQ,COUNTRY,XB,
 CSNY,CERTYPE,CERNO,MZ,ISWZ,DH,YZBM,EXEAFFSIGN,ZRLX,SZQY,PGFS,CDZRFS,BALDELPER,CONDATE,BLICTYPE,BLICNO,CYLX,ISWD,TZRSSDQ,ZB,ACCONAM,UNISCID)
  SELECT  NBXH PRIPID, UEXT_RANDOM.VALUE(1,10) SBXH, UEXT_RANDOM.STRING('P',10) TZFLX, UEXT_RANDOM.STRING('P',10) INVTYPE, UEXT_RANDOM.VALUE(1,10) SUBCONAM,
          UEXT_RANDOM.VALUE(1,10) SUBCONAMUSD, UEXT_RANDOM.VALUE(1,10) SUBCONPROP, UEXT_RANDOM.STRING('P',500) BZSM, UEXT_RANDOM.STRING('P',10) CURRENCY, UEXT_RANDOM.VALUE(1,10) HL,
          UEXT_RANDOM.STRING('P',500) BYXZRYY, TRUNC(UEXT_RANDOM.VALUE(1,3)) SFYXZR, UEXT_RANDOM.STRING('P',10) CONFORM, UEXT_RANDOM.STRING('P',150) FHBCZ, UEXT_RANDOM.STRING('P',10) ZWBZ,
          UEXT_RANDOM.VALUE(1,10) CZQS, UEXT_RANDOM.STRING('P',32) BSNBXH, UEXT_RANDOM.STRING('P',100) INV, UEXT_RANDOM.STRING('P',26) ZCH, UEXT_RANDOM.STRING('P',10) GBDQ,
          UEXT_RANDOM.STRING('P',100) DOM, UEXT_RANDOM.STRING('P',10) QYLX, UEXT_RANDOM.STRING('P',200) FDDBR, UEXT_RANDOM.RANDOM_DATE(900) JYJZRQ, UEXT_RANDOM.RANDOM_DATE(900) JYQSRQ,
          UEXT_RANDOM.STRING('P',10) COUNTRY, UEXT_RANDOM.STRING('P',10) XB, UEXT_RANDOM.STRING('P',8) CSNY, UEXT_RANDOM.STRING('P',10) CERTYPE, UEXT_RANDOM.STRING('P',40) CERNO,
          UEXT_RANDOM.STRING('P',10) MZ, UEXT_RANDOM.STRING('P',10) ISWZ, UEXT_RANDOM.STRING('P',30) DH, UEXT_RANDOM.STRING('P',6) YZBM, TRUNC(UEXT_RANDOM.VALUE(1,3)) EXEAFFSIGN,
          TRUNC(UEXT_RANDOM.VALUE(1,3)) ZRLX, TRUNC(UEXT_RANDOM.VALUE(1,3)) SZQY, UEXT_RANDOM.STRING('P',100) PGFS, UEXT_RANDOM.STRING('P',100) CDZRFS,
          UEXT_RANDOM.STRING('P',100) BALDELPER, UEXT_RANDOM.RANDOM_DATE(900) CONDATE, UEXT_RANDOM.STRING('P',10) BLICTYPE, UEXT_RANDOM.STRING('P',40) BLICNO,
          UEXT_RANDOM.STRING('P',10) CYLX, TRUNC(UEXT_RANDOM.VALUE(1,3)) ISWD, UEXT_RANDOM.STRING('P',10) TZRSSDQ, UEXT_RANDOM.STRING('P',10) ZB, UEXT_RANDOM.VALUE(1,10) ACCONAM,
          UEXT_RANDOM.STRING('P',18) UNISCID
  FROM ZTJG.GOV_NBCC_JH_QY WHERE JHXH=255 and NBXH not in(select pripid from SXGS.HZ_QYTZF);
INSERT INTO SXNB.NNB_DWDB
(NBXH,ND,XH,MORTGAGOR,GATYPE,RAGE,PEFPERFORM,PEFPERTO,MORE,PRICLASECKIND,PRICLASECAM,GUARANPERIOD,FLAG)
  SELECT  NBXH NBXH, ND ND, UEXT_RANDOM.VALUE(1,10) XH, UEXT_RANDOM.STRING('P',50) MORTGAGOR, TRUNC(UEXT_RANDOM.VALUE(1,3)) GATYPE,
          UEXT_RANDOM.STRING('P',1000) RAGE, UEXT_RANDOM.RANDOM_DATE(900) PEFPERFORM, UEXT_RANDOM.RANDOM_DATE(900) PEFPERTO, UEXT_RANDOM.STRING('P',100) MORE,
          UEXT_RANDOM.STRING('P',2) PRICLASECKIND, UEXT_RANDOM.VALUE(1,10) PRICLASECAM, TRUNC(UEXT_RANDOM.VALUE(1,3)) GUARANPERIOD, TRUNC(UEXT_RANDOM.VALUE(1,3)) FLAG
  FROM ZTJG.GOV_NBCC_JH_QY WHERE JHXH=255 and (NBXH,ND) not in(select NBXH,ND from SXNB.NNB_DWDB);
INSERT INTO SXNB.NNB_FGDJ
(NBXH,ND,XH,PARINS,DZZZJFS,NUMPARM,BNZJBZ,RESPARMSIGN,RESPARSECSIGN,CJSJ,ZJSJ,QYLX,DJZDYBZ,BNXZDYRS)
  SELECT  NBXH, ND, UEXT_RANDOM.VALUE(1,10) XH, TRUNC(UEXT_RANDOM.VALUE(1,3)) PARINS, TRUNC(UEXT_RANDOM.VALUE(1,3)) DZZZJFS,
                    UEXT_RANDOM.VALUE(1,10) NUMPARM, TRUNC(UEXT_RANDOM.VALUE(1,3)) BNZJBZ, TRUNC(UEXT_RANDOM.VALUE(1,3)) RESPARMSIGN, TRUNC(UEXT_RANDOM.VALUE(1,3)) RESPARSECSIGN,
                    UEXT_RANDOM.RANDOM_DATE(900) CJSJ, UEXT_RANDOM.RANDOM_DATE(900) ZJSJ, UEXT_RANDOM.STRING('P',10) QYLX, TRUNC(UEXT_RANDOM.VALUE(1,3)) DJZDYBZ, UEXT_RANDOM.VALUE(1,10) BNXZDYRS
  FROM ZTJG.GOV_NBCC_JH_QY WHERE JHXH=255 and (NBXH,ND) not in(select NBXH,ND from SXNB.NNB_FGDJ);
INSERT INTO SXNB.NNB_FR
(NBXH,ND,SEQ,NAME,ZCH,CZFS,YJCZE,SJCZE,BFB,GJDM,HBCZE,ZSCQCZE,TDSYCZE,QTCZE,SWCZE,ZXHHSW,CZQX,BNDSJCZE,BNDCZXS,YJCZEMY,SJCZEMY,CDZRFS,PGFS,WPDB)
  SELECT  NBXH, ND, UEXT_RANDOM.VALUE(1,10) SEQ, UEXT_RANDOM.STRING('P',100) NAME, UEXT_RANDOM.STRING('P',30) ZCH,
                    UEXT_RANDOM.STRING('P',100) CZFS, UEXT_RANDOM.VALUE(1,10) YJCZE, UEXT_RANDOM.VALUE(1,10) SJCZE, UEXT_RANDOM.VALUE(1,10) BFB, UEXT_RANDOM.STRING('P',10) GJDM,
                    UEXT_RANDOM.VALUE(1,10) HBCZE, UEXT_RANDOM.VALUE(1,10) ZSCQCZE, UEXT_RANDOM.VALUE(1,10) TDSYCZE, UEXT_RANDOM.VALUE(1,10) QTCZE, UEXT_RANDOM.VALUE(1,10) SWCZE,
                    UEXT_RANDOM.STRING('P',40) ZXHHSW, UEXT_RANDOM.RANDOM_DATE(900) CZQX, UEXT_RANDOM.VALUE(1,10) BNDSJCZE, UEXT_RANDOM.STRING('P',10) BNDCZXS, UEXT_RANDOM.VALUE(1,10) YJCZEMY,
                    UEXT_RANDOM.VALUE(1,10) SJCZEMY, UEXT_RANDOM.STRING('P',10) CDZRFS, UEXT_RANDOM.STRING('P',10) PGFS, UEXT_RANDOM.STRING('P',50) WPDB
  FROM ZTJG.GOV_NBCC_JH_QY WHERE JHXH=255 and (NBXH,ND) not in(select NBXH,ND from SXNB.NNB_FR);
INSERT INTO SXNB.NNB_FRCZQK
(NBXH,ND,SEQ,XH,CZLX,CZE,CZFS,CZRQ)
  SELECT * FROM
    (SELECT  A.NBXH, A.ND, B.SEQ SEQ, UEXT_RANDOM.VALUE(1,10) XH, '1' CZLX,
                           UEXT_RANDOM.VALUE(1,10) CZE, UEXT_RANDOM.STRING('P',100) CZFS, UEXT_RANDOM.RANDOM_DATE(900) CZRQ
     FROM ZTJG.GOV_NBCC_JH_QY A,SXNB.NNB_FR B
     WHERE A.JHXH=255 AND A.NBXH=B.NBXH AND A.ND=B.ND)
  WHERE (NBXH,ND,SEQ) NOT IN(SELECT NBXH,ND,SEQ FROM SXNB.NNB_FRCZQK);
INSERT INTO SXNB.NNB_FRCZQK
(NBXH,ND,SEQ,XH,CZLX,CZE,CZFS,CZRQ)
  SELECT * FROM
    (SELECT  A.NBXH, A.ND, B.SEQ SEQ, UEXT_RANDOM.VALUE(1,10) XH, '2' CZLX,
                           UEXT_RANDOM.VALUE(1,10) CZE, UEXT_RANDOM.STRING('P',100) CZFS, UEXT_RANDOM.RANDOM_DATE(900) CZRQ
     FROM ZTJG.GOV_NBCC_JH_QY A,SXNB.NNB_FR B
     WHERE A.JHXH=255 AND A.NBXH=B.NBXH AND A.ND=B.ND)
  WHERE (NBXH,ND,SEQ) NOT IN(SELECT NBXH,ND,SEQ FROM SXNB.NNB_FRCZQK);

INSERT INTO SXNB.NNB_GQBG
(NBXH,ND,XH,INV,ALTDATE,TRANSAMPR,TRANSAMOR)
  SELECT  UEXT_RANDOM.STRING('P',32) NBXH, UEXT_RANDOM.VALUE(1,10) ND, UEXT_RANDOM.VALUE(1,10) XH, UEXT_RANDOM.STRING('P',100) INV, UEXT_RANDOM.RANDOM_DATE(900) ALTDATE,
          UEXT_RANDOM.VALUE(1,10) TRANSAMPR, UEXT_RANDOM.VALUE(1,10) TRANSAMOR
  FROM ZTJG.GOV_NBCC_JH_QY WHERE JHXH=255 and (NBXH,ND) not in(select NBXH,ND from SXNB.NNB_GQBG);
INSERT INTO SXNB.NNB_JBQK
(NBXH,ND,ZS,FDDBR,YQMC,YYQX_QS,YYQX_JZ,ZCZJ,QYLX,JYFS_JYFW,JYCS,SSZB,JYFW,JYFS,CYRS,CZFS,QZXK,YBJY,JYLB,SSHY,CLRQ,BELONG_EPNAME,BELONG_EPZCH,BELONG_EPZS,JYFWDJXKZ,JYFWDJXKZNR,
 JYFWQZXKXM,JYFWQZXKXMNR,JYFWYBDJXM,JYFWYBDJXMNR,GDXMSFBG,GDAQJCZE,ZCSFXG,ZCSFBA,ZCSJQK,DSSFBD,DSSFBA,DSSJQK,JSSFBD,JSSFBA,JSSJQK,JLSFBD,JLSFBA,JLSJQK,SFYFGS,FGSSFBD,FGSSFBA,
 FGSSJQK,SFQS,QSZSFBD,QSZSFBA,QSZSJQK,JYXMQZXZXK,QZXZXKSFYX,GDSFBD,GDSFBA,GDSJQK,DSJSSFBG,DSJSSFBA,DSJSSJQK,ZGBMSFBG,ZGBMSFBA,ZGBMSJQK,TZZEMY,ZCZBMY,ZFRJMY,WFRJMY,SSZBMY,ZFSJMY,
 WFSJMY,WQSFCX,WQCXQX,ZXSWHHRSFBD,ZXSWHHRSFBA,HHRSFBD,HHRSFBA,HHRCZSFBD,HHRCZSFBA,GBDQ,FQR,YYZK,ZYYWXM,BZSM,ZCXS,YWFW,REGNO,LSQY)
  SELECT NBXH, ND, UEXT_RANDOM.STRING('P',100) ZS, UEXT_RANDOM.STRING('P',80) FDDBR, UEXT_RANDOM.STRING('P',100) YQMC,
                   UEXT_RANDOM.RANDOM_DATE(900) YYQX_QS, UEXT_RANDOM.RANDOM_DATE(900) YYQX_JZ, UEXT_RANDOM.VALUE(1,10) ZCZJ, UEXT_RANDOM.STRING('P',10) QYLX, UEXT_RANDOM.STRING('P',2000) JYFS_JYFW,
                   UEXT_RANDOM.STRING('P',100) JYCS, UEXT_RANDOM.VALUE(1,10) SSZB, UEXT_RANDOM.STRING('P',2000) JYFW, UEXT_RANDOM.STRING('P',1000) JYFS, UEXT_RANDOM.VALUE(1,10) CYRS,
                   UEXT_RANDOM.STRING('P',100) CZFS, UEXT_RANDOM.STRING('P',2000) QZXK, UEXT_RANDOM.STRING('P',2000) YBJY, UEXT_RANDOM.STRING('P',4) JYLB, UEXT_RANDOM.STRING('P',10) SSHY,
                   UEXT_RANDOM.RANDOM_DATE(900) CLRQ, UEXT_RANDOM.STRING('P',120) BELONG_EPNAME, UEXT_RANDOM.STRING('P',60) BELONG_EPZCH, UEXT_RANDOM.STRING('P',100) BELONG_EPZS,
                   TRUNC(UEXT_RANDOM.VALUE(1,3)) JYFWDJXKZ, UEXT_RANDOM.STRING('P',1000) JYFWDJXKZNR, TRUNC(UEXT_RANDOM.VALUE(1,3)) JYFWQZXKXM, UEXT_RANDOM.STRING('P',1000) JYFWQZXKXMNR,
                   TRUNC(UEXT_RANDOM.VALUE(1,3)) JYFWYBDJXM, UEXT_RANDOM.STRING('P',1000) JYFWYBDJXMNR, TRUNC(UEXT_RANDOM.VALUE(1,3)) GDXMSFBG, TRUNC(UEXT_RANDOM.VALUE(1,3)) GDAQJCZE,
                   TRUNC(UEXT_RANDOM.VALUE(1,3)) ZCSFXG, TRUNC(UEXT_RANDOM.VALUE(1,3)) ZCSFBA, UEXT_RANDOM.STRING('P',1000) ZCSJQK, TRUNC(UEXT_RANDOM.VALUE(1,3)) DSSFBD,
                   TRUNC(UEXT_RANDOM.VALUE(1,3)) DSSFBA, UEXT_RANDOM.STRING('P',1000) DSSJQK, TRUNC(UEXT_RANDOM.VALUE(1,3)) JSSFBD, TRUNC(UEXT_RANDOM.VALUE(1,3)) JSSFBA,
                   UEXT_RANDOM.STRING('P',1000) JSSJQK, TRUNC(UEXT_RANDOM.VALUE(1,3)) JLSFBD, TRUNC(UEXT_RANDOM.VALUE(1,3)) JLSFBA, UEXT_RANDOM.STRING('P',1000) JLSJQK,
                   TRUNC(UEXT_RANDOM.VALUE(1,3)) SFYFGS, TRUNC(UEXT_RANDOM.VALUE(1,3)) FGSSFBD, TRUNC(UEXT_RANDOM.VALUE(1,3)) FGSSFBA, UEXT_RANDOM.STRING('P',1000) FGSSJQK,
                   TRUNC(UEXT_RANDOM.VALUE(1,3)) SFQS, TRUNC(UEXT_RANDOM.VALUE(1,3)) QSZSFBD, TRUNC(UEXT_RANDOM.VALUE(1,3)) QSZSFBA, UEXT_RANDOM.STRING('P',1000) QSZSJQK,
                   TRUNC(UEXT_RANDOM.VALUE(1,3)) JYXMQZXZXK, TRUNC(UEXT_RANDOM.VALUE(1,3)) QZXZXKSFYX, TRUNC(UEXT_RANDOM.VALUE(1,3)) GDSFBD, TRUNC(UEXT_RANDOM.VALUE(1,3)) GDSFBA,
                   UEXT_RANDOM.STRING('P',1000) GDSJQK, TRUNC(UEXT_RANDOM.VALUE(1,3)) DSJSSFBG, TRUNC(UEXT_RANDOM.VALUE(1,3)) DSJSSFBA, UEXT_RANDOM.STRING('P',1000) DSJSSJQK,
                   TRUNC(UEXT_RANDOM.VALUE(1,3)) ZGBMSFBG, TRUNC(UEXT_RANDOM.VALUE(1,3)) ZGBMSFBA, UEXT_RANDOM.STRING('P',1000) ZGBMSJQK, UEXT_RANDOM.VALUE(1,10) TZZEMY,
                   UEXT_RANDOM.VALUE(1,10) ZCZBMY, UEXT_RANDOM.VALUE(1,10) ZFRJMY, UEXT_RANDOM.VALUE(1,10) WFRJMY, UEXT_RANDOM.VALUE(1,10) SSZBMY, UEXT_RANDOM.VALUE(1,10) ZFSJMY,
                   UEXT_RANDOM.VALUE(1,10) WFSJMY, TRUNC(UEXT_RANDOM.VALUE(1,3)) WQSFCX, UEXT_RANDOM.RANDOM_DATE(900) WQCXQX, TRUNC(UEXT_RANDOM.VALUE(1,3)) ZXSWHHRSFBD,
                   TRUNC(UEXT_RANDOM.VALUE(1,3)) ZXSWHHRSFBA, TRUNC(UEXT_RANDOM.VALUE(1,3)) HHRSFBD, TRUNC(UEXT_RANDOM.VALUE(1,3)) HHRSFBA, TRUNC(UEXT_RANDOM.VALUE(1,3)) HHRCZSFBD,
                   TRUNC(UEXT_RANDOM.VALUE(1,3)) HHRCZSFBA, UEXT_RANDOM.STRING('P',10) GBDQ, UEXT_RANDOM.STRING('P',2000) FQR, TRUNC(UEXT_RANDOM.VALUE(1,3)) YYZK,
                   UEXT_RANDOM.STRING('P',3000) ZYYWXM, UEXT_RANDOM.STRING('P',3000) BZSM, UEXT_RANDOM.STRING('P',50) ZCXS, UEXT_RANDOM.STRING('P',100) YWFW, UEXT_RANDOM.STRING('P',26) REGNO,
                   UEXT_RANDOM.STRING('P',100) LSQY
  FROM ZTJG.GOV_NBCC_JH_QY WHERE JHXH=255 and (NBXH,ND) not in(select NBXH,ND from SXNB.NNB_JBQK);
INSERT INTO SXNB.NNB_QTXX
(NBXH,ND,CYRS,XZCYRS,TCCYRS,COLEMPLNUM,RETEMPLNUM,DISEMPLNUM,UNEEMPLNUM,HZSDJ,NCPRZQK,QTRZQK,BZ,SFYWZWD,SFYDWTZ,JYZDYBZ,JYZDSJBZ,DYRS,FARNUM,
 COLGRANUM,RETSOLNUM,DISPERNUM,UNENUM,SFFSGQBG)
  SELECT  NBXH, ND, TRUNC(UEXT_RANDOM.VALUE(1,10)) CYRS, TRUNC(UEXT_RANDOM.VALUE(1,10)) XZCYRS, TRUNC(UEXT_RANDOM.VALUE(1,10)) TCCYRS,
                    TRUNC(UEXT_RANDOM.VALUE(1,10)) COLEMPLNUM, TRUNC(UEXT_RANDOM.VALUE(1,10)) RETEMPLNUM, TRUNC(UEXT_RANDOM.VALUE(1,10)) DISEMPLNUM, TRUNC(UEXT_RANDOM.VALUE(1,10)) UNEEMPLNUM,
                    UEXT_RANDOM.STRING('P',10) HZSDJ, UEXT_RANDOM.STRING('P',100) NCPRZQK, UEXT_RANDOM.STRING('P',200) QTRZQK, UEXT_RANDOM.STRING('P',1000) BZ, UEXT_RANDOM.STRING('P',2) SFYWZWD,
                    UEXT_RANDOM.STRING('P',2) SFYDWTZ, UEXT_RANDOM.STRING('P',2) JYZDYBZ, UEXT_RANDOM.STRING('P',2) JYZDSJBZ, TRUNC(UEXT_RANDOM.VALUE(1,10)) DYRS,
                    TRUNC(UEXT_RANDOM.VALUE(1,10)) FARNUM, TRUNC(UEXT_RANDOM.VALUE(1,10)) COLGRANUM, TRUNC(UEXT_RANDOM.VALUE(1,10)) RETSOLNUM, TRUNC(UEXT_RANDOM.VALUE(1,10)) DISPERNUM,
                    TRUNC(UEXT_RANDOM.VALUE(1,10)) UNENUM, UEXT_RANDOM.STRING('P',2) SFFSGQBG
  FROM ZTJG.GOV_NBCC_JH_QY WHERE JHXH=255 and (NBXH,ND) not in(select NBXH,ND from SXNB.NNB_QTXX);
INSERT INTO SXNB.NNB_TXXX
(NBXH,ND,TXDZ,YZBM,DZYX,LXDH,GSLLYXM,GSLLYDH,JNJSRMC,JNJSRDZ,JNJSRYZBM,JNJSRLXR,JNJSRGDDH,JNJSRYDDH,JNJSRDZYX)
  SELECT  NBXH, ND, UEXT_RANDOM.STRING('P',200) TXDZ, UEXT_RANDOM.STRING('P',10) YZBM, UEXT_RANDOM.STRING('P',100) DZYX,
                    UEXT_RANDOM.STRING('P',40) LXDH, UEXT_RANDOM.STRING('P',100) GSLLYXM, UEXT_RANDOM.STRING('P',40) GSLLYDH, UEXT_RANDOM.STRING('P',100) JNJSRMC,
                    UEXT_RANDOM.STRING('P',200) JNJSRDZ, UEXT_RANDOM.STRING('P',10) JNJSRYZBM, UEXT_RANDOM.STRING('P',100) JNJSRLXR, UEXT_RANDOM.STRING('P',40) JNJSRGDDH,
                    UEXT_RANDOM.STRING('P',40) JNJSRYDDH, UEXT_RANDOM.STRING('P',100) JNJSRDZYX
  FROM ZTJG.GOV_NBCC_JH_QY WHERE JHXH=255 and (NBXH,ND) not in(select NBXH,ND from SXNB.NNB_TXXX);
INSERT INTO SXNB.NNB_TZ
(NBXH,ND,SEQ,ENTNAME,DZ,TZFS,TZJE,TZBL,REGNO,DJJG,SFKG,SJJE)
  SELECT NBXH, ND, UEXT_RANDOM.VALUE(1,10) SEQ, UEXT_RANDOM.STRING('P',100) ENTNAME, UEXT_RANDOM.STRING('P',80) DZ,
                   UEXT_RANDOM.STRING('P',100) TZFS, UEXT_RANDOM.VALUE(1,10) TZJE, UEXT_RANDOM.VALUE(1,10) TZBL, UEXT_RANDOM.STRING('P',100) REGNO, UEXT_RANDOM.STRING('P',100) DJJG,
                   TRUNC(UEXT_RANDOM.VALUE(1,3)) SFKG, UEXT_RANDOM.VALUE(1,10) SJJE
  FROM ZTJG.GOV_NBCC_JH_QY WHERE JHXH=255 and (NBXH,ND) not in(select NBXH,ND from SXNB.NNB_TZ);
INSERT INTO SXNB.NNB_WZXX
(NBXH,ND,SEQ,WEBSITNAME,DOMAIN,WEBTYPE,SFWSLZ)
  SELECT NBXH, ND, UEXT_RANDOM.VALUE(1,10) SEQ, UEXT_RANDOM.STRING('P',100) WEBSITNAME, UEXT_RANDOM.STRING('P',100) DOMAIN,
                   UEXT_RANDOM.STRING('P',2) WEBTYPE, TRUNC(UEXT_RANDOM.VALUE(1,3)) SFWSLZ
  FROM ZTJG.GOV_NBCC_JH_QY WHERE JHXH=255 and (NBXH,ND) not in(select NBXH,ND from SXNB.NNB_WZXX);
INSERT INTO SXNB.NNB_ZCZK
(NBXH,ND,QNYYSR,FWYYSR,ZCZE,FZZE,SFGK,CQTZ,CQFZ,LRZE,JLR,KSE,NSZE,SFSJ,SWSMC,LXDH,SJBGBH,SJRQ,CZ,LSE,FCZJ,JRDK,SYZQYHJ,ZYYWSR,FDLHS)
  SELECT  NBXH, ND, UEXT_RANDOM.VALUE(1,10) QNYYSR, UEXT_RANDOM.VALUE(1,10) FWYYSR, UEXT_RANDOM.VALUE(1,10) ZCZE,
                    UEXT_RANDOM.VALUE(1,10) FZZE, TRUNC(UEXT_RANDOM.VALUE(1,3)) SFGK, UEXT_RANDOM.VALUE(1,10) CQTZ, UEXT_RANDOM.VALUE(1,10) CQFZ, UEXT_RANDOM.VALUE(1,10) LRZE,
                    UEXT_RANDOM.VALUE(1,10) JLR, UEXT_RANDOM.VALUE(1,10) KSE, UEXT_RANDOM.VALUE(1,10) NSZE, TRUNC(UEXT_RANDOM.VALUE(1,3)) SFSJ, UEXT_RANDOM.STRING('P',100) SWSMC,
                    UEXT_RANDOM.STRING('P',100) LXDH, UEXT_RANDOM.STRING('P',100) SJBGBH, UEXT_RANDOM.RANDOM_DATE(900) SJRQ, UEXT_RANDOM.VALUE(1,10) CZ, UEXT_RANDOM.VALUE(1,10) LSE,
                    UEXT_RANDOM.VALUE(1,10) FCZJ, UEXT_RANDOM.VALUE(1,10) JRDK, UEXT_RANDOM.VALUE(1,10) SYZQYHJ, UEXT_RANDOM.VALUE(1,10) ZYYWSR, TRUNC(UEXT_RANDOM.VALUE(1,3)) FDLHS
  FROM ZTJG.GOV_NBCC_JH_QY WHERE JHXH=255 and (NBXH,ND) not in(select NBXH,ND from SXNB.NNB_ZCZK);

/**
----问题
1、任务表问题中XCR人员分隔规则需要明确，如果不能确定，只能进行模糊查询。另外能否给出代码，如果按照名称进行匹配会有重名问题。
     任务表问题中XCR字段有610300000000486
     XCR字段与xt_user表中数据对应不上如何处理
2、三个人如何处理
3、管辖单位编码有6、9、10位的
      610100001	城东工商所
      610502002	临渭分局机关
      612428004	牛头店工商所
      610524	西寨街道
      612428005	上竹工商所
      612428006	曙坪工商所
      612428007	华坪工商所
      610526	韦林街道、果园街道
      6127220301	大柳塔管区
      612631011	办公室
      612631010	12315申诉举报中心
      610525	迪村街道
      610527	韦林街道
4、工号重复
    06020	2
    06033	2
    05035	2
5、任务接口表gov_nbcc_jh_qy中增加创建时间字段，根据创建时间进行增量数据获取
6、登记机关中SJCODE字段不正确，目前是进行判断，如果SJCODE=0则付值610000
7、数据完整性不够
8、非公党建数据重复
      6103000000001592	2013	2
      6103010000008353	2013	2
      6127010000001330	2013	2
      612700100002919	2013	2
      6105020000001090	2013	2
      6127262310395	2013	2
      6127322310017	2013	2
      6123006000000074	2013	2
      610403100002257	2013	2
      6100002070429	2013	2
      6104810000007776	2013	2
      610200300001929	2013	2
      6123012700198	2013	2
      610481100000935	2013	2
      6104240000004639	2013	2
      610403100002057	2013	2
      610000200008465	2013	2
      6100002009128	2013	2
      6100000000003302	2013	2
      6100000000070363	2013	2
      610400200000077	2013	2
      6127240000011628	2013	2
      610000100151317	2013	2
      612632100000181	2013	2
      610000100163853	2013	2
      6100000000036335	2013	2
      6126240000030577	2013	2
      6126262300063	2013	2
      610400100027371	2013	2
      6125221200419	2013	2
      610300100008783	2013	2
      6105212010008	2013	2
      6126010000049236	2013	2
      6104031800129	2013	2
      6100000000040276	2013	2
      6100000000070281	2013	2
      610300100004217	2013	2
      6103012060200	2013	2
      612600100006115	2013	2
      6123252100496	2013	2

 */
