--欢迎页
select ID, HCJH_ID, HCDW_XYDM, HCDW_NAME,
ZFRY_CODE1, ZFRY_CODE2, RWZT, HCFL, HCJG, HCJIEGUO, JYZT, HCJGGSQK, RLR, RLRQ, SJWCRQ, ZFRY_NAME1,
ZFRY_NAME2, HCJGMC, DJJGMC, DJJG, ZTLX, ZZXS, QYBM, QYMC, RLRMC, JHWCRQ, ND, JHMC, JHXDRQ,
JHYQWCSJ, DATA_LOADED, NR, ALL_FILES, UPLOAD_FILES, JHBH from T_HCRW where (ZFRY_CODE1 = (select
zfry from sys_user where user_id='b00035') or ZFRY_CODE2 = (select zfry from sys_user where
user_id='b00035')) ORDER BY RLRQ;
--市场主体名录
select 'false' as QUERYID, XYDM, NAME,
ZTLX, HYFL, ZZXS, JYZT, FR, LXDH, MAIL, DJJG, JYDZ, LLR, QYBM, QYMC ,(select count(1) from
t_hcrw b where b.hcdw_xydm=t_sczt.xydm) hcrws from T_SCZT where QYBM IN ( SELECT ID FROM SYS_ORGANIZATION
START WITH ID IN ( SELECT ORG_ID FROM T_USER_ORG WHERE USER_ID='b00035') CONNECT BY PRIOR ID=PARENT_ID
) and exists(select 1 from t_hcrw b where b.hcjg like '6102'||'%' and t_sczt.xydm=b.hcdw_xydm)
ORDER BY NAME;
--核查任务分配
select ID, HCJH_ID, HCDW_XYDM, HCDW_NAME,
ZFRY_CODE1, ZFRY_CODE2, RWZT, HCFL, HCJG, HCJIEGUO, JYZT, HCJGGSQK, RLR, RLRQ, SJWCRQ, ZFRY_NAME1,
ZFRY_NAME2, HCJGMC, DJJGMC, DJJG, ZTLX, ZZXS, QYBM, QYMC, RLRMC, JHWCRQ, ND, JHMC, JHXDRQ,
JHYQWCSJ, DATA_LOADED, NR, ALL_FILES, UPLOAD_FILES, JHBH from T_HCRW where HCJH_ID = '819c38ec88184bbfaea10a164fb61b05'
AND QYBM IN ( SELECT ID FROM SYS_ORGANIZATION START WITH ID IN ( SELECT ORG_ID FROM T_USER_ORG
WHERE USER_ID='e06091') CONNECT BY PRIOR ID=PARENT_ID ) AND HCJG like concat('61', '%') ORDER
BY HCJGMC, ZFRY_NAME1, ZFRY_NAME2;
--计划核查
select ID, HCJH_ID, HCDW_XYDM, HCDW_NAME, ZFRY_CODE1, ZFRY_CODE2, RWZT, HCFL, HCJG, HCJIEGUO,
JYZT, HCJGGSQK, RLR, RLRQ, SJWCRQ, ZFRY_NAME1, ZFRY_NAME2, HCJGMC, DJJGMC, DJJG, ZTLX, ZZXS,
QYBM, QYMC, RLRMC, JHWCRQ, ND, JHMC, JHXDRQ, JHYQWCSJ, DATA_LOADED, NR, ALL_FILES, UPLOAD_FILES,
JHBH from T_HCRW where (ZFRY_CODE1 = (select zfry from sys_user where user_id='e06091') or
ZFRY_CODE2 = (select zfry from sys_user where user_id='e06091')) ORDER BY RLRQ;
