package com.kysoft.cpsi.found.mapper;

import com.kysoft.cpsi.found.entity.UserOrg;
import com.kysoft.cpsi.found.entity.UserOrgKey;

public interface UserOrgMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table T_USER_ORG
	 * @mbggenerated  Tue May 24 19:32:58 CST 2016
	 */
	int deleteByPrimaryKey(UserOrgKey key);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table T_USER_ORG
	 * @mbggenerated  Tue May 24 19:32:58 CST 2016
	 */
	int insert(UserOrg record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table T_USER_ORG
	 * @mbggenerated  Tue May 24 19:32:58 CST 2016
	 */
	int insertSelective(UserOrg record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table T_USER_ORG
	 * @mbggenerated  Tue May 24 19:32:58 CST 2016
	 */
	UserOrg selectByPrimaryKey(UserOrgKey key);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table T_USER_ORG
	 * @mbggenerated  Tue May 24 19:32:58 CST 2016
	 */
	int updateByPrimaryKeySelective(UserOrg record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table T_USER_ORG
	 * @mbggenerated  Tue May 24 19:32:58 CST 2016
	 */
	int updateByPrimaryKey(UserOrg record);
}