package com.kysoft.kteam.plan.mapper;

import java.util.List;

import com.kysoft.kteam.plan.entity.Attachment;

public interface AttachmentMapper {
    /**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table T_ATTACHMENT
	 * @mbggenerated  Tue Dec 01 13:11:53 CST 2015
	 */
	int insert(Attachment record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table T_ATTACHMENT
	 * @mbggenerated  Tue Dec 01 13:11:53 CST 2015
	 */
	int insertSelective(Attachment record);

	List<Attachment> selectByPlanId(String planId);

	void deleteByMongoId(String mongoId);
}