package com.kysoft.cpsi.repo.entity;

public class AuditItemEnterpriseTypeKey {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column T_HCSX_QYLX.ZTLX_ID
	 * @mbg.generated  Wed Sep 21 17:32:50 CST 2016
	 */
	private String ztlxId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column T_HCSX_QYLX.HCSX_ID
	 * @mbg.generated  Wed Sep 21 17:32:50 CST 2016
	 */
	private String hcsxId;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column T_HCSX_QYLX.ZTLX_ID
	 * @return  the value of T_HCSX_QYLX.ZTLX_ID
	 * @mbg.generated  Wed Sep 21 17:32:50 CST 2016
	 */
	public String getZtlxId() {
		return ztlxId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column T_HCSX_QYLX.ZTLX_ID
	 * @param ztlxId  the value for T_HCSX_QYLX.ZTLX_ID
	 * @mbg.generated  Wed Sep 21 17:32:50 CST 2016
	 */
	public void setZtlxId(String ztlxId) {
		this.ztlxId = ztlxId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column T_HCSX_QYLX.HCSX_ID
	 * @return  the value of T_HCSX_QYLX.HCSX_ID
	 * @mbg.generated  Wed Sep 21 17:32:50 CST 2016
	 */
	public String getHcsxId() {
		return hcsxId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column T_HCSX_QYLX.HCSX_ID
	 * @param hcsxId  the value for T_HCSX_QYLX.HCSX_ID
	 * @mbg.generated  Wed Sep 21 17:32:50 CST 2016
	 */
	public void setHcsxId(String hcsxId) {
		this.hcsxId = hcsxId;
	}
}