package com.kysoft.cpsi.repo.entity;

public class Hccl {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_HCCL.ID
     *
     * @mbggenerated Fri May 20 11:20:44 CST 2016
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_HCCL.NAME
     *
     * @mbggenerated Fri May 20 11:20:44 CST 2016
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_HCCL.SFBYX
     *
     * @mbggenerated Fri May 20 11:20:44 CST 2016
     */
    private Integer sfbyx;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_HCCL.WJLX
     *
     * @mbggenerated Fri May 20 11:20:44 CST 2016
     */
    private Integer wjlx;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_HCCL.HCSX_ID
     *
     * @mbggenerated Fri May 20 11:20:44 CST 2016
     */
    private String hcsxId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_HCCL.ID
     *
     * @return the value of T_HCCL.ID
     *
     * @mbggenerated Fri May 20 11:20:44 CST 2016
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_HCCL.ID
     *
     * @param id the value for T_HCCL.ID
     *
     * @mbggenerated Fri May 20 11:20:44 CST 2016
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_HCCL.NAME
     *
     * @return the value of T_HCCL.NAME
     *
     * @mbggenerated Fri May 20 11:20:44 CST 2016
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_HCCL.NAME
     *
     * @param name the value for T_HCCL.NAME
     *
     * @mbggenerated Fri May 20 11:20:44 CST 2016
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_HCCL.SFBYX
     *
     * @return the value of T_HCCL.SFBYX
     *
     * @mbggenerated Fri May 20 11:20:44 CST 2016
     */
    public Integer getSfbyx() {
        return sfbyx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_HCCL.SFBYX
     *
     * @param sfbyx the value for T_HCCL.SFBYX
     *
     * @mbggenerated Fri May 20 11:20:44 CST 2016
     */
    public void setSfbyx(Integer sfbyx) {
        this.sfbyx = sfbyx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_HCCL.WJLX
     *
     * @return the value of T_HCCL.WJLX
     *
     * @mbggenerated Fri May 20 11:20:44 CST 2016
     */
    public Integer getWjlx() {
        return wjlx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_HCCL.WJLX
     *
     * @param wjlx the value for T_HCCL.WJLX
     *
     * @mbggenerated Fri May 20 11:20:44 CST 2016
     */
    public void setWjlx(Integer wjlx) {
        this.wjlx = wjlx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_HCCL.HCSX_ID
     *
     * @return the value of T_HCCL.HCSX_ID
     *
     * @mbggenerated Fri May 20 11:20:44 CST 2016
     */
    public String getHcsxId() {
        return hcsxId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_HCCL.HCSX_ID
     *
     * @param hcsxId the value for T_HCCL.HCSX_ID
     *
     * @mbggenerated Fri May 20 11:20:44 CST 2016
     */
    public void setHcsxId(String hcsxId) {
        this.hcsxId = hcsxId;
    }
}