package com.kysoft.cpsi.repo.entity;

import java.util.Date;

public class Hcsx {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_HCSX.ID
     *
     * @mbggenerated Fri May 20 11:20:44 CST 2016
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_HCSX.NAME
     *
     * @mbggenerated Fri May 20 11:20:44 CST 2016
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_HCSX.TYPE
     *
     * @mbggenerated Fri May 20 11:20:44 CST 2016
     */
    private Integer type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_HCSX.DESCRIPT
     *
     * @mbggenerated Fri May 20 11:20:44 CST 2016
     */
    private String descript;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_HCSX.HCCL
     *
     * @mbggenerated Fri May 20 11:20:44 CST 2016
     */
    private String hccl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_HCSX.HCFF
     *
     * @mbggenerated Fri May 20 11:20:44 CST 2016
     */
    private String hcff;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_HCSX.HCXXFL
     *
     * @mbggenerated Fri May 20 11:20:44 CST 2016
     */
    private Integer hcxxfl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_HCSX.HCLX
     *
     * @mbggenerated Fri May 20 11:20:44 CST 2016
     */
    private Integer hclx;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_HCSX.QYZZXS
     *
     * @mbggenerated Fri May 20 11:20:44 CST 2016
     */
    private Integer qyzzxs;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_HCSX.GSXM
     *
     * @mbggenerated Fri May 20 11:20:44 CST 2016
     */
    private String gsxm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_HCSX.HCFFSM
     *
     * @mbggenerated Fri May 20 11:20:44 CST 2016
     */
    private String hcffsm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_HCSX.JGCL
     *
     * @mbggenerated Fri May 20 11:20:44 CST 2016
     */
    private Integer jgcl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_HCSX.XXDB
     *
     * @mbggenerated Fri May 20 11:20:44 CST 2016
     */
    private String xxdb;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_HCSX.DBXXLY
     *
     * @mbggenerated Fri May 20 11:20:44 CST 2016
     */
    private String dbxxly;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_HCSX.SFXYSDHC
     *
     * @mbggenerated Fri May 20 11:20:44 CST 2016
     */
    private Integer sfxysdhc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_HCSX.SFXYRGHD
     *
     * @mbggenerated Fri May 20 11:20:44 CST 2016
     */
    private Integer sfxyrghd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_HCSX.GZQX
     *
     * @mbggenerated Fri May 20 11:20:44 CST 2016
     */
    private String gzqx;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_HCSX.SFBJXM
     *
     * @mbggenerated Fri May 20 11:20:44 CST 2016
     */
    private Integer sfbjxm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_HCSX.ZXRQ
     *
     * @mbggenerated Fri May 20 11:20:44 CST 2016
     */
    private Date zxrq;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_HCSX.ZXSM
     *
     * @mbggenerated Fri May 20 11:20:44 CST 2016
     */
    private String zxsm;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_HCSX.ID
     *
     * @return the value of T_HCSX.ID
     *
     * @mbggenerated Fri May 20 11:20:44 CST 2016
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_HCSX.ID
     *
     * @param id the value for T_HCSX.ID
     *
     * @mbggenerated Fri May 20 11:20:44 CST 2016
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_HCSX.NAME
     *
     * @return the value of T_HCSX.NAME
     *
     * @mbggenerated Fri May 20 11:20:44 CST 2016
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_HCSX.NAME
     *
     * @param name the value for T_HCSX.NAME
     *
     * @mbggenerated Fri May 20 11:20:44 CST 2016
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_HCSX.TYPE
     *
     * @return the value of T_HCSX.TYPE
     *
     * @mbggenerated Fri May 20 11:20:44 CST 2016
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_HCSX.TYPE
     *
     * @param type the value for T_HCSX.TYPE
     *
     * @mbggenerated Fri May 20 11:20:44 CST 2016
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_HCSX.DESCRIPT
     *
     * @return the value of T_HCSX.DESCRIPT
     *
     * @mbggenerated Fri May 20 11:20:44 CST 2016
     */
    public String getDescript() {
        return descript;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_HCSX.DESCRIPT
     *
     * @param descript the value for T_HCSX.DESCRIPT
     *
     * @mbggenerated Fri May 20 11:20:44 CST 2016
     */
    public void setDescript(String descript) {
        this.descript = descript;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_HCSX.HCCL
     *
     * @return the value of T_HCSX.HCCL
     *
     * @mbggenerated Fri May 20 11:20:44 CST 2016
     */
    public String getHccl() {
        return hccl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_HCSX.HCCL
     *
     * @param hccl the value for T_HCSX.HCCL
     *
     * @mbggenerated Fri May 20 11:20:44 CST 2016
     */
    public void setHccl(String hccl) {
        this.hccl = hccl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_HCSX.HCFF
     *
     * @return the value of T_HCSX.HCFF
     *
     * @mbggenerated Fri May 20 11:20:44 CST 2016
     */
    public String getHcff() {
        return hcff;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_HCSX.HCFF
     *
     * @param hcff the value for T_HCSX.HCFF
     *
     * @mbggenerated Fri May 20 11:20:44 CST 2016
     */
    public void setHcff(String hcff) {
        this.hcff = hcff;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_HCSX.HCXXFL
     *
     * @return the value of T_HCSX.HCXXFL
     *
     * @mbggenerated Fri May 20 11:20:44 CST 2016
     */
    public Integer getHcxxfl() {
        return hcxxfl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_HCSX.HCXXFL
     *
     * @param hcxxfl the value for T_HCSX.HCXXFL
     *
     * @mbggenerated Fri May 20 11:20:44 CST 2016
     */
    public void setHcxxfl(Integer hcxxfl) {
        this.hcxxfl = hcxxfl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_HCSX.HCLX
     *
     * @return the value of T_HCSX.HCLX
     *
     * @mbggenerated Fri May 20 11:20:44 CST 2016
     */
    public Integer getHclx() {
        return hclx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_HCSX.HCLX
     *
     * @param hclx the value for T_HCSX.HCLX
     *
     * @mbggenerated Fri May 20 11:20:44 CST 2016
     */
    public void setHclx(Integer hclx) {
        this.hclx = hclx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_HCSX.QYZZXS
     *
     * @return the value of T_HCSX.QYZZXS
     *
     * @mbggenerated Fri May 20 11:20:44 CST 2016
     */
    public Integer getQyzzxs() {
        return qyzzxs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_HCSX.QYZZXS
     *
     * @param qyzzxs the value for T_HCSX.QYZZXS
     *
     * @mbggenerated Fri May 20 11:20:44 CST 2016
     */
    public void setQyzzxs(Integer qyzzxs) {
        this.qyzzxs = qyzzxs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_HCSX.GSXM
     *
     * @return the value of T_HCSX.GSXM
     *
     * @mbggenerated Fri May 20 11:20:44 CST 2016
     */
    public String getGsxm() {
        return gsxm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_HCSX.GSXM
     *
     * @param gsxm the value for T_HCSX.GSXM
     *
     * @mbggenerated Fri May 20 11:20:44 CST 2016
     */
    public void setGsxm(String gsxm) {
        this.gsxm = gsxm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_HCSX.HCFFSM
     *
     * @return the value of T_HCSX.HCFFSM
     *
     * @mbggenerated Fri May 20 11:20:44 CST 2016
     */
    public String getHcffsm() {
        return hcffsm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_HCSX.HCFFSM
     *
     * @param hcffsm the value for T_HCSX.HCFFSM
     *
     * @mbggenerated Fri May 20 11:20:44 CST 2016
     */
    public void setHcffsm(String hcffsm) {
        this.hcffsm = hcffsm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_HCSX.JGCL
     *
     * @return the value of T_HCSX.JGCL
     *
     * @mbggenerated Fri May 20 11:20:44 CST 2016
     */
    public Integer getJgcl() {
        return jgcl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_HCSX.JGCL
     *
     * @param jgcl the value for T_HCSX.JGCL
     *
     * @mbggenerated Fri May 20 11:20:44 CST 2016
     */
    public void setJgcl(Integer jgcl) {
        this.jgcl = jgcl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_HCSX.XXDB
     *
     * @return the value of T_HCSX.XXDB
     *
     * @mbggenerated Fri May 20 11:20:44 CST 2016
     */
    public String getXxdb() {
        return xxdb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_HCSX.XXDB
     *
     * @param xxdb the value for T_HCSX.XXDB
     *
     * @mbggenerated Fri May 20 11:20:44 CST 2016
     */
    public void setXxdb(String xxdb) {
        this.xxdb = xxdb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_HCSX.DBXXLY
     *
     * @return the value of T_HCSX.DBXXLY
     *
     * @mbggenerated Fri May 20 11:20:44 CST 2016
     */
    public String getDbxxly() {
        return dbxxly;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_HCSX.DBXXLY
     *
     * @param dbxxly the value for T_HCSX.DBXXLY
     *
     * @mbggenerated Fri May 20 11:20:44 CST 2016
     */
    public void setDbxxly(String dbxxly) {
        this.dbxxly = dbxxly;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_HCSX.SFXYSDHC
     *
     * @return the value of T_HCSX.SFXYSDHC
     *
     * @mbggenerated Fri May 20 11:20:44 CST 2016
     */
    public Integer getSfxysdhc() {
        return sfxysdhc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_HCSX.SFXYSDHC
     *
     * @param sfxysdhc the value for T_HCSX.SFXYSDHC
     *
     * @mbggenerated Fri May 20 11:20:44 CST 2016
     */
    public void setSfxysdhc(Integer sfxysdhc) {
        this.sfxysdhc = sfxysdhc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_HCSX.SFXYRGHD
     *
     * @return the value of T_HCSX.SFXYRGHD
     *
     * @mbggenerated Fri May 20 11:20:44 CST 2016
     */
    public Integer getSfxyrghd() {
        return sfxyrghd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_HCSX.SFXYRGHD
     *
     * @param sfxyrghd the value for T_HCSX.SFXYRGHD
     *
     * @mbggenerated Fri May 20 11:20:44 CST 2016
     */
    public void setSfxyrghd(Integer sfxyrghd) {
        this.sfxyrghd = sfxyrghd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_HCSX.GZQX
     *
     * @return the value of T_HCSX.GZQX
     *
     * @mbggenerated Fri May 20 11:20:44 CST 2016
     */
    public String getGzqx() {
        return gzqx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_HCSX.GZQX
     *
     * @param gzqx the value for T_HCSX.GZQX
     *
     * @mbggenerated Fri May 20 11:20:44 CST 2016
     */
    public void setGzqx(String gzqx) {
        this.gzqx = gzqx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_HCSX.SFBJXM
     *
     * @return the value of T_HCSX.SFBJXM
     *
     * @mbggenerated Fri May 20 11:20:44 CST 2016
     */
    public Integer getSfbjxm() {
        return sfbjxm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_HCSX.SFBJXM
     *
     * @param sfbjxm the value for T_HCSX.SFBJXM
     *
     * @mbggenerated Fri May 20 11:20:44 CST 2016
     */
    public void setSfbjxm(Integer sfbjxm) {
        this.sfbjxm = sfbjxm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_HCSX.ZXRQ
     *
     * @return the value of T_HCSX.ZXRQ
     *
     * @mbggenerated Fri May 20 11:20:44 CST 2016
     */
    public Date getZxrq() {
        return zxrq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_HCSX.ZXRQ
     *
     * @param zxrq the value for T_HCSX.ZXRQ
     *
     * @mbggenerated Fri May 20 11:20:44 CST 2016
     */
    public void setZxrq(Date zxrq) {
        this.zxrq = zxrq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_HCSX.ZXSM
     *
     * @return the value of T_HCSX.ZXSM
     *
     * @mbggenerated Fri May 20 11:20:44 CST 2016
     */
    public String getZxsm() {
        return zxsm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_HCSX.ZXSM
     *
     * @param zxsm the value for T_HCSX.ZXSM
     *
     * @mbggenerated Fri May 20 11:20:44 CST 2016
     */
    public void setZxsm(String zxsm) {
        this.zxsm = zxsm;
    }
}