package com.kysoft.cpsi.repo.entity;

public class Sczt {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SCZT.XYDM
     *
     * @mbggenerated Fri May 20 11:20:44 CST 2016
     */
    private String xydm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SCZT.NAME
     *
     * @mbggenerated Fri May 20 11:20:44 CST 2016
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SCZT.TYPE
     *
     * @mbggenerated Fri May 20 11:20:44 CST 2016
     */
    private Integer type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SCZT.HYFL
     *
     * @mbggenerated Fri May 20 11:20:44 CST 2016
     */
    private Integer hyfl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SCZT.ZZXS
     *
     * @mbggenerated Fri May 20 11:20:44 CST 2016
     */
    private Integer zzxs;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SCZT.JYZT
     *
     * @mbggenerated Fri May 20 11:20:44 CST 2016
     */
    private Integer jyzt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SCZT.FR
     *
     * @mbggenerated Fri May 20 11:20:44 CST 2016
     */
    private String fr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SCZT.LXDH
     *
     * @mbggenerated Fri May 20 11:20:44 CST 2016
     */
    private String lxdh;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SCZT.MAIL
     *
     * @mbggenerated Fri May 20 11:20:44 CST 2016
     */
    private String mail;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SCZT.DJJG
     *
     * @mbggenerated Fri May 20 11:20:44 CST 2016
     */
    private String djjg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SCZT.JYDZ
     *
     * @mbggenerated Fri May 20 11:20:44 CST 2016
     */
    private String jydz;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SCZT.LLR
     *
     * @mbggenerated Fri May 20 11:20:44 CST 2016
     */
    private String llr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SCZT.SZQY
     *
     * @mbggenerated Fri May 20 11:20:44 CST 2016
     */
    private String szqy;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SCZT.XYDM
     *
     * @return the value of T_SCZT.XYDM
     *
     * @mbggenerated Fri May 20 11:20:44 CST 2016
     */
    public String getXydm() {
        return xydm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SCZT.XYDM
     *
     * @param xydm the value for T_SCZT.XYDM
     *
     * @mbggenerated Fri May 20 11:20:44 CST 2016
     */
    public void setXydm(String xydm) {
        this.xydm = xydm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SCZT.NAME
     *
     * @return the value of T_SCZT.NAME
     *
     * @mbggenerated Fri May 20 11:20:44 CST 2016
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SCZT.NAME
     *
     * @param name the value for T_SCZT.NAME
     *
     * @mbggenerated Fri May 20 11:20:44 CST 2016
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SCZT.TYPE
     *
     * @return the value of T_SCZT.TYPE
     *
     * @mbggenerated Fri May 20 11:20:44 CST 2016
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SCZT.TYPE
     *
     * @param type the value for T_SCZT.TYPE
     *
     * @mbggenerated Fri May 20 11:20:44 CST 2016
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SCZT.HYFL
     *
     * @return the value of T_SCZT.HYFL
     *
     * @mbggenerated Fri May 20 11:20:44 CST 2016
     */
    public Integer getHyfl() {
        return hyfl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SCZT.HYFL
     *
     * @param hyfl the value for T_SCZT.HYFL
     *
     * @mbggenerated Fri May 20 11:20:44 CST 2016
     */
    public void setHyfl(Integer hyfl) {
        this.hyfl = hyfl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SCZT.ZZXS
     *
     * @return the value of T_SCZT.ZZXS
     *
     * @mbggenerated Fri May 20 11:20:44 CST 2016
     */
    public Integer getZzxs() {
        return zzxs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SCZT.ZZXS
     *
     * @param zzxs the value for T_SCZT.ZZXS
     *
     * @mbggenerated Fri May 20 11:20:44 CST 2016
     */
    public void setZzxs(Integer zzxs) {
        this.zzxs = zzxs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SCZT.JYZT
     *
     * @return the value of T_SCZT.JYZT
     *
     * @mbggenerated Fri May 20 11:20:44 CST 2016
     */
    public Integer getJyzt() {
        return jyzt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SCZT.JYZT
     *
     * @param jyzt the value for T_SCZT.JYZT
     *
     * @mbggenerated Fri May 20 11:20:44 CST 2016
     */
    public void setJyzt(Integer jyzt) {
        this.jyzt = jyzt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SCZT.FR
     *
     * @return the value of T_SCZT.FR
     *
     * @mbggenerated Fri May 20 11:20:44 CST 2016
     */
    public String getFr() {
        return fr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SCZT.FR
     *
     * @param fr the value for T_SCZT.FR
     *
     * @mbggenerated Fri May 20 11:20:44 CST 2016
     */
    public void setFr(String fr) {
        this.fr = fr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SCZT.LXDH
     *
     * @return the value of T_SCZT.LXDH
     *
     * @mbggenerated Fri May 20 11:20:44 CST 2016
     */
    public String getLxdh() {
        return lxdh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SCZT.LXDH
     *
     * @param lxdh the value for T_SCZT.LXDH
     *
     * @mbggenerated Fri May 20 11:20:44 CST 2016
     */
    public void setLxdh(String lxdh) {
        this.lxdh = lxdh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SCZT.MAIL
     *
     * @return the value of T_SCZT.MAIL
     *
     * @mbggenerated Fri May 20 11:20:44 CST 2016
     */
    public String getMail() {
        return mail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SCZT.MAIL
     *
     * @param mail the value for T_SCZT.MAIL
     *
     * @mbggenerated Fri May 20 11:20:44 CST 2016
     */
    public void setMail(String mail) {
        this.mail = mail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SCZT.DJJG
     *
     * @return the value of T_SCZT.DJJG
     *
     * @mbggenerated Fri May 20 11:20:44 CST 2016
     */
    public String getDjjg() {
        return djjg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SCZT.DJJG
     *
     * @param djjg the value for T_SCZT.DJJG
     *
     * @mbggenerated Fri May 20 11:20:44 CST 2016
     */
    public void setDjjg(String djjg) {
        this.djjg = djjg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SCZT.JYDZ
     *
     * @return the value of T_SCZT.JYDZ
     *
     * @mbggenerated Fri May 20 11:20:44 CST 2016
     */
    public String getJydz() {
        return jydz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SCZT.JYDZ
     *
     * @param jydz the value for T_SCZT.JYDZ
     *
     * @mbggenerated Fri May 20 11:20:44 CST 2016
     */
    public void setJydz(String jydz) {
        this.jydz = jydz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SCZT.LLR
     *
     * @return the value of T_SCZT.LLR
     *
     * @mbggenerated Fri May 20 11:20:44 CST 2016
     */
    public String getLlr() {
        return llr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SCZT.LLR
     *
     * @param llr the value for T_SCZT.LLR
     *
     * @mbggenerated Fri May 20 11:20:44 CST 2016
     */
    public void setLlr(String llr) {
        this.llr = llr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SCZT.SZQY
     *
     * @return the value of T_SCZT.SZQY
     *
     * @mbggenerated Fri May 20 11:20:44 CST 2016
     */
    public String getSzqy() {
        return szqy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SCZT.SZQY
     *
     * @param szqy the value for T_SCZT.SZQY
     *
     * @mbggenerated Fri May 20 11:20:44 CST 2016
     */
    public void setSzqy(String szqy) {
        this.szqy = szqy;
    }
}