package com.kysoft.cpsi.enterprise.entity;

import java.util.Date;

public class Sczt {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SCZT.ZCH
     *
     * @mbggenerated Tue May 03 15:27:09 CST 2016
     */
    private String zch;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SCZT.MC
     *
     * @mbggenerated Tue May 03 15:27:09 CST 2016
     */
    private String mc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SCZT.LX
     *
     * @mbggenerated Tue May 03 15:27:09 CST 2016
     */
    private Integer lx;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SCZT.FR
     *
     * @mbggenerated Tue May 03 15:27:09 CST 2016
     */
    private String fr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SCZT.FRSFZH
     *
     * @mbggenerated Tue May 03 15:27:09 CST 2016
     */
    private String frsfzh;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SCZT.CLRQ
     *
     * @mbggenerated Tue May 03 15:27:09 CST 2016
     */
    private Date clrq;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SCZT.ZCZB
     *
     * @mbggenerated Tue May 03 15:27:09 CST 2016
     */
    private String zczb;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SCZT.DJJG
     *
     * @mbggenerated Tue May 03 15:27:09 CST 2016
     */
    private String djjg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SCZT.DJJGMC
     *
     * @mbggenerated Tue May 03 15:27:09 CST 2016
     */
    private String djjgmc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SCZT.DJZT
     *
     * @mbggenerated Tue May 03 15:27:09 CST 2016
     */
    private Integer djzt;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SCZT.ZCH
     *
     * @return the value of T_SCZT.ZCH
     *
     * @mbggenerated Tue May 03 15:27:09 CST 2016
     */
    public String getZch() {
        return zch;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SCZT.ZCH
     *
     * @param zch the value for T_SCZT.ZCH
     *
     * @mbggenerated Tue May 03 15:27:09 CST 2016
     */
    public void setZch(String zch) {
        this.zch = zch;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SCZT.MC
     *
     * @return the value of T_SCZT.MC
     *
     * @mbggenerated Tue May 03 15:27:09 CST 2016
     */
    public String getMc() {
        return mc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SCZT.MC
     *
     * @param mc the value for T_SCZT.MC
     *
     * @mbggenerated Tue May 03 15:27:09 CST 2016
     */
    public void setMc(String mc) {
        this.mc = mc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SCZT.LX
     *
     * @return the value of T_SCZT.LX
     *
     * @mbggenerated Tue May 03 15:27:09 CST 2016
     */
    public Integer getLx() {
        return lx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SCZT.LX
     *
     * @param lx the value for T_SCZT.LX
     *
     * @mbggenerated Tue May 03 15:27:09 CST 2016
     */
    public void setLx(Integer lx) {
        this.lx = lx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SCZT.FR
     *
     * @return the value of T_SCZT.FR
     *
     * @mbggenerated Tue May 03 15:27:09 CST 2016
     */
    public String getFr() {
        return fr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SCZT.FR
     *
     * @param fr the value for T_SCZT.FR
     *
     * @mbggenerated Tue May 03 15:27:09 CST 2016
     */
    public void setFr(String fr) {
        this.fr = fr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SCZT.FRSFZH
     *
     * @return the value of T_SCZT.FRSFZH
     *
     * @mbggenerated Tue May 03 15:27:09 CST 2016
     */
    public String getFrsfzh() {
        return frsfzh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SCZT.FRSFZH
     *
     * @param frsfzh the value for T_SCZT.FRSFZH
     *
     * @mbggenerated Tue May 03 15:27:09 CST 2016
     */
    public void setFrsfzh(String frsfzh) {
        this.frsfzh = frsfzh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SCZT.CLRQ
     *
     * @return the value of T_SCZT.CLRQ
     *
     * @mbggenerated Tue May 03 15:27:09 CST 2016
     */
    public Date getClrq() {
        return clrq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SCZT.CLRQ
     *
     * @param clrq the value for T_SCZT.CLRQ
     *
     * @mbggenerated Tue May 03 15:27:09 CST 2016
     */
    public void setClrq(Date clrq) {
        this.clrq = clrq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SCZT.ZCZB
     *
     * @return the value of T_SCZT.ZCZB
     *
     * @mbggenerated Tue May 03 15:27:09 CST 2016
     */
    public String getZczb() {
        return zczb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SCZT.ZCZB
     *
     * @param zczb the value for T_SCZT.ZCZB
     *
     * @mbggenerated Tue May 03 15:27:09 CST 2016
     */
    public void setZczb(String zczb) {
        this.zczb = zczb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SCZT.DJJG
     *
     * @return the value of T_SCZT.DJJG
     *
     * @mbggenerated Tue May 03 15:27:09 CST 2016
     */
    public String getDjjg() {
        return djjg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SCZT.DJJG
     *
     * @param djjg the value for T_SCZT.DJJG
     *
     * @mbggenerated Tue May 03 15:27:09 CST 2016
     */
    public void setDjjg(String djjg) {
        this.djjg = djjg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SCZT.DJJGMC
     *
     * @return the value of T_SCZT.DJJGMC
     *
     * @mbggenerated Tue May 03 15:27:09 CST 2016
     */
    public String getDjjgmc() {
        return djjgmc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SCZT.DJJGMC
     *
     * @param djjgmc the value for T_SCZT.DJJGMC
     *
     * @mbggenerated Tue May 03 15:27:09 CST 2016
     */
    public void setDjjgmc(String djjgmc) {
        this.djjgmc = djjgmc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SCZT.DJZT
     *
     * @return the value of T_SCZT.DJZT
     *
     * @mbggenerated Tue May 03 15:27:09 CST 2016
     */
    public Integer getDjzt() {
        return djzt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SCZT.DJZT
     *
     * @param djzt the value for T_SCZT.DJZT
     *
     * @mbggenerated Tue May 03 15:27:09 CST 2016
     */
    public void setDjzt(Integer djzt) {
        this.djzt = djzt;
    }
}