package com.kysoft.cpsi.enterprise.entity;

public class Zfry {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_ZFRY.USER_ID
     *
     * @mbggenerated Tue May 03 17:59:53 CST 2016
     */
    private Object userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_ZFRY.MANAGER_ID
     *
     * @mbggenerated Tue May 03 17:59:53 CST 2016
     */
    private Object managerId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_ZFRY.NAME
     *
     * @mbggenerated Tue May 03 17:59:53 CST 2016
     */
    private Object name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_ZFRY.EMAIL
     *
     * @mbggenerated Tue May 03 17:59:53 CST 2016
     */
    private Object email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_ZFRY.MOBILE
     *
     * @mbggenerated Tue May 03 17:59:53 CST 2016
     */
    private Object mobile;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_ZFRY.MANAGER_NAME
     *
     * @mbggenerated Tue May 03 17:59:53 CST 2016
     */
    private Object managerName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_ZFRY.STATUS
     *
     * @mbggenerated Tue May 03 17:59:53 CST 2016
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_ZFRY.ORG_ID
     *
     * @mbggenerated Tue May 03 17:59:53 CST 2016
     */
    private Object orgId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_ZFRY.ORG_TYPE
     *
     * @mbggenerated Tue May 03 17:59:53 CST 2016
     */
    private Integer orgType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_ZFRY.WEIGHT
     *
     * @mbggenerated Tue May 03 17:59:53 CST 2016
     */
    private Integer weight;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_ZFRY.ORG_NAME
     *
     * @mbggenerated Tue May 03 17:59:53 CST 2016
     */
    private String orgName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_ZFRY.USER_ID
     *
     * @return the value of T_ZFRY.USER_ID
     *
     * @mbggenerated Tue May 03 17:59:53 CST 2016
     */
    public Object getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_ZFRY.USER_ID
     *
     * @param userId the value for T_ZFRY.USER_ID
     *
     * @mbggenerated Tue May 03 17:59:53 CST 2016
     */
    public void setUserId(Object userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_ZFRY.MANAGER_ID
     *
     * @return the value of T_ZFRY.MANAGER_ID
     *
     * @mbggenerated Tue May 03 17:59:53 CST 2016
     */
    public Object getManagerId() {
        return managerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_ZFRY.MANAGER_ID
     *
     * @param managerId the value for T_ZFRY.MANAGER_ID
     *
     * @mbggenerated Tue May 03 17:59:53 CST 2016
     */
    public void setManagerId(Object managerId) {
        this.managerId = managerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_ZFRY.NAME
     *
     * @return the value of T_ZFRY.NAME
     *
     * @mbggenerated Tue May 03 17:59:53 CST 2016
     */
    public Object getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_ZFRY.NAME
     *
     * @param name the value for T_ZFRY.NAME
     *
     * @mbggenerated Tue May 03 17:59:53 CST 2016
     */
    public void setName(Object name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_ZFRY.EMAIL
     *
     * @return the value of T_ZFRY.EMAIL
     *
     * @mbggenerated Tue May 03 17:59:53 CST 2016
     */
    public Object getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_ZFRY.EMAIL
     *
     * @param email the value for T_ZFRY.EMAIL
     *
     * @mbggenerated Tue May 03 17:59:53 CST 2016
     */
    public void setEmail(Object email) {
        this.email = email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_ZFRY.MOBILE
     *
     * @return the value of T_ZFRY.MOBILE
     *
     * @mbggenerated Tue May 03 17:59:53 CST 2016
     */
    public Object getMobile() {
        return mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_ZFRY.MOBILE
     *
     * @param mobile the value for T_ZFRY.MOBILE
     *
     * @mbggenerated Tue May 03 17:59:53 CST 2016
     */
    public void setMobile(Object mobile) {
        this.mobile = mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_ZFRY.MANAGER_NAME
     *
     * @return the value of T_ZFRY.MANAGER_NAME
     *
     * @mbggenerated Tue May 03 17:59:53 CST 2016
     */
    public Object getManagerName() {
        return managerName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_ZFRY.MANAGER_NAME
     *
     * @param managerName the value for T_ZFRY.MANAGER_NAME
     *
     * @mbggenerated Tue May 03 17:59:53 CST 2016
     */
    public void setManagerName(Object managerName) {
        this.managerName = managerName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_ZFRY.STATUS
     *
     * @return the value of T_ZFRY.STATUS
     *
     * @mbggenerated Tue May 03 17:59:53 CST 2016
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_ZFRY.STATUS
     *
     * @param status the value for T_ZFRY.STATUS
     *
     * @mbggenerated Tue May 03 17:59:53 CST 2016
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_ZFRY.ORG_ID
     *
     * @return the value of T_ZFRY.ORG_ID
     *
     * @mbggenerated Tue May 03 17:59:53 CST 2016
     */
    public Object getOrgId() {
        return orgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_ZFRY.ORG_ID
     *
     * @param orgId the value for T_ZFRY.ORG_ID
     *
     * @mbggenerated Tue May 03 17:59:53 CST 2016
     */
    public void setOrgId(Object orgId) {
        this.orgId = orgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_ZFRY.ORG_TYPE
     *
     * @return the value of T_ZFRY.ORG_TYPE
     *
     * @mbggenerated Tue May 03 17:59:53 CST 2016
     */
    public Integer getOrgType() {
        return orgType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_ZFRY.ORG_TYPE
     *
     * @param orgType the value for T_ZFRY.ORG_TYPE
     *
     * @mbggenerated Tue May 03 17:59:53 CST 2016
     */
    public void setOrgType(Integer orgType) {
        this.orgType = orgType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_ZFRY.WEIGHT
     *
     * @return the value of T_ZFRY.WEIGHT
     *
     * @mbggenerated Tue May 03 17:59:53 CST 2016
     */
    public Integer getWeight() {
        return weight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_ZFRY.WEIGHT
     *
     * @param weight the value for T_ZFRY.WEIGHT
     *
     * @mbggenerated Tue May 03 17:59:53 CST 2016
     */
    public void setWeight(Integer weight) {
        this.weight = weight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_ZFRY.ORG_NAME
     *
     * @return the value of T_ZFRY.ORG_NAME
     *
     * @mbggenerated Tue May 03 17:59:53 CST 2016
     */
    public String getOrgName() {
        return orgName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_ZFRY.ORG_NAME
     *
     * @param orgName the value for T_ZFRY.ORG_NAME
     *
     * @mbggenerated Tue May 03 17:59:53 CST 2016
     */
    public void setOrgName(String orgName) {
        this.orgName = orgName;
    }
}