package com.kysoft.cpsi.audit.entity;

public class AnnualReport extends AnnualReportKey {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column T_NB.QYMC
	 * @mbg.generated  Tue Jan 17 14:07:24 CST 2017
	 */
	private String qymc;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column T_NB.TXDZ
	 * @mbg.generated  Tue Jan 17 14:07:24 CST 2017
	 */
	private String txdz;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column T_NB.MAIL
	 * @mbg.generated  Tue Jan 17 14:07:24 CST 2017
	 */
	private String mail;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column T_NB.SFTZGMGQ
	 * @mbg.generated  Tue Jan 17 14:07:24 CST 2017
	 */
	private String sftzgmgq;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column T_NB.JYZT
	 * @mbg.generated  Tue Jan 17 14:07:24 CST 2017
	 */
	private String jyzt;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column T_NB.SFYWZWD
	 * @mbg.generated  Tue Jan 17 14:07:24 CST 2017
	 */
	private String sfywzwd;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column T_NB.SFYDWDBXX
	 * @mbg.generated  Tue Jan 17 14:07:24 CST 2017
	 */
	private String sfydwdbxx;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column T_NB.CYRS
	 * @mbg.generated  Tue Jan 17 14:07:24 CST 2017
	 */
	private Integer cyrs;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column T_NB.SYZQYHJ
	 * @mbg.generated  Tue Jan 17 14:07:24 CST 2017
	 */
	private Float syzqyhj;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column T_NB.LRZE
	 * @mbg.generated  Tue Jan 17 14:07:24 CST 2017
	 */
	private Float lrze;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column T_NB.ZYYWSR
	 * @mbg.generated  Tue Jan 17 14:07:24 CST 2017
	 */
	private Float zyywsr;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column T_NB.JLR
	 * @mbg.generated  Tue Jan 17 14:07:24 CST 2017
	 */
	private Float jlr;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column T_NB.NSZE
	 * @mbg.generated  Tue Jan 17 14:07:24 CST 2017
	 */
	private Float nsze;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column T_NB.FZZE
	 * @mbg.generated  Tue Jan 17 14:07:24 CST 2017
	 */
	private Float fzze;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column T_NB.LXDH
	 * @mbg.generated  Tue Jan 17 14:07:24 CST 2017
	 */
	private String lxdh;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column T_NB.YZBM
	 * @mbg.generated  Tue Jan 17 14:07:24 CST 2017
	 */
	private String yzbm;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column T_NB.ZCZE
	 * @mbg.generated  Tue Jan 17 14:07:24 CST 2017
	 */
	private Float zcze;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column T_NB.GXBYS_JY
	 * @mbg.generated  Tue Jan 17 14:07:24 CST 2017
	 */
	private Integer gxbysJy;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column T_NB.GXBYS_GG
	 * @mbg.generated  Tue Jan 17 14:07:24 CST 2017
	 */
	private Integer gxbysGg;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column T_NB.TYSBS_JY
	 * @mbg.generated  Tue Jan 17 14:07:24 CST 2017
	 */
	private Integer tysbsJy;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column T_NB.TYSBS_GG
	 * @mbg.generated  Tue Jan 17 14:07:24 CST 2017
	 */
	private Integer tysbsGg;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column T_NB.CJRS_JY
	 * @mbg.generated  Tue Jan 17 14:07:24 CST 2017
	 */
	private Integer cjrsJy;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column T_NB.CJRS_GG
	 * @mbg.generated  Tue Jan 17 14:07:24 CST 2017
	 */
	private Integer cjrsGg;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column T_NB.ZJYS_JY
	 * @mbg.generated  Tue Jan 17 14:07:24 CST 2017
	 */
	private Integer zjysJy;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column T_NB.ZJYS_GG
	 * @mbg.generated  Tue Jan 17 14:07:24 CST 2017
	 */
	private Integer zjysGg;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column T_NB.DJ_FRSFDY
	 * @mbg.generated  Tue Jan 17 14:07:24 CST 2017
	 */
	private String djFrsfdy;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column T_NB.DJ_LXDH
	 * @mbg.generated  Tue Jan 17 14:07:24 CST 2017
	 */
	private String djLxdh;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column T_NB.DJ_QTZW
	 * @mbg.generated  Tue Jan 17 14:07:24 CST 2017
	 */
	private Integer djQtzw;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column T_NB.DJ_DYZS
	 * @mbg.generated  Tue Jan 17 14:07:24 CST 2017
	 */
	private Integer djDyzs;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column T_NB.DJ_ZCDYS
	 * @mbg.generated  Tue Jan 17 14:07:24 CST 2017
	 */
	private Integer djZcdys;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column T_NB.DJ_WZRS
	 * @mbg.generated  Tue Jan 17 14:07:24 CST 2017
	 */
	private Integer djWzrs;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column T_NB.DJ_FZDYS
	 * @mbg.generated  Tue Jan 17 14:07:24 CST 2017
	 */
	private Integer djFzdys;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column T_NB.DJ_JJFZS
	 * @mbg.generated  Tue Jan 17 14:07:24 CST 2017
	 */
	private Integer djJjfzs;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column T_NB.DJ_SFJLZZ
	 * @mbg.generated  Tue Jan 17 14:07:24 CST 2017
	 */
	private String djSfjlzz;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column T_NB.DJ_WJLZZYY
	 * @mbg.generated  Tue Jan 17 14:07:24 CST 2017
	 */
	private String djWjlzzyy;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column T_NB.YYZSR
	 * @mbg.generated  Tue Jan 17 14:07:24 CST 2017
	 */
	private Float yyzsr;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column T_NB.DJ_DZZJZ
	 * @mbg.generated  Tue Jan 17 14:07:24 CST 2017
	 */
	private String djDzzjz;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column T_NB.DJ_FRDBSFDZZSJ
	 * @mbg.generated  Tue Jan 17 14:07:24 CST 2017
	 */
	private String djFrdbsfdzzsj;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column T_NB.QYMC
	 * @return  the value of T_NB.QYMC
	 * @mbg.generated  Tue Jan 17 14:07:24 CST 2017
	 */
	public String getQymc() {
		return qymc;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column T_NB.QYMC
	 * @param qymc  the value for T_NB.QYMC
	 * @mbg.generated  Tue Jan 17 14:07:24 CST 2017
	 */
	public void setQymc(String qymc) {
		this.qymc = qymc;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column T_NB.TXDZ
	 * @return  the value of T_NB.TXDZ
	 * @mbg.generated  Tue Jan 17 14:07:24 CST 2017
	 */
	public String getTxdz() {
		return txdz;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column T_NB.TXDZ
	 * @param txdz  the value for T_NB.TXDZ
	 * @mbg.generated  Tue Jan 17 14:07:24 CST 2017
	 */
	public void setTxdz(String txdz) {
		this.txdz = txdz;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column T_NB.MAIL
	 * @return  the value of T_NB.MAIL
	 * @mbg.generated  Tue Jan 17 14:07:24 CST 2017
	 */
	public String getMail() {
		return mail;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column T_NB.MAIL
	 * @param mail  the value for T_NB.MAIL
	 * @mbg.generated  Tue Jan 17 14:07:24 CST 2017
	 */
	public void setMail(String mail) {
		this.mail = mail;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column T_NB.SFTZGMGQ
	 * @return  the value of T_NB.SFTZGMGQ
	 * @mbg.generated  Tue Jan 17 14:07:24 CST 2017
	 */
	public String getSftzgmgq() {
		return sftzgmgq;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column T_NB.SFTZGMGQ
	 * @param sftzgmgq  the value for T_NB.SFTZGMGQ
	 * @mbg.generated  Tue Jan 17 14:07:24 CST 2017
	 */
	public void setSftzgmgq(String sftzgmgq) {
		this.sftzgmgq = sftzgmgq;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column T_NB.JYZT
	 * @return  the value of T_NB.JYZT
	 * @mbg.generated  Tue Jan 17 14:07:24 CST 2017
	 */
	public String getJyzt() {
		return jyzt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column T_NB.JYZT
	 * @param jyzt  the value for T_NB.JYZT
	 * @mbg.generated  Tue Jan 17 14:07:24 CST 2017
	 */
	public void setJyzt(String jyzt) {
		this.jyzt = jyzt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column T_NB.SFYWZWD
	 * @return  the value of T_NB.SFYWZWD
	 * @mbg.generated  Tue Jan 17 14:07:24 CST 2017
	 */
	public String getSfywzwd() {
		return sfywzwd;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column T_NB.SFYWZWD
	 * @param sfywzwd  the value for T_NB.SFYWZWD
	 * @mbg.generated  Tue Jan 17 14:07:24 CST 2017
	 */
	public void setSfywzwd(String sfywzwd) {
		this.sfywzwd = sfywzwd;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column T_NB.SFYDWDBXX
	 * @return  the value of T_NB.SFYDWDBXX
	 * @mbg.generated  Tue Jan 17 14:07:24 CST 2017
	 */
	public String getSfydwdbxx() {
		return sfydwdbxx;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column T_NB.SFYDWDBXX
	 * @param sfydwdbxx  the value for T_NB.SFYDWDBXX
	 * @mbg.generated  Tue Jan 17 14:07:24 CST 2017
	 */
	public void setSfydwdbxx(String sfydwdbxx) {
		this.sfydwdbxx = sfydwdbxx;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column T_NB.CYRS
	 * @return  the value of T_NB.CYRS
	 * @mbg.generated  Tue Jan 17 14:07:24 CST 2017
	 */
	public Integer getCyrs() {
		return cyrs;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column T_NB.CYRS
	 * @param cyrs  the value for T_NB.CYRS
	 * @mbg.generated  Tue Jan 17 14:07:24 CST 2017
	 */
	public void setCyrs(Integer cyrs) {
		this.cyrs = cyrs;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column T_NB.SYZQYHJ
	 * @return  the value of T_NB.SYZQYHJ
	 * @mbg.generated  Tue Jan 17 14:07:24 CST 2017
	 */
	public Float getSyzqyhj() {
		return syzqyhj;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column T_NB.SYZQYHJ
	 * @param syzqyhj  the value for T_NB.SYZQYHJ
	 * @mbg.generated  Tue Jan 17 14:07:24 CST 2017
	 */
	public void setSyzqyhj(Float syzqyhj) {
		this.syzqyhj = syzqyhj;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column T_NB.LRZE
	 * @return  the value of T_NB.LRZE
	 * @mbg.generated  Tue Jan 17 14:07:24 CST 2017
	 */
	public Float getLrze() {
		return lrze;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column T_NB.LRZE
	 * @param lrze  the value for T_NB.LRZE
	 * @mbg.generated  Tue Jan 17 14:07:24 CST 2017
	 */
	public void setLrze(Float lrze) {
		this.lrze = lrze;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column T_NB.ZYYWSR
	 * @return  the value of T_NB.ZYYWSR
	 * @mbg.generated  Tue Jan 17 14:07:24 CST 2017
	 */
	public Float getZyywsr() {
		return zyywsr;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column T_NB.ZYYWSR
	 * @param zyywsr  the value for T_NB.ZYYWSR
	 * @mbg.generated  Tue Jan 17 14:07:24 CST 2017
	 */
	public void setZyywsr(Float zyywsr) {
		this.zyywsr = zyywsr;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column T_NB.JLR
	 * @return  the value of T_NB.JLR
	 * @mbg.generated  Tue Jan 17 14:07:24 CST 2017
	 */
	public Float getJlr() {
		return jlr;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column T_NB.JLR
	 * @param jlr  the value for T_NB.JLR
	 * @mbg.generated  Tue Jan 17 14:07:24 CST 2017
	 */
	public void setJlr(Float jlr) {
		this.jlr = jlr;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column T_NB.NSZE
	 * @return  the value of T_NB.NSZE
	 * @mbg.generated  Tue Jan 17 14:07:24 CST 2017
	 */
	public Float getNsze() {
		return nsze;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column T_NB.NSZE
	 * @param nsze  the value for T_NB.NSZE
	 * @mbg.generated  Tue Jan 17 14:07:24 CST 2017
	 */
	public void setNsze(Float nsze) {
		this.nsze = nsze;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column T_NB.FZZE
	 * @return  the value of T_NB.FZZE
	 * @mbg.generated  Tue Jan 17 14:07:24 CST 2017
	 */
	public Float getFzze() {
		return fzze;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column T_NB.FZZE
	 * @param fzze  the value for T_NB.FZZE
	 * @mbg.generated  Tue Jan 17 14:07:24 CST 2017
	 */
	public void setFzze(Float fzze) {
		this.fzze = fzze;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column T_NB.LXDH
	 * @return  the value of T_NB.LXDH
	 * @mbg.generated  Tue Jan 17 14:07:24 CST 2017
	 */
	public String getLxdh() {
		return lxdh;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column T_NB.LXDH
	 * @param lxdh  the value for T_NB.LXDH
	 * @mbg.generated  Tue Jan 17 14:07:24 CST 2017
	 */
	public void setLxdh(String lxdh) {
		this.lxdh = lxdh;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column T_NB.YZBM
	 * @return  the value of T_NB.YZBM
	 * @mbg.generated  Tue Jan 17 14:07:24 CST 2017
	 */
	public String getYzbm() {
		return yzbm;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column T_NB.YZBM
	 * @param yzbm  the value for T_NB.YZBM
	 * @mbg.generated  Tue Jan 17 14:07:24 CST 2017
	 */
	public void setYzbm(String yzbm) {
		this.yzbm = yzbm;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column T_NB.ZCZE
	 * @return  the value of T_NB.ZCZE
	 * @mbg.generated  Tue Jan 17 14:07:24 CST 2017
	 */
	public Float getZcze() {
		return zcze;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column T_NB.ZCZE
	 * @param zcze  the value for T_NB.ZCZE
	 * @mbg.generated  Tue Jan 17 14:07:24 CST 2017
	 */
	public void setZcze(Float zcze) {
		this.zcze = zcze;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column T_NB.GXBYS_JY
	 * @return  the value of T_NB.GXBYS_JY
	 * @mbg.generated  Tue Jan 17 14:07:24 CST 2017
	 */
	public Integer getGxbysJy() {
		return gxbysJy;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column T_NB.GXBYS_JY
	 * @param gxbysJy  the value for T_NB.GXBYS_JY
	 * @mbg.generated  Tue Jan 17 14:07:24 CST 2017
	 */
	public void setGxbysJy(Integer gxbysJy) {
		this.gxbysJy = gxbysJy;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column T_NB.GXBYS_GG
	 * @return  the value of T_NB.GXBYS_GG
	 * @mbg.generated  Tue Jan 17 14:07:24 CST 2017
	 */
	public Integer getGxbysGg() {
		return gxbysGg;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column T_NB.GXBYS_GG
	 * @param gxbysGg  the value for T_NB.GXBYS_GG
	 * @mbg.generated  Tue Jan 17 14:07:24 CST 2017
	 */
	public void setGxbysGg(Integer gxbysGg) {
		this.gxbysGg = gxbysGg;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column T_NB.TYSBS_JY
	 * @return  the value of T_NB.TYSBS_JY
	 * @mbg.generated  Tue Jan 17 14:07:24 CST 2017
	 */
	public Integer getTysbsJy() {
		return tysbsJy;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column T_NB.TYSBS_JY
	 * @param tysbsJy  the value for T_NB.TYSBS_JY
	 * @mbg.generated  Tue Jan 17 14:07:24 CST 2017
	 */
	public void setTysbsJy(Integer tysbsJy) {
		this.tysbsJy = tysbsJy;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column T_NB.TYSBS_GG
	 * @return  the value of T_NB.TYSBS_GG
	 * @mbg.generated  Tue Jan 17 14:07:24 CST 2017
	 */
	public Integer getTysbsGg() {
		return tysbsGg;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column T_NB.TYSBS_GG
	 * @param tysbsGg  the value for T_NB.TYSBS_GG
	 * @mbg.generated  Tue Jan 17 14:07:24 CST 2017
	 */
	public void setTysbsGg(Integer tysbsGg) {
		this.tysbsGg = tysbsGg;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column T_NB.CJRS_JY
	 * @return  the value of T_NB.CJRS_JY
	 * @mbg.generated  Tue Jan 17 14:07:24 CST 2017
	 */
	public Integer getCjrsJy() {
		return cjrsJy;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column T_NB.CJRS_JY
	 * @param cjrsJy  the value for T_NB.CJRS_JY
	 * @mbg.generated  Tue Jan 17 14:07:24 CST 2017
	 */
	public void setCjrsJy(Integer cjrsJy) {
		this.cjrsJy = cjrsJy;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column T_NB.CJRS_GG
	 * @return  the value of T_NB.CJRS_GG
	 * @mbg.generated  Tue Jan 17 14:07:24 CST 2017
	 */
	public Integer getCjrsGg() {
		return cjrsGg;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column T_NB.CJRS_GG
	 * @param cjrsGg  the value for T_NB.CJRS_GG
	 * @mbg.generated  Tue Jan 17 14:07:24 CST 2017
	 */
	public void setCjrsGg(Integer cjrsGg) {
		this.cjrsGg = cjrsGg;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column T_NB.ZJYS_JY
	 * @return  the value of T_NB.ZJYS_JY
	 * @mbg.generated  Tue Jan 17 14:07:24 CST 2017
	 */
	public Integer getZjysJy() {
		return zjysJy;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column T_NB.ZJYS_JY
	 * @param zjysJy  the value for T_NB.ZJYS_JY
	 * @mbg.generated  Tue Jan 17 14:07:24 CST 2017
	 */
	public void setZjysJy(Integer zjysJy) {
		this.zjysJy = zjysJy;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column T_NB.ZJYS_GG
	 * @return  the value of T_NB.ZJYS_GG
	 * @mbg.generated  Tue Jan 17 14:07:24 CST 2017
	 */
	public Integer getZjysGg() {
		return zjysGg;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column T_NB.ZJYS_GG
	 * @param zjysGg  the value for T_NB.ZJYS_GG
	 * @mbg.generated  Tue Jan 17 14:07:24 CST 2017
	 */
	public void setZjysGg(Integer zjysGg) {
		this.zjysGg = zjysGg;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column T_NB.DJ_FRSFDY
	 * @return  the value of T_NB.DJ_FRSFDY
	 * @mbg.generated  Tue Jan 17 14:07:24 CST 2017
	 */
	public String getDjFrsfdy() {
		return djFrsfdy;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column T_NB.DJ_FRSFDY
	 * @param djFrsfdy  the value for T_NB.DJ_FRSFDY
	 * @mbg.generated  Tue Jan 17 14:07:24 CST 2017
	 */
	public void setDjFrsfdy(String djFrsfdy) {
		this.djFrsfdy = djFrsfdy;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column T_NB.DJ_LXDH
	 * @return  the value of T_NB.DJ_LXDH
	 * @mbg.generated  Tue Jan 17 14:07:24 CST 2017
	 */
	public String getDjLxdh() {
		return djLxdh;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column T_NB.DJ_LXDH
	 * @param djLxdh  the value for T_NB.DJ_LXDH
	 * @mbg.generated  Tue Jan 17 14:07:24 CST 2017
	 */
	public void setDjLxdh(String djLxdh) {
		this.djLxdh = djLxdh;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column T_NB.DJ_QTZW
	 * @return  the value of T_NB.DJ_QTZW
	 * @mbg.generated  Tue Jan 17 14:07:24 CST 2017
	 */
	public Integer getDjQtzw() {
		return djQtzw;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column T_NB.DJ_QTZW
	 * @param djQtzw  the value for T_NB.DJ_QTZW
	 * @mbg.generated  Tue Jan 17 14:07:24 CST 2017
	 */
	public void setDjQtzw(Integer djQtzw) {
		this.djQtzw = djQtzw;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column T_NB.DJ_DYZS
	 * @return  the value of T_NB.DJ_DYZS
	 * @mbg.generated  Tue Jan 17 14:07:24 CST 2017
	 */
	public Integer getDjDyzs() {
		return djDyzs;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column T_NB.DJ_DYZS
	 * @param djDyzs  the value for T_NB.DJ_DYZS
	 * @mbg.generated  Tue Jan 17 14:07:24 CST 2017
	 */
	public void setDjDyzs(Integer djDyzs) {
		this.djDyzs = djDyzs;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column T_NB.DJ_ZCDYS
	 * @return  the value of T_NB.DJ_ZCDYS
	 * @mbg.generated  Tue Jan 17 14:07:24 CST 2017
	 */
	public Integer getDjZcdys() {
		return djZcdys;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column T_NB.DJ_ZCDYS
	 * @param djZcdys  the value for T_NB.DJ_ZCDYS
	 * @mbg.generated  Tue Jan 17 14:07:24 CST 2017
	 */
	public void setDjZcdys(Integer djZcdys) {
		this.djZcdys = djZcdys;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column T_NB.DJ_WZRS
	 * @return  the value of T_NB.DJ_WZRS
	 * @mbg.generated  Tue Jan 17 14:07:24 CST 2017
	 */
	public Integer getDjWzrs() {
		return djWzrs;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column T_NB.DJ_WZRS
	 * @param djWzrs  the value for T_NB.DJ_WZRS
	 * @mbg.generated  Tue Jan 17 14:07:24 CST 2017
	 */
	public void setDjWzrs(Integer djWzrs) {
		this.djWzrs = djWzrs;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column T_NB.DJ_FZDYS
	 * @return  the value of T_NB.DJ_FZDYS
	 * @mbg.generated  Tue Jan 17 14:07:24 CST 2017
	 */
	public Integer getDjFzdys() {
		return djFzdys;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column T_NB.DJ_FZDYS
	 * @param djFzdys  the value for T_NB.DJ_FZDYS
	 * @mbg.generated  Tue Jan 17 14:07:24 CST 2017
	 */
	public void setDjFzdys(Integer djFzdys) {
		this.djFzdys = djFzdys;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column T_NB.DJ_JJFZS
	 * @return  the value of T_NB.DJ_JJFZS
	 * @mbg.generated  Tue Jan 17 14:07:24 CST 2017
	 */
	public Integer getDjJjfzs() {
		return djJjfzs;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column T_NB.DJ_JJFZS
	 * @param djJjfzs  the value for T_NB.DJ_JJFZS
	 * @mbg.generated  Tue Jan 17 14:07:24 CST 2017
	 */
	public void setDjJjfzs(Integer djJjfzs) {
		this.djJjfzs = djJjfzs;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column T_NB.DJ_SFJLZZ
	 * @return  the value of T_NB.DJ_SFJLZZ
	 * @mbg.generated  Tue Jan 17 14:07:24 CST 2017
	 */
	public String getDjSfjlzz() {
		return djSfjlzz;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column T_NB.DJ_SFJLZZ
	 * @param djSfjlzz  the value for T_NB.DJ_SFJLZZ
	 * @mbg.generated  Tue Jan 17 14:07:24 CST 2017
	 */
	public void setDjSfjlzz(String djSfjlzz) {
		this.djSfjlzz = djSfjlzz;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column T_NB.DJ_WJLZZYY
	 * @return  the value of T_NB.DJ_WJLZZYY
	 * @mbg.generated  Tue Jan 17 14:07:24 CST 2017
	 */
	public String getDjWjlzzyy() {
		return djWjlzzyy;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column T_NB.DJ_WJLZZYY
	 * @param djWjlzzyy  the value for T_NB.DJ_WJLZZYY
	 * @mbg.generated  Tue Jan 17 14:07:24 CST 2017
	 */
	public void setDjWjlzzyy(String djWjlzzyy) {
		this.djWjlzzyy = djWjlzzyy;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column T_NB.YYZSR
	 * @return  the value of T_NB.YYZSR
	 * @mbg.generated  Tue Jan 17 14:07:24 CST 2017
	 */
	public Float getYyzsr() {
		return yyzsr;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column T_NB.YYZSR
	 * @param yyzsr  the value for T_NB.YYZSR
	 * @mbg.generated  Tue Jan 17 14:07:24 CST 2017
	 */
	public void setYyzsr(Float yyzsr) {
		this.yyzsr = yyzsr;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column T_NB.DJ_DZZJZ
	 * @return  the value of T_NB.DJ_DZZJZ
	 * @mbg.generated  Tue Jan 17 14:07:24 CST 2017
	 */
	public String getDjDzzjz() {
		return djDzzjz;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column T_NB.DJ_DZZJZ
	 * @param djDzzjz  the value for T_NB.DJ_DZZJZ
	 * @mbg.generated  Tue Jan 17 14:07:24 CST 2017
	 */
	public void setDjDzzjz(String djDzzjz) {
		this.djDzzjz = djDzzjz;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column T_NB.DJ_FRDBSFDZZSJ
	 * @return  the value of T_NB.DJ_FRDBSFDZZSJ
	 * @mbg.generated  Tue Jan 17 14:07:24 CST 2017
	 */
	public String getDjFrdbsfdzzsj() {
		return djFrdbsfdzzsj;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column T_NB.DJ_FRDBSFDZZSJ
	 * @param djFrdbsfdzzsj  the value for T_NB.DJ_FRDBSFDZZSJ
	 * @mbg.generated  Tue Jan 17 14:07:24 CST 2017
	 */
	public void setDjFrdbsfdzzsj(String djFrdbsfdzzsj) {
		this.djFrdbsfdzzsj = djFrdbsfdzzsj;
	}
}