package com.kysoft.cpsi.audit.entity;

public class GuaranteeKey {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column T_NB_DWDB.ID
	 * @mbggenerated  Mon May 30 19:14:20 CST 2016
	 */
	private String id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column T_NB_DWDB.ND
	 * @mbggenerated  Mon May 30 19:14:20 CST 2016
	 */
	private Integer nd;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column T_NB_DWDB.XYDM
	 * @mbggenerated  Mon May 30 19:14:20 CST 2016
	 */
	private String xydm;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column T_NB_DWDB.ID
	 * @return  the value of T_NB_DWDB.ID
	 * @mbggenerated  Mon May 30 19:14:20 CST 2016
	 */
	public String getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column T_NB_DWDB.ID
	 * @param id  the value for T_NB_DWDB.ID
	 * @mbggenerated  Mon May 30 19:14:20 CST 2016
	 */
	public void setId(String id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column T_NB_DWDB.ND
	 * @return  the value of T_NB_DWDB.ND
	 * @mbggenerated  Mon May 30 19:14:20 CST 2016
	 */
	public Integer getNd() {
		return nd;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column T_NB_DWDB.ND
	 * @param nd  the value for T_NB_DWDB.ND
	 * @mbggenerated  Mon May 30 19:14:20 CST 2016
	 */
	public void setNd(Integer nd) {
		this.nd = nd;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column T_NB_DWDB.XYDM
	 * @return  the value of T_NB_DWDB.XYDM
	 * @mbggenerated  Mon May 30 19:14:20 CST 2016
	 */
	public String getXydm() {
		return xydm;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column T_NB_DWDB.XYDM
	 * @param xydm  the value for T_NB_DWDB.XYDM
	 * @mbggenerated  Mon May 30 19:14:20 CST 2016
	 */
	public void setXydm(String xydm) {
		this.xydm = xydm;
	}
}