package com.kysoft.cpsi.audit.entity;

import java.math.BigDecimal;

public class Guarantee {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column T_NB_DWDB.ID
	 * @mbggenerated  Tue May 31 10:35:29 CST 2016
	 */
	private String id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column T_NB_DWDB.ND
	 * @mbggenerated  Tue May 31 10:35:29 CST 2016
	 */
	private Integer nd;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column T_NB_DWDB.XYDM
	 * @mbggenerated  Tue May 31 10:35:29 CST 2016
	 */
	private String xydm;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column T_NB_DWDB.ZQR
	 * @mbggenerated  Tue May 31 10:35:29 CST 2016
	 */
	private String zqr;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column T_NB_DWDB.ZWR
	 * @mbggenerated  Tue May 31 10:35:29 CST 2016
	 */
	private String zwr;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column T_NB_DWDB.ZZQZL
	 * @mbggenerated  Tue May 31 10:35:29 CST 2016
	 */
	private Integer zzqzl;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column T_NB_DWDB.ZZQSE
	 * @mbggenerated  Tue May 31 10:35:29 CST 2016
	 */
	private BigDecimal zzqse;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column T_NB_DWDB.LXZWQX
	 * @mbggenerated  Tue May 31 10:35:29 CST 2016
	 */
	private String lxzwqx;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column T_NB_DWDB.BZQJ
	 * @mbggenerated  Tue May 31 10:35:29 CST 2016
	 */
	private String bzqj;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column T_NB_DWDB.BZFS
	 * @mbggenerated  Tue May 31 10:35:29 CST 2016
	 */
	private Integer bzfs;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column T_NB_DWDB.BZDBFW
	 * @mbggenerated  Tue May 31 10:35:29 CST 2016
	 */
	private String bzdbfw;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column T_NB_DWDB.HCRW_ID
	 * @mbggenerated  Tue May 31 10:35:29 CST 2016
	 */
	private String hcrwId;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column T_NB_DWDB.ID
	 * @return  the value of T_NB_DWDB.ID
	 * @mbggenerated  Tue May 31 10:35:29 CST 2016
	 */
	public String getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column T_NB_DWDB.ID
	 * @param id  the value for T_NB_DWDB.ID
	 * @mbggenerated  Tue May 31 10:35:29 CST 2016
	 */
	public void setId(String id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column T_NB_DWDB.ND
	 * @return  the value of T_NB_DWDB.ND
	 * @mbggenerated  Tue May 31 10:35:29 CST 2016
	 */
	public Integer getNd() {
		return nd;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column T_NB_DWDB.ND
	 * @param nd  the value for T_NB_DWDB.ND
	 * @mbggenerated  Tue May 31 10:35:29 CST 2016
	 */
	public void setNd(Integer nd) {
		this.nd = nd;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column T_NB_DWDB.XYDM
	 * @return  the value of T_NB_DWDB.XYDM
	 * @mbggenerated  Tue May 31 10:35:29 CST 2016
	 */
	public String getXydm() {
		return xydm;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column T_NB_DWDB.XYDM
	 * @param xydm  the value for T_NB_DWDB.XYDM
	 * @mbggenerated  Tue May 31 10:35:29 CST 2016
	 */
	public void setXydm(String xydm) {
		this.xydm = xydm;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column T_NB_DWDB.ZQR
	 * @return  the value of T_NB_DWDB.ZQR
	 * @mbggenerated  Tue May 31 10:35:29 CST 2016
	 */
	public String getZqr() {
		return zqr;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column T_NB_DWDB.ZQR
	 * @param zqr  the value for T_NB_DWDB.ZQR
	 * @mbggenerated  Tue May 31 10:35:29 CST 2016
	 */
	public void setZqr(String zqr) {
		this.zqr = zqr;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column T_NB_DWDB.ZWR
	 * @return  the value of T_NB_DWDB.ZWR
	 * @mbggenerated  Tue May 31 10:35:29 CST 2016
	 */
	public String getZwr() {
		return zwr;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column T_NB_DWDB.ZWR
	 * @param zwr  the value for T_NB_DWDB.ZWR
	 * @mbggenerated  Tue May 31 10:35:29 CST 2016
	 */
	public void setZwr(String zwr) {
		this.zwr = zwr;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column T_NB_DWDB.ZZQZL
	 * @return  the value of T_NB_DWDB.ZZQZL
	 * @mbggenerated  Tue May 31 10:35:29 CST 2016
	 */
	public Integer getZzqzl() {
		return zzqzl;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column T_NB_DWDB.ZZQZL
	 * @param zzqzl  the value for T_NB_DWDB.ZZQZL
	 * @mbggenerated  Tue May 31 10:35:29 CST 2016
	 */
	public void setZzqzl(Integer zzqzl) {
		this.zzqzl = zzqzl;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column T_NB_DWDB.ZZQSE
	 * @return  the value of T_NB_DWDB.ZZQSE
	 * @mbggenerated  Tue May 31 10:35:29 CST 2016
	 */
	public BigDecimal getZzqse() {
		return zzqse;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column T_NB_DWDB.ZZQSE
	 * @param zzqse  the value for T_NB_DWDB.ZZQSE
	 * @mbggenerated  Tue May 31 10:35:29 CST 2016
	 */
	public void setZzqse(BigDecimal zzqse) {
		this.zzqse = zzqse;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column T_NB_DWDB.LXZWQX
	 * @return  the value of T_NB_DWDB.LXZWQX
	 * @mbggenerated  Tue May 31 10:35:29 CST 2016
	 */
	public String getLxzwqx() {
		return lxzwqx;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column T_NB_DWDB.LXZWQX
	 * @param lxzwqx  the value for T_NB_DWDB.LXZWQX
	 * @mbggenerated  Tue May 31 10:35:29 CST 2016
	 */
	public void setLxzwqx(String lxzwqx) {
		this.lxzwqx = lxzwqx;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column T_NB_DWDB.BZQJ
	 * @return  the value of T_NB_DWDB.BZQJ
	 * @mbggenerated  Tue May 31 10:35:29 CST 2016
	 */
	public String getBzqj() {
		return bzqj;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column T_NB_DWDB.BZQJ
	 * @param bzqj  the value for T_NB_DWDB.BZQJ
	 * @mbggenerated  Tue May 31 10:35:29 CST 2016
	 */
	public void setBzqj(String bzqj) {
		this.bzqj = bzqj;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column T_NB_DWDB.BZFS
	 * @return  the value of T_NB_DWDB.BZFS
	 * @mbggenerated  Tue May 31 10:35:29 CST 2016
	 */
	public Integer getBzfs() {
		return bzfs;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column T_NB_DWDB.BZFS
	 * @param bzfs  the value for T_NB_DWDB.BZFS
	 * @mbggenerated  Tue May 31 10:35:29 CST 2016
	 */
	public void setBzfs(Integer bzfs) {
		this.bzfs = bzfs;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column T_NB_DWDB.BZDBFW
	 * @return  the value of T_NB_DWDB.BZDBFW
	 * @mbggenerated  Tue May 31 10:35:29 CST 2016
	 */
	public String getBzdbfw() {
		return bzdbfw;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column T_NB_DWDB.BZDBFW
	 * @param bzdbfw  the value for T_NB_DWDB.BZDBFW
	 * @mbggenerated  Tue May 31 10:35:29 CST 2016
	 */
	public void setBzdbfw(String bzdbfw) {
		this.bzdbfw = bzdbfw;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column T_NB_DWDB.HCRW_ID
	 * @return  the value of T_NB_DWDB.HCRW_ID
	 * @mbggenerated  Tue May 31 10:35:29 CST 2016
	 */
	public String getHcrwId() {
		return hcrwId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column T_NB_DWDB.HCRW_ID
	 * @param hcrwId  the value for T_NB_DWDB.HCRW_ID
	 * @mbggenerated  Tue May 31 10:35:29 CST 2016
	 */
	public void setHcrwId(String hcrwId) {
		this.hcrwId = hcrwId;
	}
}