package com.kysoft.cpsi.audit.entity;

public class Investment {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column T_NB_DWTZ.ID
	 * @mbg.generated  Mon Jan 09 11:26:18 CST 2017
	 */
	private String id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column T_NB_DWTZ.ND
	 * @mbg.generated  Mon Jan 09 11:26:18 CST 2017
	 */
	private Integer nd;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column T_NB_DWTZ.XYDM
	 * @mbg.generated  Mon Jan 09 11:26:18 CST 2017
	 */
	private String xydm;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column T_NB_DWTZ.TZQYMC
	 * @mbg.generated  Mon Jan 09 11:26:18 CST 2017
	 */
	private String tzqymc;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column T_NB_DWTZ.TZQY_ZCH
	 * @mbg.generated  Mon Jan 09 11:26:18 CST 2017
	 */
	private String tzqyZch;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column T_NB_DWTZ.ID
	 * @return  the value of T_NB_DWTZ.ID
	 * @mbg.generated  Mon Jan 09 11:26:18 CST 2017
	 */
	public String getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column T_NB_DWTZ.ID
	 * @param id  the value for T_NB_DWTZ.ID
	 * @mbg.generated  Mon Jan 09 11:26:18 CST 2017
	 */
	public void setId(String id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column T_NB_DWTZ.ND
	 * @return  the value of T_NB_DWTZ.ND
	 * @mbg.generated  Mon Jan 09 11:26:18 CST 2017
	 */
	public Integer getNd() {
		return nd;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column T_NB_DWTZ.ND
	 * @param nd  the value for T_NB_DWTZ.ND
	 * @mbg.generated  Mon Jan 09 11:26:18 CST 2017
	 */
	public void setNd(Integer nd) {
		this.nd = nd;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column T_NB_DWTZ.XYDM
	 * @return  the value of T_NB_DWTZ.XYDM
	 * @mbg.generated  Mon Jan 09 11:26:18 CST 2017
	 */
	public String getXydm() {
		return xydm;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column T_NB_DWTZ.XYDM
	 * @param xydm  the value for T_NB_DWTZ.XYDM
	 * @mbg.generated  Mon Jan 09 11:26:18 CST 2017
	 */
	public void setXydm(String xydm) {
		this.xydm = xydm;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column T_NB_DWTZ.TZQYMC
	 * @return  the value of T_NB_DWTZ.TZQYMC
	 * @mbg.generated  Mon Jan 09 11:26:18 CST 2017
	 */
	public String getTzqymc() {
		return tzqymc;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column T_NB_DWTZ.TZQYMC
	 * @param tzqymc  the value for T_NB_DWTZ.TZQYMC
	 * @mbg.generated  Mon Jan 09 11:26:18 CST 2017
	 */
	public void setTzqymc(String tzqymc) {
		this.tzqymc = tzqymc;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column T_NB_DWTZ.TZQY_ZCH
	 * @return  the value of T_NB_DWTZ.TZQY_ZCH
	 * @mbg.generated  Mon Jan 09 11:26:18 CST 2017
	 */
	public String getTzqyZch() {
		return tzqyZch;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column T_NB_DWTZ.TZQY_ZCH
	 * @param tzqyZch  the value for T_NB_DWTZ.TZQY_ZCH
	 * @mbg.generated  Mon Jan 09 11:26:18 CST 2017
	 */
	public void setTzqyZch(String tzqyZch) {
		this.tzqyZch = tzqyZch;
	}
}