package com.kysoft.cpsi.audit.entity;

import java.util.Date;

public class JsGqbgKey {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column T_JS_GQBG.XYDM
	 * @mbg.generated  Mon Jan 09 11:29:39 CST 2017
	 */
	private String xydm;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column T_JS_GQBG.GD
	 * @mbg.generated  Mon Jan 09 11:29:39 CST 2017
	 */
	private String gd;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column T_JS_GQBG.BGRQ
	 * @mbg.generated  Mon Jan 09 11:29:39 CST 2017
	 */
	private Date bgrq;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column T_JS_GQBG.XYDM
	 * @return  the value of T_JS_GQBG.XYDM
	 * @mbg.generated  Mon Jan 09 11:29:39 CST 2017
	 */
	public String getXydm() {
		return xydm;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column T_JS_GQBG.XYDM
	 * @param xydm  the value for T_JS_GQBG.XYDM
	 * @mbg.generated  Mon Jan 09 11:29:39 CST 2017
	 */
	public void setXydm(String xydm) {
		this.xydm = xydm;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column T_JS_GQBG.GD
	 * @return  the value of T_JS_GQBG.GD
	 * @mbg.generated  Mon Jan 09 11:29:39 CST 2017
	 */
	public String getGd() {
		return gd;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column T_JS_GQBG.GD
	 * @param gd  the value for T_JS_GQBG.GD
	 * @mbg.generated  Mon Jan 09 11:29:39 CST 2017
	 */
	public void setGd(String gd) {
		this.gd = gd;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column T_JS_GQBG.BGRQ
	 * @return  the value of T_JS_GQBG.BGRQ
	 * @mbg.generated  Mon Jan 09 11:29:39 CST 2017
	 */
	public Date getBgrq() {
		return bgrq;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column T_JS_GQBG.BGRQ
	 * @param bgrq  the value for T_JS_GQBG.BGRQ
	 * @mbg.generated  Mon Jan 09 11:29:39 CST 2017
	 */
	public void setBgrq(Date bgrq) {
		this.bgrq = bgrq;
	}
}