package com.kysoft.cpsi.audit.entity;

import java.util.Date;

public class JsLicense extends JsLicenseKey {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column T_JS_XZXK.YXQ_KS
	 * @mbg.generated  Mon Jan 09 11:29:39 CST 2017
	 */
	private Date yxqKs;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column T_JS_XZXK.YXQ_JS
	 * @mbg.generated  Mon Jan 09 11:29:39 CST 2017
	 */
	private Date yxqJs;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column T_JS_XZXK.XKWJMC
	 * @mbg.generated  Mon Jan 09 11:29:39 CST 2017
	 */
	private String xkwjmc;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column T_JS_XZXK.XKJG
	 * @mbg.generated  Mon Jan 09 11:29:39 CST 2017
	 */
	private String xkjg;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column T_JS_XZXK.XKNR
	 * @mbg.generated  Mon Jan 09 11:29:39 CST 2017
	 */
	private String xknr;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column T_JS_XZXK.ZT
	 * @mbg.generated  Mon Jan 09 11:29:39 CST 2017
	 */
	private String zt;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column T_JS_XZXK.GSSJ
	 * @mbg.generated  Mon Jan 09 11:29:39 CST 2017
	 */
	private Date gssj;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column T_JS_XZXK.XQ
	 * @mbg.generated  Mon Jan 09 11:29:39 CST 2017
	 */
	private String xq;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column T_JS_XZXK.HDRQ
	 * @mbg.generated  Mon Jan 09 11:29:39 CST 2017
	 */
	private Date hdrq;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column T_JS_XZXK.ID
	 * @mbg.generated  Mon Jan 09 11:29:39 CST 2017
	 */
	private String id;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column T_JS_XZXK.YXQ_KS
	 * @return  the value of T_JS_XZXK.YXQ_KS
	 * @mbg.generated  Mon Jan 09 11:29:39 CST 2017
	 */
	public Date getYxqKs() {
		return yxqKs;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column T_JS_XZXK.YXQ_KS
	 * @param yxqKs  the value for T_JS_XZXK.YXQ_KS
	 * @mbg.generated  Mon Jan 09 11:29:39 CST 2017
	 */
	public void setYxqKs(Date yxqKs) {
		this.yxqKs = yxqKs;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column T_JS_XZXK.YXQ_JS
	 * @return  the value of T_JS_XZXK.YXQ_JS
	 * @mbg.generated  Mon Jan 09 11:29:39 CST 2017
	 */
	public Date getYxqJs() {
		return yxqJs;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column T_JS_XZXK.YXQ_JS
	 * @param yxqJs  the value for T_JS_XZXK.YXQ_JS
	 * @mbg.generated  Mon Jan 09 11:29:39 CST 2017
	 */
	public void setYxqJs(Date yxqJs) {
		this.yxqJs = yxqJs;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column T_JS_XZXK.XKWJMC
	 * @return  the value of T_JS_XZXK.XKWJMC
	 * @mbg.generated  Mon Jan 09 11:29:39 CST 2017
	 */
	public String getXkwjmc() {
		return xkwjmc;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column T_JS_XZXK.XKWJMC
	 * @param xkwjmc  the value for T_JS_XZXK.XKWJMC
	 * @mbg.generated  Mon Jan 09 11:29:39 CST 2017
	 */
	public void setXkwjmc(String xkwjmc) {
		this.xkwjmc = xkwjmc;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column T_JS_XZXK.XKJG
	 * @return  the value of T_JS_XZXK.XKJG
	 * @mbg.generated  Mon Jan 09 11:29:39 CST 2017
	 */
	public String getXkjg() {
		return xkjg;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column T_JS_XZXK.XKJG
	 * @param xkjg  the value for T_JS_XZXK.XKJG
	 * @mbg.generated  Mon Jan 09 11:29:39 CST 2017
	 */
	public void setXkjg(String xkjg) {
		this.xkjg = xkjg;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column T_JS_XZXK.XKNR
	 * @return  the value of T_JS_XZXK.XKNR
	 * @mbg.generated  Mon Jan 09 11:29:39 CST 2017
	 */
	public String getXknr() {
		return xknr;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column T_JS_XZXK.XKNR
	 * @param xknr  the value for T_JS_XZXK.XKNR
	 * @mbg.generated  Mon Jan 09 11:29:39 CST 2017
	 */
	public void setXknr(String xknr) {
		this.xknr = xknr;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column T_JS_XZXK.ZT
	 * @return  the value of T_JS_XZXK.ZT
	 * @mbg.generated  Mon Jan 09 11:29:39 CST 2017
	 */
	public String getZt() {
		return zt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column T_JS_XZXK.ZT
	 * @param zt  the value for T_JS_XZXK.ZT
	 * @mbg.generated  Mon Jan 09 11:29:39 CST 2017
	 */
	public void setZt(String zt) {
		this.zt = zt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column T_JS_XZXK.GSSJ
	 * @return  the value of T_JS_XZXK.GSSJ
	 * @mbg.generated  Mon Jan 09 11:29:39 CST 2017
	 */
	public Date getGssj() {
		return gssj;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column T_JS_XZXK.GSSJ
	 * @param gssj  the value for T_JS_XZXK.GSSJ
	 * @mbg.generated  Mon Jan 09 11:29:39 CST 2017
	 */
	public void setGssj(Date gssj) {
		this.gssj = gssj;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column T_JS_XZXK.XQ
	 * @return  the value of T_JS_XZXK.XQ
	 * @mbg.generated  Mon Jan 09 11:29:39 CST 2017
	 */
	public String getXq() {
		return xq;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column T_JS_XZXK.XQ
	 * @param xq  the value for T_JS_XZXK.XQ
	 * @mbg.generated  Mon Jan 09 11:29:39 CST 2017
	 */
	public void setXq(String xq) {
		this.xq = xq;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column T_JS_XZXK.HDRQ
	 * @return  the value of T_JS_XZXK.HDRQ
	 * @mbg.generated  Mon Jan 09 11:29:39 CST 2017
	 */
	public Date getHdrq() {
		return hdrq;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column T_JS_XZXK.HDRQ
	 * @param hdrq  the value for T_JS_XZXK.HDRQ
	 * @mbg.generated  Mon Jan 09 11:29:39 CST 2017
	 */
	public void setHdrq(Date hdrq) {
		this.hdrq = hdrq;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column T_JS_XZXK.ID
	 * @return  the value of T_JS_XZXK.ID
	 * @mbg.generated  Mon Jan 09 11:29:39 CST 2017
	 */
	public String getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column T_JS_XZXK.ID
	 * @param id  the value for T_JS_XZXK.ID
	 * @mbg.generated  Mon Jan 09 11:29:39 CST 2017
	 */
	public void setId(String id) {
		this.id = id;
	}
}