package com.kysoft.cpsi.audit.entity;

import java.math.BigDecimal;
import java.util.Date;

public class JsStockholderContribution extends JsStockholderContributionKey {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column T_JS_GDCZ.RJE
	 * @mbggenerated  Thu Aug 11 14:58:43 CST 2016
	 */
	private BigDecimal rje;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column T_JS_GDCZ.SJE
	 * @mbggenerated  Thu Aug 11 14:58:43 CST 2016
	 */
	private BigDecimal sje;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column T_JS_GDCZ.GSSJ
	 * @mbggenerated  Thu Aug 11 14:58:43 CST 2016
	 */
	private Date gssj;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column T_JS_GDCZ.RJCZFS
	 * @mbggenerated  Thu Aug 11 14:58:43 CST 2016
	 */
	private String rjczfs;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column T_JS_GDCZ.RJCZE
	 * @mbggenerated  Thu Aug 11 14:58:43 CST 2016
	 */
	private Float rjcze;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column T_JS_GDCZ.RJCZRQ
	 * @mbggenerated  Thu Aug 11 14:58:43 CST 2016
	 */
	private Date rjczrq;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column T_JS_GDCZ.SJCZFS
	 * @mbggenerated  Thu Aug 11 14:58:43 CST 2016
	 */
	private String sjczfs;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column T_JS_GDCZ.SJCZE
	 * @mbggenerated  Thu Aug 11 14:58:43 CST 2016
	 */
	private Float sjcze;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column T_JS_GDCZ.SJCZRQ
	 * @mbggenerated  Thu Aug 11 14:58:43 CST 2016
	 */
	private Date sjczrq;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column T_JS_GDCZ.HCRW_ID
	 * @mbggenerated  Thu Aug 11 14:58:43 CST 2016
	 */
	private String hcrwId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column T_JS_GDCZ.ID
	 * @mbggenerated  Thu Aug 11 14:58:43 CST 2016
	 */
	private String id;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column T_JS_GDCZ.RJE
	 * @return  the value of T_JS_GDCZ.RJE
	 * @mbggenerated  Thu Aug 11 14:58:43 CST 2016
	 */
	public BigDecimal getRje() {
		return rje;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column T_JS_GDCZ.RJE
	 * @param rje  the value for T_JS_GDCZ.RJE
	 * @mbggenerated  Thu Aug 11 14:58:43 CST 2016
	 */
	public void setRje(BigDecimal rje) {
		this.rje = rje;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column T_JS_GDCZ.SJE
	 * @return  the value of T_JS_GDCZ.SJE
	 * @mbggenerated  Thu Aug 11 14:58:43 CST 2016
	 */
	public BigDecimal getSje() {
		return sje;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column T_JS_GDCZ.SJE
	 * @param sje  the value for T_JS_GDCZ.SJE
	 * @mbggenerated  Thu Aug 11 14:58:43 CST 2016
	 */
	public void setSje(BigDecimal sje) {
		this.sje = sje;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column T_JS_GDCZ.GSSJ
	 * @return  the value of T_JS_GDCZ.GSSJ
	 * @mbggenerated  Thu Aug 11 14:58:43 CST 2016
	 */
	public Date getGssj() {
		return gssj;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column T_JS_GDCZ.GSSJ
	 * @param gssj  the value for T_JS_GDCZ.GSSJ
	 * @mbggenerated  Thu Aug 11 14:58:43 CST 2016
	 */
	public void setGssj(Date gssj) {
		this.gssj = gssj;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column T_JS_GDCZ.RJCZFS
	 * @return  the value of T_JS_GDCZ.RJCZFS
	 * @mbggenerated  Thu Aug 11 14:58:43 CST 2016
	 */
	public String getRjczfs() {
		return rjczfs;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column T_JS_GDCZ.RJCZFS
	 * @param rjczfs  the value for T_JS_GDCZ.RJCZFS
	 * @mbggenerated  Thu Aug 11 14:58:43 CST 2016
	 */
	public void setRjczfs(String rjczfs) {
		this.rjczfs = rjczfs;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column T_JS_GDCZ.RJCZE
	 * @return  the value of T_JS_GDCZ.RJCZE
	 * @mbggenerated  Thu Aug 11 14:58:43 CST 2016
	 */
	public Float getRjcze() {
		return rjcze;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column T_JS_GDCZ.RJCZE
	 * @param rjcze  the value for T_JS_GDCZ.RJCZE
	 * @mbggenerated  Thu Aug 11 14:58:43 CST 2016
	 */
	public void setRjcze(Float rjcze) {
		this.rjcze = rjcze;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column T_JS_GDCZ.RJCZRQ
	 * @return  the value of T_JS_GDCZ.RJCZRQ
	 * @mbggenerated  Thu Aug 11 14:58:43 CST 2016
	 */
	public Date getRjczrq() {
		return rjczrq;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column T_JS_GDCZ.RJCZRQ
	 * @param rjczrq  the value for T_JS_GDCZ.RJCZRQ
	 * @mbggenerated  Thu Aug 11 14:58:43 CST 2016
	 */
	public void setRjczrq(Date rjczrq) {
		this.rjczrq = rjczrq;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column T_JS_GDCZ.SJCZFS
	 * @return  the value of T_JS_GDCZ.SJCZFS
	 * @mbggenerated  Thu Aug 11 14:58:43 CST 2016
	 */
	public String getSjczfs() {
		return sjczfs;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column T_JS_GDCZ.SJCZFS
	 * @param sjczfs  the value for T_JS_GDCZ.SJCZFS
	 * @mbggenerated  Thu Aug 11 14:58:43 CST 2016
	 */
	public void setSjczfs(String sjczfs) {
		this.sjczfs = sjczfs;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column T_JS_GDCZ.SJCZE
	 * @return  the value of T_JS_GDCZ.SJCZE
	 * @mbggenerated  Thu Aug 11 14:58:43 CST 2016
	 */
	public Float getSjcze() {
		return sjcze;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column T_JS_GDCZ.SJCZE
	 * @param sjcze  the value for T_JS_GDCZ.SJCZE
	 * @mbggenerated  Thu Aug 11 14:58:43 CST 2016
	 */
	public void setSjcze(Float sjcze) {
		this.sjcze = sjcze;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column T_JS_GDCZ.SJCZRQ
	 * @return  the value of T_JS_GDCZ.SJCZRQ
	 * @mbggenerated  Thu Aug 11 14:58:43 CST 2016
	 */
	public Date getSjczrq() {
		return sjczrq;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column T_JS_GDCZ.SJCZRQ
	 * @param sjczrq  the value for T_JS_GDCZ.SJCZRQ
	 * @mbggenerated  Thu Aug 11 14:58:43 CST 2016
	 */
	public void setSjczrq(Date sjczrq) {
		this.sjczrq = sjczrq;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column T_JS_GDCZ.HCRW_ID
	 * @return  the value of T_JS_GDCZ.HCRW_ID
	 * @mbggenerated  Thu Aug 11 14:58:43 CST 2016
	 */
	public String getHcrwId() {
		return hcrwId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column T_JS_GDCZ.HCRW_ID
	 * @param hcrwId  the value for T_JS_GDCZ.HCRW_ID
	 * @mbggenerated  Thu Aug 11 14:58:43 CST 2016
	 */
	public void setHcrwId(String hcrwId) {
		this.hcrwId = hcrwId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column T_JS_GDCZ.ID
	 * @return  the value of T_JS_GDCZ.ID
	 * @mbggenerated  Thu Aug 11 14:58:43 CST 2016
	 */
	public String getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column T_JS_GDCZ.ID
	 * @param id  the value for T_JS_GDCZ.ID
	 * @mbggenerated  Thu Aug 11 14:58:43 CST 2016
	 */
	public void setId(String id) {
		this.id = id;
	}
}