package com.kysoft.cpsi.audit.entity;

public class JsZscqKey {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column T_JS_ZSCQ.XYDM
	 * @mbg.generated  Mon Jan 09 11:29:39 CST 2017
	 */
	private String xydm;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column T_JS_ZSCQ.CZRMC
	 * @mbg.generated  Mon Jan 09 11:29:39 CST 2017
	 */
	private String czrmc;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column T_JS_ZSCQ.ZL
	 * @mbg.generated  Mon Jan 09 11:29:39 CST 2017
	 */
	private String zl;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column T_JS_ZSCQ.XYDM
	 * @return  the value of T_JS_ZSCQ.XYDM
	 * @mbg.generated  Mon Jan 09 11:29:39 CST 2017
	 */
	public String getXydm() {
		return xydm;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column T_JS_ZSCQ.XYDM
	 * @param xydm  the value for T_JS_ZSCQ.XYDM
	 * @mbg.generated  Mon Jan 09 11:29:39 CST 2017
	 */
	public void setXydm(String xydm) {
		this.xydm = xydm;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column T_JS_ZSCQ.CZRMC
	 * @return  the value of T_JS_ZSCQ.CZRMC
	 * @mbg.generated  Mon Jan 09 11:29:39 CST 2017
	 */
	public String getCzrmc() {
		return czrmc;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column T_JS_ZSCQ.CZRMC
	 * @param czrmc  the value for T_JS_ZSCQ.CZRMC
	 * @mbg.generated  Mon Jan 09 11:29:39 CST 2017
	 */
	public void setCzrmc(String czrmc) {
		this.czrmc = czrmc;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column T_JS_ZSCQ.ZL
	 * @return  the value of T_JS_ZSCQ.ZL
	 * @mbg.generated  Mon Jan 09 11:29:39 CST 2017
	 */
	public String getZl() {
		return zl;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column T_JS_ZSCQ.ZL
	 * @param zl  the value for T_JS_ZSCQ.ZL
	 * @mbg.generated  Mon Jan 09 11:29:39 CST 2017
	 */
	public void setZl(String zl) {
		this.zl = zl;
	}
}