package com.kysoft.cpsi.audit.entity;

public class License {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column T_NB_XZXK.ID
	 * @mbggenerated  Sat Jun 25 10:35:58 CST 2016
	 */
	private String id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column T_NB_XZXK.ND
	 * @mbggenerated  Sat Jun 25 10:35:58 CST 2016
	 */
	private Integer nd;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column T_NB_XZXK.XYDM
	 * @mbggenerated  Sat Jun 25 10:35:58 CST 2016
	 */
	private String xydm;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column T_NB_XZXK.XKWJMC
	 * @mbggenerated  Sat Jun 25 10:35:58 CST 2016
	 */
	private String xkwjmc;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column T_NB_XZXK.YXQ
	 * @mbggenerated  Sat Jun 25 10:35:58 CST 2016
	 */
	private String yxq;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column T_NB_XZXK.HCRW_ID
	 * @mbggenerated  Sat Jun 25 10:35:58 CST 2016
	 */
	private String hcrwId;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column T_NB_XZXK.ID
	 * @return  the value of T_NB_XZXK.ID
	 * @mbggenerated  Sat Jun 25 10:35:58 CST 2016
	 */
	public String getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column T_NB_XZXK.ID
	 * @param id  the value for T_NB_XZXK.ID
	 * @mbggenerated  Sat Jun 25 10:35:58 CST 2016
	 */
	public void setId(String id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column T_NB_XZXK.ND
	 * @return  the value of T_NB_XZXK.ND
	 * @mbggenerated  Sat Jun 25 10:35:58 CST 2016
	 */
	public Integer getNd() {
		return nd;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column T_NB_XZXK.ND
	 * @param nd  the value for T_NB_XZXK.ND
	 * @mbggenerated  Sat Jun 25 10:35:58 CST 2016
	 */
	public void setNd(Integer nd) {
		this.nd = nd;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column T_NB_XZXK.XYDM
	 * @return  the value of T_NB_XZXK.XYDM
	 * @mbggenerated  Sat Jun 25 10:35:58 CST 2016
	 */
	public String getXydm() {
		return xydm;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column T_NB_XZXK.XYDM
	 * @param xydm  the value for T_NB_XZXK.XYDM
	 * @mbggenerated  Sat Jun 25 10:35:58 CST 2016
	 */
	public void setXydm(String xydm) {
		this.xydm = xydm;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column T_NB_XZXK.XKWJMC
	 * @return  the value of T_NB_XZXK.XKWJMC
	 * @mbggenerated  Sat Jun 25 10:35:58 CST 2016
	 */
	public String getXkwjmc() {
		return xkwjmc;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column T_NB_XZXK.XKWJMC
	 * @param xkwjmc  the value for T_NB_XZXK.XKWJMC
	 * @mbggenerated  Sat Jun 25 10:35:58 CST 2016
	 */
	public void setXkwjmc(String xkwjmc) {
		this.xkwjmc = xkwjmc;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column T_NB_XZXK.YXQ
	 * @return  the value of T_NB_XZXK.YXQ
	 * @mbggenerated  Sat Jun 25 10:35:58 CST 2016
	 */
	public String getYxq() {
		return yxq;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column T_NB_XZXK.YXQ
	 * @param yxq  the value for T_NB_XZXK.YXQ
	 * @mbggenerated  Sat Jun 25 10:35:58 CST 2016
	 */
	public void setYxq(String yxq) {
		this.yxq = yxq;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column T_NB_XZXK.HCRW_ID
	 * @return  the value of T_NB_XZXK.HCRW_ID
	 * @mbggenerated  Sat Jun 25 10:35:58 CST 2016
	 */
	public String getHcrwId() {
		return hcrwId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column T_NB_XZXK.HCRW_ID
	 * @param hcrwId  the value for T_NB_XZXK.HCRW_ID
	 * @mbggenerated  Sat Jun 25 10:35:58 CST 2016
	 */
	public void setHcrwId(String hcrwId) {
		this.hcrwId = hcrwId;
	}
}