package com.kysoft.cpsi.task.entity;

import java.util.Date;

public class Hcclmx {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column T_HCCLMX.ID
	 * @mbggenerated  Thu May 26 21:29:52 CST 2016
	 */
	private String id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column T_HCCLMX.HCDW_XYDM
	 * @mbggenerated  Thu May 26 21:29:52 CST 2016
	 */
	private String hcdwXydm;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column T_HCCLMX.HCJHND
	 * @mbggenerated  Thu May 26 21:29:52 CST 2016
	 */
	private Integer hcjhnd;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column T_HCCLMX.NAME
	 * @mbggenerated  Thu May 26 21:29:52 CST 2016
	 */
	private String name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column T_HCCLMX.SFBYX
	 * @mbggenerated  Thu May 26 21:29:52 CST 2016
	 */
	private Integer sfbyx;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column T_HCCLMX.WJLX
	 * @mbggenerated  Thu May 26 21:29:52 CST 2016
	 */
	private Integer wjlx;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column T_HCCLMX.HCCL_ID
	 * @mbggenerated  Thu May 26 21:29:52 CST 2016
	 */
	private String hcclId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column T_HCCLMX.HCSX_ID
	 * @mbggenerated  Thu May 26 21:29:52 CST 2016
	 */
	private String hcsxId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column T_HCCLMX.HCRW_ID
	 * @mbggenerated  Thu May 26 21:29:52 CST 2016
	 */
	private String hcrwId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column T_HCCLMX.MONGOID
	 * @mbggenerated  Thu May 26 21:29:52 CST 2016
	 */
	private String mongoid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column T_HCCLMX.YHTG
	 * @mbggenerated  Thu May 26 21:29:52 CST 2016
	 */
	private Integer yhtg;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column T_HCCLMX.LY
	 * @mbggenerated  Thu May 26 21:29:52 CST 2016
	 */
	private Integer ly;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column T_HCCLMX.HCSXMC
	 * @mbggenerated  Thu May 26 21:29:52 CST 2016
	 */
	private String hcsxmc;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column T_HCCLMX.UPLOAD_TIME
	 * @mbggenerated  Thu May 26 21:29:52 CST 2016
	 */
	private Date uploadTime;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column T_HCCLMX.ID
	 * @return  the value of T_HCCLMX.ID
	 * @mbggenerated  Thu May 26 21:29:52 CST 2016
	 */
	public String getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column T_HCCLMX.ID
	 * @param id  the value for T_HCCLMX.ID
	 * @mbggenerated  Thu May 26 21:29:52 CST 2016
	 */
	public void setId(String id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column T_HCCLMX.HCDW_XYDM
	 * @return  the value of T_HCCLMX.HCDW_XYDM
	 * @mbggenerated  Thu May 26 21:29:52 CST 2016
	 */
	public String getHcdwXydm() {
		return hcdwXydm;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column T_HCCLMX.HCDW_XYDM
	 * @param hcdwXydm  the value for T_HCCLMX.HCDW_XYDM
	 * @mbggenerated  Thu May 26 21:29:52 CST 2016
	 */
	public void setHcdwXydm(String hcdwXydm) {
		this.hcdwXydm = hcdwXydm;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column T_HCCLMX.HCJHND
	 * @return  the value of T_HCCLMX.HCJHND
	 * @mbggenerated  Thu May 26 21:29:52 CST 2016
	 */
	public Integer getHcjhnd() {
		return hcjhnd;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column T_HCCLMX.HCJHND
	 * @param hcjhnd  the value for T_HCCLMX.HCJHND
	 * @mbggenerated  Thu May 26 21:29:52 CST 2016
	 */
	public void setHcjhnd(Integer hcjhnd) {
		this.hcjhnd = hcjhnd;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column T_HCCLMX.NAME
	 * @return  the value of T_HCCLMX.NAME
	 * @mbggenerated  Thu May 26 21:29:52 CST 2016
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column T_HCCLMX.NAME
	 * @param name  the value for T_HCCLMX.NAME
	 * @mbggenerated  Thu May 26 21:29:52 CST 2016
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column T_HCCLMX.SFBYX
	 * @return  the value of T_HCCLMX.SFBYX
	 * @mbggenerated  Thu May 26 21:29:52 CST 2016
	 */
	public Integer getSfbyx() {
		return sfbyx;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column T_HCCLMX.SFBYX
	 * @param sfbyx  the value for T_HCCLMX.SFBYX
	 * @mbggenerated  Thu May 26 21:29:52 CST 2016
	 */
	public void setSfbyx(Integer sfbyx) {
		this.sfbyx = sfbyx;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column T_HCCLMX.WJLX
	 * @return  the value of T_HCCLMX.WJLX
	 * @mbggenerated  Thu May 26 21:29:52 CST 2016
	 */
	public Integer getWjlx() {
		return wjlx;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column T_HCCLMX.WJLX
	 * @param wjlx  the value for T_HCCLMX.WJLX
	 * @mbggenerated  Thu May 26 21:29:52 CST 2016
	 */
	public void setWjlx(Integer wjlx) {
		this.wjlx = wjlx;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column T_HCCLMX.HCCL_ID
	 * @return  the value of T_HCCLMX.HCCL_ID
	 * @mbggenerated  Thu May 26 21:29:52 CST 2016
	 */
	public String getHcclId() {
		return hcclId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column T_HCCLMX.HCCL_ID
	 * @param hcclId  the value for T_HCCLMX.HCCL_ID
	 * @mbggenerated  Thu May 26 21:29:52 CST 2016
	 */
	public void setHcclId(String hcclId) {
		this.hcclId = hcclId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column T_HCCLMX.HCSX_ID
	 * @return  the value of T_HCCLMX.HCSX_ID
	 * @mbggenerated  Thu May 26 21:29:52 CST 2016
	 */
	public String getHcsxId() {
		return hcsxId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column T_HCCLMX.HCSX_ID
	 * @param hcsxId  the value for T_HCCLMX.HCSX_ID
	 * @mbggenerated  Thu May 26 21:29:52 CST 2016
	 */
	public void setHcsxId(String hcsxId) {
		this.hcsxId = hcsxId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column T_HCCLMX.HCRW_ID
	 * @return  the value of T_HCCLMX.HCRW_ID
	 * @mbggenerated  Thu May 26 21:29:52 CST 2016
	 */
	public String getHcrwId() {
		return hcrwId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column T_HCCLMX.HCRW_ID
	 * @param hcrwId  the value for T_HCCLMX.HCRW_ID
	 * @mbggenerated  Thu May 26 21:29:52 CST 2016
	 */
	public void setHcrwId(String hcrwId) {
		this.hcrwId = hcrwId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column T_HCCLMX.MONGOID
	 * @return  the value of T_HCCLMX.MONGOID
	 * @mbggenerated  Thu May 26 21:29:52 CST 2016
	 */
	public String getMongoid() {
		return mongoid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column T_HCCLMX.MONGOID
	 * @param mongoid  the value for T_HCCLMX.MONGOID
	 * @mbggenerated  Thu May 26 21:29:52 CST 2016
	 */
	public void setMongoid(String mongoid) {
		this.mongoid = mongoid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column T_HCCLMX.YHTG
	 * @return  the value of T_HCCLMX.YHTG
	 * @mbggenerated  Thu May 26 21:29:52 CST 2016
	 */
	public Integer getYhtg() {
		return yhtg;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column T_HCCLMX.YHTG
	 * @param yhtg  the value for T_HCCLMX.YHTG
	 * @mbggenerated  Thu May 26 21:29:52 CST 2016
	 */
	public void setYhtg(Integer yhtg) {
		this.yhtg = yhtg;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column T_HCCLMX.LY
	 * @return  the value of T_HCCLMX.LY
	 * @mbggenerated  Thu May 26 21:29:52 CST 2016
	 */
	public Integer getLy() {
		return ly;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column T_HCCLMX.LY
	 * @param ly  the value for T_HCCLMX.LY
	 * @mbggenerated  Thu May 26 21:29:52 CST 2016
	 */
	public void setLy(Integer ly) {
		this.ly = ly;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column T_HCCLMX.HCSXMC
	 * @return  the value of T_HCCLMX.HCSXMC
	 * @mbggenerated  Thu May 26 21:29:52 CST 2016
	 */
	public String getHcsxmc() {
		return hcsxmc;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column T_HCCLMX.HCSXMC
	 * @param hcsxmc  the value for T_HCCLMX.HCSXMC
	 * @mbggenerated  Thu May 26 21:29:52 CST 2016
	 */
	public void setHcsxmc(String hcsxmc) {
		this.hcsxmc = hcsxmc;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column T_HCCLMX.UPLOAD_TIME
	 * @return  the value of T_HCCLMX.UPLOAD_TIME
	 * @mbggenerated  Thu May 26 21:29:52 CST 2016
	 */
	public Date getUploadTime() {
		return uploadTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column T_HCCLMX.UPLOAD_TIME
	 * @param uploadTime  the value for T_HCCLMX.UPLOAD_TIME
	 * @mbggenerated  Thu May 26 21:29:52 CST 2016
	 */
	public void setUploadTime(Date uploadTime) {
		this.uploadTime = uploadTime;
	}
}