package com.kysoft.cpsi.task.entity;

import java.util.Date;

public class Hcjh {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column T_HCJH.ID
	 * @mbggenerated  Mon Jun 13 13:09:37 CST 2016
	 */
	private String id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column T_HCJH.ND
	 * @mbggenerated  Mon Jun 13 13:09:37 CST 2016
	 */
	private Integer nd;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column T_HCJH.JHMC
	 * @mbggenerated  Mon Jun 13 13:09:37 CST 2016
	 */
	private String jhmc;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column T_HCJH.GSJHBH
	 * @mbggenerated  Mon Jun 13 13:09:37 CST 2016
	 */
	private String gsjhbh;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column T_HCJH.FL
	 * @mbggenerated  Mon Jun 13 13:09:37 CST 2016
	 */
	private Integer fl;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column T_HCJH.XDRQ
	 * @mbggenerated  Mon Jun 13 13:09:37 CST 2016
	 */
	private Date xdrq;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column T_HCJH.YQWCSJ
	 * @mbggenerated  Mon Jun 13 13:09:37 CST 2016
	 */
	private Date yqwcsj;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column T_HCJH.HCRWSL
	 * @mbggenerated  Mon Jun 13 13:09:37 CST 2016
	 */
	private Integer hcrwsl;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column T_HCJH.YPFSL
	 * @mbggenerated  Mon Jun 13 13:09:37 CST 2016
	 */
	private Integer ypfsl;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column T_HCJH.YRLSL
	 * @mbggenerated  Mon Jun 13 13:09:37 CST 2016
	 */
	private Integer yrlsl;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column T_HCJH.WRLSL
	 * @mbggenerated  Mon Jun 13 13:09:37 CST 2016
	 */
	private Integer wrlsl;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column T_HCJH.SHR
	 * @mbggenerated  Mon Jun 13 13:09:37 CST 2016
	 */
	private String shr;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column T_HCJH.SHZT
	 * @mbggenerated  Mon Jun 13 13:09:37 CST 2016
	 */
	private Integer shzt;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column T_HCJH.XDR
	 * @mbggenerated  Mon Jun 13 13:09:37 CST 2016
	 */
	private String xdr;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column T_HCJH.SM
	 * @mbggenerated  Mon Jun 13 13:09:37 CST 2016
	 */
	private String sm;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column T_HCJH.NR
	 * @mbggenerated  Mon Jun 13 13:09:37 CST 2016
	 */
	private Integer nr;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column T_HCJH.XDRMC
	 * @mbggenerated  Mon Jun 13 13:09:37 CST 2016
	 */
	private String xdrmc;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column T_HCJH.SHRMC
	 * @mbggenerated  Mon Jun 13 13:09:37 CST 2016
	 */
	private String shrmc;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column T_HCJH.JHBH
	 * @mbggenerated  Mon Jun 13 13:09:37 CST 2016
	 */
	private String jhbh;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column T_HCJH.CXWH
	 * @mbggenerated  Mon Jun 13 13:09:37 CST 2016
	 */
	private String cxwh;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column T_HCJH.KSRQ
	 * @mbggenerated  Mon Jun 13 13:09:37 CST 2016
	 */
	private Date ksrq;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column T_HCJH.CLQSR
	 * @mbggenerated  Mon Jun 13 13:09:37 CST 2016
	 */
	private Date clqsr;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column T_HCJH.CLZZR
	 * @mbggenerated  Mon Jun 13 13:09:37 CST 2016
	 */
	private Date clzzr;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column T_HCJH.ID
	 * @return  the value of T_HCJH.ID
	 * @mbggenerated  Mon Jun 13 13:09:37 CST 2016
	 */
	public String getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column T_HCJH.ID
	 * @param id  the value for T_HCJH.ID
	 * @mbggenerated  Mon Jun 13 13:09:37 CST 2016
	 */
	public void setId(String id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column T_HCJH.ND
	 * @return  the value of T_HCJH.ND
	 * @mbggenerated  Mon Jun 13 13:09:37 CST 2016
	 */
	public Integer getNd() {
		return nd;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column T_HCJH.ND
	 * @param nd  the value for T_HCJH.ND
	 * @mbggenerated  Mon Jun 13 13:09:37 CST 2016
	 */
	public void setNd(Integer nd) {
		this.nd = nd;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column T_HCJH.JHMC
	 * @return  the value of T_HCJH.JHMC
	 * @mbggenerated  Mon Jun 13 13:09:37 CST 2016
	 */
	public String getJhmc() {
		return jhmc;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column T_HCJH.JHMC
	 * @param jhmc  the value for T_HCJH.JHMC
	 * @mbggenerated  Mon Jun 13 13:09:37 CST 2016
	 */
	public void setJhmc(String jhmc) {
		this.jhmc = jhmc;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column T_HCJH.GSJHBH
	 * @return  the value of T_HCJH.GSJHBH
	 * @mbggenerated  Mon Jun 13 13:09:37 CST 2016
	 */
	public String getGsjhbh() {
		return gsjhbh;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column T_HCJH.GSJHBH
	 * @param gsjhbh  the value for T_HCJH.GSJHBH
	 * @mbggenerated  Mon Jun 13 13:09:37 CST 2016
	 */
	public void setGsjhbh(String gsjhbh) {
		this.gsjhbh = gsjhbh;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column T_HCJH.FL
	 * @return  the value of T_HCJH.FL
	 * @mbggenerated  Mon Jun 13 13:09:37 CST 2016
	 */
	public Integer getFl() {
		return fl;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column T_HCJH.FL
	 * @param fl  the value for T_HCJH.FL
	 * @mbggenerated  Mon Jun 13 13:09:37 CST 2016
	 */
	public void setFl(Integer fl) {
		this.fl = fl;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column T_HCJH.XDRQ
	 * @return  the value of T_HCJH.XDRQ
	 * @mbggenerated  Mon Jun 13 13:09:37 CST 2016
	 */
	public Date getXdrq() {
		return xdrq;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column T_HCJH.XDRQ
	 * @param xdrq  the value for T_HCJH.XDRQ
	 * @mbggenerated  Mon Jun 13 13:09:37 CST 2016
	 */
	public void setXdrq(Date xdrq) {
		this.xdrq = xdrq;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column T_HCJH.YQWCSJ
	 * @return  the value of T_HCJH.YQWCSJ
	 * @mbggenerated  Mon Jun 13 13:09:37 CST 2016
	 */
	public Date getYqwcsj() {
		return yqwcsj;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column T_HCJH.YQWCSJ
	 * @param yqwcsj  the value for T_HCJH.YQWCSJ
	 * @mbggenerated  Mon Jun 13 13:09:37 CST 2016
	 */
	public void setYqwcsj(Date yqwcsj) {
		this.yqwcsj = yqwcsj;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column T_HCJH.HCRWSL
	 * @return  the value of T_HCJH.HCRWSL
	 * @mbggenerated  Mon Jun 13 13:09:37 CST 2016
	 */
	public Integer getHcrwsl() {
		return hcrwsl;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column T_HCJH.HCRWSL
	 * @param hcrwsl  the value for T_HCJH.HCRWSL
	 * @mbggenerated  Mon Jun 13 13:09:37 CST 2016
	 */
	public void setHcrwsl(Integer hcrwsl) {
		this.hcrwsl = hcrwsl;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column T_HCJH.YPFSL
	 * @return  the value of T_HCJH.YPFSL
	 * @mbggenerated  Mon Jun 13 13:09:37 CST 2016
	 */
	public Integer getYpfsl() {
		return ypfsl;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column T_HCJH.YPFSL
	 * @param ypfsl  the value for T_HCJH.YPFSL
	 * @mbggenerated  Mon Jun 13 13:09:37 CST 2016
	 */
	public void setYpfsl(Integer ypfsl) {
		this.ypfsl = ypfsl;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column T_HCJH.YRLSL
	 * @return  the value of T_HCJH.YRLSL
	 * @mbggenerated  Mon Jun 13 13:09:37 CST 2016
	 */
	public Integer getYrlsl() {
		return yrlsl;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column T_HCJH.YRLSL
	 * @param yrlsl  the value for T_HCJH.YRLSL
	 * @mbggenerated  Mon Jun 13 13:09:37 CST 2016
	 */
	public void setYrlsl(Integer yrlsl) {
		this.yrlsl = yrlsl;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column T_HCJH.WRLSL
	 * @return  the value of T_HCJH.WRLSL
	 * @mbggenerated  Mon Jun 13 13:09:37 CST 2016
	 */
	public Integer getWrlsl() {
		return wrlsl;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column T_HCJH.WRLSL
	 * @param wrlsl  the value for T_HCJH.WRLSL
	 * @mbggenerated  Mon Jun 13 13:09:37 CST 2016
	 */
	public void setWrlsl(Integer wrlsl) {
		this.wrlsl = wrlsl;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column T_HCJH.SHR
	 * @return  the value of T_HCJH.SHR
	 * @mbggenerated  Mon Jun 13 13:09:37 CST 2016
	 */
	public String getShr() {
		return shr;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column T_HCJH.SHR
	 * @param shr  the value for T_HCJH.SHR
	 * @mbggenerated  Mon Jun 13 13:09:37 CST 2016
	 */
	public void setShr(String shr) {
		this.shr = shr;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column T_HCJH.SHZT
	 * @return  the value of T_HCJH.SHZT
	 * @mbggenerated  Mon Jun 13 13:09:37 CST 2016
	 */
	public Integer getShzt() {
		return shzt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column T_HCJH.SHZT
	 * @param shzt  the value for T_HCJH.SHZT
	 * @mbggenerated  Mon Jun 13 13:09:37 CST 2016
	 */
	public void setShzt(Integer shzt) {
		this.shzt = shzt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column T_HCJH.XDR
	 * @return  the value of T_HCJH.XDR
	 * @mbggenerated  Mon Jun 13 13:09:37 CST 2016
	 */
	public String getXdr() {
		return xdr;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column T_HCJH.XDR
	 * @param xdr  the value for T_HCJH.XDR
	 * @mbggenerated  Mon Jun 13 13:09:37 CST 2016
	 */
	public void setXdr(String xdr) {
		this.xdr = xdr;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column T_HCJH.SM
	 * @return  the value of T_HCJH.SM
	 * @mbggenerated  Mon Jun 13 13:09:37 CST 2016
	 */
	public String getSm() {
		return sm;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column T_HCJH.SM
	 * @param sm  the value for T_HCJH.SM
	 * @mbggenerated  Mon Jun 13 13:09:37 CST 2016
	 */
	public void setSm(String sm) {
		this.sm = sm;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column T_HCJH.NR
	 * @return  the value of T_HCJH.NR
	 * @mbggenerated  Mon Jun 13 13:09:37 CST 2016
	 */
	public Integer getNr() {
		return nr;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column T_HCJH.NR
	 * @param nr  the value for T_HCJH.NR
	 * @mbggenerated  Mon Jun 13 13:09:37 CST 2016
	 */
	public void setNr(Integer nr) {
		this.nr = nr;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column T_HCJH.XDRMC
	 * @return  the value of T_HCJH.XDRMC
	 * @mbggenerated  Mon Jun 13 13:09:37 CST 2016
	 */
	public String getXdrmc() {
		return xdrmc;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column T_HCJH.XDRMC
	 * @param xdrmc  the value for T_HCJH.XDRMC
	 * @mbggenerated  Mon Jun 13 13:09:37 CST 2016
	 */
	public void setXdrmc(String xdrmc) {
		this.xdrmc = xdrmc;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column T_HCJH.SHRMC
	 * @return  the value of T_HCJH.SHRMC
	 * @mbggenerated  Mon Jun 13 13:09:37 CST 2016
	 */
	public String getShrmc() {
		return shrmc;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column T_HCJH.SHRMC
	 * @param shrmc  the value for T_HCJH.SHRMC
	 * @mbggenerated  Mon Jun 13 13:09:37 CST 2016
	 */
	public void setShrmc(String shrmc) {
		this.shrmc = shrmc;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column T_HCJH.JHBH
	 * @return  the value of T_HCJH.JHBH
	 * @mbggenerated  Mon Jun 13 13:09:37 CST 2016
	 */
	public String getJhbh() {
		return jhbh;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column T_HCJH.JHBH
	 * @param jhbh  the value for T_HCJH.JHBH
	 * @mbggenerated  Mon Jun 13 13:09:37 CST 2016
	 */
	public void setJhbh(String jhbh) {
		this.jhbh = jhbh;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column T_HCJH.CXWH
	 * @return  the value of T_HCJH.CXWH
	 * @mbggenerated  Mon Jun 13 13:09:37 CST 2016
	 */
	public String getCxwh() {
		return cxwh;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column T_HCJH.CXWH
	 * @param cxwh  the value for T_HCJH.CXWH
	 * @mbggenerated  Mon Jun 13 13:09:37 CST 2016
	 */
	public void setCxwh(String cxwh) {
		this.cxwh = cxwh;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column T_HCJH.KSRQ
	 * @return  the value of T_HCJH.KSRQ
	 * @mbggenerated  Mon Jun 13 13:09:37 CST 2016
	 */
	public Date getKsrq() {
		return ksrq;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column T_HCJH.KSRQ
	 * @param ksrq  the value for T_HCJH.KSRQ
	 * @mbggenerated  Mon Jun 13 13:09:37 CST 2016
	 */
	public void setKsrq(Date ksrq) {
		this.ksrq = ksrq;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column T_HCJH.CLQSR
	 * @return  the value of T_HCJH.CLQSR
	 * @mbggenerated  Mon Jun 13 13:09:37 CST 2016
	 */
	public Date getClqsr() {
		return clqsr;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column T_HCJH.CLQSR
	 * @param clqsr  the value for T_HCJH.CLQSR
	 * @mbggenerated  Mon Jun 13 13:09:37 CST 2016
	 */
	public void setClqsr(Date clqsr) {
		this.clqsr = clqsr;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column T_HCJH.CLZZR
	 * @return  the value of T_HCJH.CLZZR
	 * @mbggenerated  Mon Jun 13 13:09:37 CST 2016
	 */
	public Date getClzzr() {
		return clzzr;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column T_HCJH.CLZZR
	 * @param clzzr  the value for T_HCJH.CLZZR
	 * @mbggenerated  Mon Jun 13 13:09:37 CST 2016
	 */
	public void setClzzr(Date clzzr) {
		this.clzzr = clzzr;
	}
}