package com.kysoft.cpsi.task.entity;

import java.util.Date;

public class HcrwRc {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GOV_NBCC_RC_QY.NBXH
     *
     * @mbggenerated Sun Jul 24 11:36:19 CST 2016
     */
    private String nbxh;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GOV_NBCC_RC_QY.ZCH
     *
     * @mbggenerated Sun Jul 24 11:36:19 CST 2016
     */
    private String zch;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GOV_NBCC_RC_QY.QYMC
     *
     * @mbggenerated Sun Jul 24 11:36:19 CST 2016
     */
    private String qymc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GOV_NBCC_RC_QY.FDDBR
     *
     * @mbggenerated Sun Jul 24 11:36:19 CST 2016
     */
    private String fddbr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GOV_NBCC_RC_QY.QYLXDL
     *
     * @mbggenerated Sun Jul 24 11:36:19 CST 2016
     */
    private String qylxdl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GOV_NBCC_RC_QY.DJJG
     *
     * @mbggenerated Sun Jul 24 11:36:19 CST 2016
     */
    private String djjg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GOV_NBCC_RC_QY.GXDW
     *
     * @mbggenerated Sun Jul 24 11:36:19 CST 2016
     */
    private String gxdw;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GOV_NBCC_RC_QY.QYZZXS
     *
     * @mbggenerated Sun Jul 24 11:36:19 CST 2016
     */
    private String qyzzxs;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GOV_NBCC_RC_QY.JDJG
     *
     * @mbggenerated Sun Jul 24 11:36:19 CST 2016
     */
    private String jdjg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GOV_NBCC_RC_QY.LRRQ
     *
     * @mbggenerated Sun Jul 24 11:36:19 CST 2016
     */
    private Date lrrq;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GOV_NBCC_RC_QY.LRSY
     *
     * @mbggenerated Sun Jul 24 11:36:19 CST 2016
     */
    private String lrsy;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GOV_NBCC_RC_QY.NBXH
     *
     * @return the value of GOV_NBCC_RC_QY.NBXH
     *
     * @mbggenerated Sun Jul 24 11:36:19 CST 2016
     */
    public String getNbxh() {
        return nbxh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GOV_NBCC_RC_QY.NBXH
     *
     * @param nbxh the value for GOV_NBCC_RC_QY.NBXH
     *
     * @mbggenerated Sun Jul 24 11:36:19 CST 2016
     */
    public void setNbxh(String nbxh) {
        this.nbxh = nbxh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GOV_NBCC_RC_QY.ZCH
     *
     * @return the value of GOV_NBCC_RC_QY.ZCH
     *
     * @mbggenerated Sun Jul 24 11:36:19 CST 2016
     */
    public String getZch() {
        return zch;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GOV_NBCC_RC_QY.ZCH
     *
     * @param zch the value for GOV_NBCC_RC_QY.ZCH
     *
     * @mbggenerated Sun Jul 24 11:36:19 CST 2016
     */
    public void setZch(String zch) {
        this.zch = zch;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GOV_NBCC_RC_QY.QYMC
     *
     * @return the value of GOV_NBCC_RC_QY.QYMC
     *
     * @mbggenerated Sun Jul 24 11:36:19 CST 2016
     */
    public String getQymc() {
        return qymc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GOV_NBCC_RC_QY.QYMC
     *
     * @param qymc the value for GOV_NBCC_RC_QY.QYMC
     *
     * @mbggenerated Sun Jul 24 11:36:19 CST 2016
     */
    public void setQymc(String qymc) {
        this.qymc = qymc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GOV_NBCC_RC_QY.FDDBR
     *
     * @return the value of GOV_NBCC_RC_QY.FDDBR
     *
     * @mbggenerated Sun Jul 24 11:36:19 CST 2016
     */
    public String getFddbr() {
        return fddbr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GOV_NBCC_RC_QY.FDDBR
     *
     * @param fddbr the value for GOV_NBCC_RC_QY.FDDBR
     *
     * @mbggenerated Sun Jul 24 11:36:19 CST 2016
     */
    public void setFddbr(String fddbr) {
        this.fddbr = fddbr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GOV_NBCC_RC_QY.QYLXDL
     *
     * @return the value of GOV_NBCC_RC_QY.QYLXDL
     *
     * @mbggenerated Sun Jul 24 11:36:19 CST 2016
     */
    public String getQylxdl() {
        return qylxdl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GOV_NBCC_RC_QY.QYLXDL
     *
     * @param qylxdl the value for GOV_NBCC_RC_QY.QYLXDL
     *
     * @mbggenerated Sun Jul 24 11:36:19 CST 2016
     */
    public void setQylxdl(String qylxdl) {
        this.qylxdl = qylxdl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GOV_NBCC_RC_QY.DJJG
     *
     * @return the value of GOV_NBCC_RC_QY.DJJG
     *
     * @mbggenerated Sun Jul 24 11:36:19 CST 2016
     */
    public String getDjjg() {
        return djjg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GOV_NBCC_RC_QY.DJJG
     *
     * @param djjg the value for GOV_NBCC_RC_QY.DJJG
     *
     * @mbggenerated Sun Jul 24 11:36:19 CST 2016
     */
    public void setDjjg(String djjg) {
        this.djjg = djjg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GOV_NBCC_RC_QY.GXDW
     *
     * @return the value of GOV_NBCC_RC_QY.GXDW
     *
     * @mbggenerated Sun Jul 24 11:36:19 CST 2016
     */
    public String getGxdw() {
        return gxdw;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GOV_NBCC_RC_QY.GXDW
     *
     * @param gxdw the value for GOV_NBCC_RC_QY.GXDW
     *
     * @mbggenerated Sun Jul 24 11:36:19 CST 2016
     */
    public void setGxdw(String gxdw) {
        this.gxdw = gxdw;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GOV_NBCC_RC_QY.QYZZXS
     *
     * @return the value of GOV_NBCC_RC_QY.QYZZXS
     *
     * @mbggenerated Sun Jul 24 11:36:19 CST 2016
     */
    public String getQyzzxs() {
        return qyzzxs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GOV_NBCC_RC_QY.QYZZXS
     *
     * @param qyzzxs the value for GOV_NBCC_RC_QY.QYZZXS
     *
     * @mbggenerated Sun Jul 24 11:36:19 CST 2016
     */
    public void setQyzzxs(String qyzzxs) {
        this.qyzzxs = qyzzxs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GOV_NBCC_RC_QY.JDJG
     *
     * @return the value of GOV_NBCC_RC_QY.JDJG
     *
     * @mbggenerated Sun Jul 24 11:36:19 CST 2016
     */
    public String getJdjg() {
        return jdjg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GOV_NBCC_RC_QY.JDJG
     *
     * @param jdjg the value for GOV_NBCC_RC_QY.JDJG
     *
     * @mbggenerated Sun Jul 24 11:36:19 CST 2016
     */
    public void setJdjg(String jdjg) {
        this.jdjg = jdjg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GOV_NBCC_RC_QY.LRRQ
     *
     * @return the value of GOV_NBCC_RC_QY.LRRQ
     *
     * @mbggenerated Sun Jul 24 11:36:19 CST 2016
     */
    public Date getLrrq() {
        return lrrq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GOV_NBCC_RC_QY.LRRQ
     *
     * @param lrrq the value for GOV_NBCC_RC_QY.LRRQ
     *
     * @mbggenerated Sun Jul 24 11:36:19 CST 2016
     */
    public void setLrrq(Date lrrq) {
        this.lrrq = lrrq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GOV_NBCC_RC_QY.LRSY
     *
     * @return the value of GOV_NBCC_RC_QY.LRSY
     *
     * @mbggenerated Sun Jul 24 11:36:19 CST 2016
     */
    public String getLrsy() {
        return lrsy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GOV_NBCC_RC_QY.LRSY
     *
     * @param lrsy the value for GOV_NBCC_RC_QY.LRSY
     *
     * @mbggenerated Sun Jul 24 11:36:19 CST 2016
     */
    public void setLrsy(String lrsy) {
        this.lrsy = lrsy;
    }
}