package com.kysoft.cpsi.task.entity;

public class HcrwTjKey {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column T_HCRW_TJ.HCJH_ID
	 * @mbggenerated  Mon May 23 09:16:18 CST 2016
	 */
	private String hcjhId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column T_HCRW_TJ.ZFRY_CODE
	 * @mbggenerated  Mon May 23 09:16:18 CST 2016
	 */
	private String zfryCode;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column T_HCRW_TJ.HCJH_ID
	 * @return  the value of T_HCRW_TJ.HCJH_ID
	 * @mbggenerated  Mon May 23 09:16:18 CST 2016
	 */
	public String getHcjhId() {
		return hcjhId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column T_HCRW_TJ.HCJH_ID
	 * @param hcjhId  the value for T_HCRW_TJ.HCJH_ID
	 * @mbggenerated  Mon May 23 09:16:18 CST 2016
	 */
	public void setHcjhId(String hcjhId) {
		this.hcjhId = hcjhId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column T_HCRW_TJ.ZFRY_CODE
	 * @return  the value of T_HCRW_TJ.ZFRY_CODE
	 * @mbggenerated  Mon May 23 09:16:18 CST 2016
	 */
	public String getZfryCode() {
		return zfryCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column T_HCRW_TJ.ZFRY_CODE
	 * @param zfryCode  the value for T_HCRW_TJ.ZFRY_CODE
	 * @mbggenerated  Mon May 23 09:16:18 CST 2016
	 */
	public void setZfryCode(String zfryCode) {
		this.zfryCode = zfryCode;
	}
}