package com.kysoft.cpsi.task.entity;

import java.util.Date;

public class Hcrw {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_HCRW.ID
     *
     * @mbggenerated Fri May 20 11:38:53 CST 2016
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_HCRW.HCJH_ID
     *
     * @mbggenerated Fri May 20 11:38:53 CST 2016
     */
    private String hcjhId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_HCRW.HCDW_XYDM
     *
     * @mbggenerated Fri May 20 11:38:53 CST 2016
     */
    private String hcdwXydm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_HCRW.HCDW_NAME
     *
     * @mbggenerated Fri May 20 11:38:53 CST 2016
     */
    private String hcdwName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_HCRW.ZFRY_CODE1
     *
     * @mbggenerated Fri May 20 11:38:53 CST 2016
     */
    private String zfryCode1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_HCRW.ZFRY_CODE2
     *
     * @mbggenerated Fri May 20 11:38:53 CST 2016
     */
    private String zfryCode2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_HCRW.RWZT
     *
     * @mbggenerated Fri May 20 11:38:53 CST 2016
     */
    private Integer rwzt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_HCRW.HCFL
     *
     * @mbggenerated Fri May 20 11:38:53 CST 2016
     */
    private Integer hcfl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_HCRW.HCJIGUAN
     *
     * @mbggenerated Fri May 20 11:38:53 CST 2016
     */
    private String hcjiguan;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_HCRW.HCJIEGUO
     *
     * @mbggenerated Fri May 20 11:38:53 CST 2016
     */
    private Integer hcjieguo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_HCRW.JYZT
     *
     * @mbggenerated Fri May 20 11:38:53 CST 2016
     */
    private Integer jyzt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_HCRW.HCJGGSQK
     *
     * @mbggenerated Fri May 20 11:38:53 CST 2016
     */
    private Integer hcjggsqk;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_HCRW.RLR
     *
     * @mbggenerated Fri May 20 11:38:53 CST 2016
     */
    private String rlr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_HCRW.RLRQ
     *
     * @mbggenerated Fri May 20 11:38:53 CST 2016
     */
    private Date rlrq;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_HCRW.WCRQ
     *
     * @mbggenerated Fri May 20 11:38:53 CST 2016
     */
    private Date wcrq;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_HCRW.ID
     *
     * @return the value of T_HCRW.ID
     *
     * @mbggenerated Fri May 20 11:38:53 CST 2016
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_HCRW.ID
     *
     * @param id the value for T_HCRW.ID
     *
     * @mbggenerated Fri May 20 11:38:53 CST 2016
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_HCRW.HCJH_ID
     *
     * @return the value of T_HCRW.HCJH_ID
     *
     * @mbggenerated Fri May 20 11:38:53 CST 2016
     */
    public String getHcjhId() {
        return hcjhId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_HCRW.HCJH_ID
     *
     * @param hcjhId the value for T_HCRW.HCJH_ID
     *
     * @mbggenerated Fri May 20 11:38:53 CST 2016
     */
    public void setHcjhId(String hcjhId) {
        this.hcjhId = hcjhId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_HCRW.HCDW_XYDM
     *
     * @return the value of T_HCRW.HCDW_XYDM
     *
     * @mbggenerated Fri May 20 11:38:53 CST 2016
     */
    public String getHcdwXydm() {
        return hcdwXydm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_HCRW.HCDW_XYDM
     *
     * @param hcdwXydm the value for T_HCRW.HCDW_XYDM
     *
     * @mbggenerated Fri May 20 11:38:53 CST 2016
     */
    public void setHcdwXydm(String hcdwXydm) {
        this.hcdwXydm = hcdwXydm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_HCRW.HCDW_NAME
     *
     * @return the value of T_HCRW.HCDW_NAME
     *
     * @mbggenerated Fri May 20 11:38:53 CST 2016
     */
    public String getHcdwName() {
        return hcdwName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_HCRW.HCDW_NAME
     *
     * @param hcdwName the value for T_HCRW.HCDW_NAME
     *
     * @mbggenerated Fri May 20 11:38:53 CST 2016
     */
    public void setHcdwName(String hcdwName) {
        this.hcdwName = hcdwName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_HCRW.ZFRY_CODE1
     *
     * @return the value of T_HCRW.ZFRY_CODE1
     *
     * @mbggenerated Fri May 20 11:38:53 CST 2016
     */
    public String getZfryCode1() {
        return zfryCode1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_HCRW.ZFRY_CODE1
     *
     * @param zfryCode1 the value for T_HCRW.ZFRY_CODE1
     *
     * @mbggenerated Fri May 20 11:38:53 CST 2016
     */
    public void setZfryCode1(String zfryCode1) {
        this.zfryCode1 = zfryCode1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_HCRW.ZFRY_CODE2
     *
     * @return the value of T_HCRW.ZFRY_CODE2
     *
     * @mbggenerated Fri May 20 11:38:53 CST 2016
     */
    public String getZfryCode2() {
        return zfryCode2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_HCRW.ZFRY_CODE2
     *
     * @param zfryCode2 the value for T_HCRW.ZFRY_CODE2
     *
     * @mbggenerated Fri May 20 11:38:53 CST 2016
     */
    public void setZfryCode2(String zfryCode2) {
        this.zfryCode2 = zfryCode2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_HCRW.RWZT
     *
     * @return the value of T_HCRW.RWZT
     *
     * @mbggenerated Fri May 20 11:38:53 CST 2016
     */
    public Integer getRwzt() {
        return rwzt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_HCRW.RWZT
     *
     * @param rwzt the value for T_HCRW.RWZT
     *
     * @mbggenerated Fri May 20 11:38:53 CST 2016
     */
    public void setRwzt(Integer rwzt) {
        this.rwzt = rwzt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_HCRW.HCFL
     *
     * @return the value of T_HCRW.HCFL
     *
     * @mbggenerated Fri May 20 11:38:53 CST 2016
     */
    public Integer getHcfl() {
        return hcfl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_HCRW.HCFL
     *
     * @param hcfl the value for T_HCRW.HCFL
     *
     * @mbggenerated Fri May 20 11:38:53 CST 2016
     */
    public void setHcfl(Integer hcfl) {
        this.hcfl = hcfl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_HCRW.HCJIGUAN
     *
     * @return the value of T_HCRW.HCJIGUAN
     *
     * @mbggenerated Fri May 20 11:38:53 CST 2016
     */
    public String getHcjiguan() {
        return hcjiguan;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_HCRW.HCJIGUAN
     *
     * @param hcjiguan the value for T_HCRW.HCJIGUAN
     *
     * @mbggenerated Fri May 20 11:38:53 CST 2016
     */
    public void setHcjiguan(String hcjiguan) {
        this.hcjiguan = hcjiguan;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_HCRW.HCJIEGUO
     *
     * @return the value of T_HCRW.HCJIEGUO
     *
     * @mbggenerated Fri May 20 11:38:53 CST 2016
     */
    public Integer getHcjieguo() {
        return hcjieguo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_HCRW.HCJIEGUO
     *
     * @param hcjieguo the value for T_HCRW.HCJIEGUO
     *
     * @mbggenerated Fri May 20 11:38:53 CST 2016
     */
    public void setHcjieguo(Integer hcjieguo) {
        this.hcjieguo = hcjieguo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_HCRW.JYZT
     *
     * @return the value of T_HCRW.JYZT
     *
     * @mbggenerated Fri May 20 11:38:53 CST 2016
     */
    public Integer getJyzt() {
        return jyzt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_HCRW.JYZT
     *
     * @param jyzt the value for T_HCRW.JYZT
     *
     * @mbggenerated Fri May 20 11:38:53 CST 2016
     */
    public void setJyzt(Integer jyzt) {
        this.jyzt = jyzt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_HCRW.HCJGGSQK
     *
     * @return the value of T_HCRW.HCJGGSQK
     *
     * @mbggenerated Fri May 20 11:38:53 CST 2016
     */
    public Integer getHcjggsqk() {
        return hcjggsqk;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_HCRW.HCJGGSQK
     *
     * @param hcjggsqk the value for T_HCRW.HCJGGSQK
     *
     * @mbggenerated Fri May 20 11:38:53 CST 2016
     */
    public void setHcjggsqk(Integer hcjggsqk) {
        this.hcjggsqk = hcjggsqk;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_HCRW.RLR
     *
     * @return the value of T_HCRW.RLR
     *
     * @mbggenerated Fri May 20 11:38:53 CST 2016
     */
    public String getRlr() {
        return rlr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_HCRW.RLR
     *
     * @param rlr the value for T_HCRW.RLR
     *
     * @mbggenerated Fri May 20 11:38:53 CST 2016
     */
    public void setRlr(String rlr) {
        this.rlr = rlr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_HCRW.RLRQ
     *
     * @return the value of T_HCRW.RLRQ
     *
     * @mbggenerated Fri May 20 11:38:53 CST 2016
     */
    public Date getRlrq() {
        return rlrq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_HCRW.RLRQ
     *
     * @param rlrq the value for T_HCRW.RLRQ
     *
     * @mbggenerated Fri May 20 11:38:53 CST 2016
     */
    public void setRlrq(Date rlrq) {
        this.rlrq = rlrq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_HCRW.WCRQ
     *
     * @return the value of T_HCRW.WCRQ
     *
     * @mbggenerated Fri May 20 11:38:53 CST 2016
     */
    public Date getWcrq() {
        return wcrq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_HCRW.WCRQ
     *
     * @param wcrq the value for T_HCRW.WCRQ
     *
     * @mbggenerated Fri May 20 11:38:53 CST 2016
     */
    public void setWcrq(Date wcrq) {
        this.wcrq = wcrq;
    }
}