package com.kysoft.cpsi.task.entity;

public class Hcsxjg extends HcsxjgKey {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column T_HCSXJG.NAME
	 * @mbggenerated  Thu Jun 02 15:44:07 CST 2016
	 */
	private String name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column T_HCSXJG.HCJG
	 * @mbggenerated  Thu Jun 02 15:44:07 CST 2016
	 */
	private Integer hcjg;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column T_HCSXJG.HCFS
	 * @mbggenerated  Thu Jun 02 15:44:07 CST 2016
	 */
	private Integer hcfs;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column T_HCSXJG.QYGSNR
	 * @mbggenerated  Thu Jun 02 15:44:07 CST 2016
	 */
	private String qygsnr;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column T_HCSXJG.BZNR
	 * @mbggenerated  Thu Jun 02 15:44:07 CST 2016
	 */
	private String bznr;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column T_HCSXJG.HCZT
	 * @mbggenerated  Thu Jun 02 15:44:07 CST 2016
	 */
	private Integer hczt;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column T_HCSXJG.SM
	 * @mbggenerated  Thu Jun 02 15:44:07 CST 2016
	 */
	private String sm;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column T_HCSXJG.PAGE
	 * @mbggenerated  Thu Jun 02 15:44:07 CST 2016
	 */
	private String page;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column T_HCSXJG.HCLX
	 * @mbggenerated  Thu Jun 02 15:44:07 CST 2016
	 */
	private Integer hclx;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column T_HCSXJG.NAME
	 * @return  the value of T_HCSXJG.NAME
	 * @mbggenerated  Thu Jun 02 15:44:07 CST 2016
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column T_HCSXJG.NAME
	 * @param name  the value for T_HCSXJG.NAME
	 * @mbggenerated  Thu Jun 02 15:44:07 CST 2016
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column T_HCSXJG.HCJG
	 * @return  the value of T_HCSXJG.HCJG
	 * @mbggenerated  Thu Jun 02 15:44:07 CST 2016
	 */
	public Integer getHcjg() {
		return hcjg;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column T_HCSXJG.HCJG
	 * @param hcjg  the value for T_HCSXJG.HCJG
	 * @mbggenerated  Thu Jun 02 15:44:07 CST 2016
	 */
	public void setHcjg(Integer hcjg) {
		this.hcjg = hcjg;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column T_HCSXJG.HCFS
	 * @return  the value of T_HCSXJG.HCFS
	 * @mbggenerated  Thu Jun 02 15:44:07 CST 2016
	 */
	public Integer getHcfs() {
		return hcfs;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column T_HCSXJG.HCFS
	 * @param hcfs  the value for T_HCSXJG.HCFS
	 * @mbggenerated  Thu Jun 02 15:44:07 CST 2016
	 */
	public void setHcfs(Integer hcfs) {
		this.hcfs = hcfs;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column T_HCSXJG.QYGSNR
	 * @return  the value of T_HCSXJG.QYGSNR
	 * @mbggenerated  Thu Jun 02 15:44:07 CST 2016
	 */
	public String getQygsnr() {
		return qygsnr;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column T_HCSXJG.QYGSNR
	 * @param qygsnr  the value for T_HCSXJG.QYGSNR
	 * @mbggenerated  Thu Jun 02 15:44:07 CST 2016
	 */
	public void setQygsnr(String qygsnr) {
		this.qygsnr = qygsnr;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column T_HCSXJG.BZNR
	 * @return  the value of T_HCSXJG.BZNR
	 * @mbggenerated  Thu Jun 02 15:44:07 CST 2016
	 */
	public String getBznr() {
		return bznr;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column T_HCSXJG.BZNR
	 * @param bznr  the value for T_HCSXJG.BZNR
	 * @mbggenerated  Thu Jun 02 15:44:07 CST 2016
	 */
	public void setBznr(String bznr) {
		this.bznr = bznr;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column T_HCSXJG.HCZT
	 * @return  the value of T_HCSXJG.HCZT
	 * @mbggenerated  Thu Jun 02 15:44:07 CST 2016
	 */
	public Integer getHczt() {
		return hczt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column T_HCSXJG.HCZT
	 * @param hczt  the value for T_HCSXJG.HCZT
	 * @mbggenerated  Thu Jun 02 15:44:07 CST 2016
	 */
	public void setHczt(Integer hczt) {
		this.hczt = hczt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column T_HCSXJG.SM
	 * @return  the value of T_HCSXJG.SM
	 * @mbggenerated  Thu Jun 02 15:44:07 CST 2016
	 */
	public String getSm() {
		return sm;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column T_HCSXJG.SM
	 * @param sm  the value for T_HCSXJG.SM
	 * @mbggenerated  Thu Jun 02 15:44:07 CST 2016
	 */
	public void setSm(String sm) {
		this.sm = sm;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column T_HCSXJG.PAGE
	 * @return  the value of T_HCSXJG.PAGE
	 * @mbggenerated  Thu Jun 02 15:44:07 CST 2016
	 */
	public String getPage() {
		return page;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column T_HCSXJG.PAGE
	 * @param page  the value for T_HCSXJG.PAGE
	 * @mbggenerated  Thu Jun 02 15:44:07 CST 2016
	 */
	public void setPage(String page) {
		this.page = page;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column T_HCSXJG.HCLX
	 * @return  the value of T_HCSXJG.HCLX
	 * @mbggenerated  Thu Jun 02 15:44:07 CST 2016
	 */
	public Integer getHclx() {
		return hclx;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column T_HCSXJG.HCLX
	 * @param hclx  the value for T_HCSXJG.HCLX
	 * @mbggenerated  Thu Jun 02 15:44:07 CST 2016
	 */
	public void setHclx(Integer hclx) {
		this.hclx = hclx;
	}

	private Integer hcxxfl;

	public Integer getHcxxfl() {
		return hcxxfl;
	}

	public void setHcxxfl(Integer hcxxfl) {
		this.hcxxfl = hcxxfl;
	}
}