package com.kysoft.cpsi.task.entity;

public class HcsxjgKey {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column T_HCSXJG.HCSX_ID
	 * @mbggenerated  Wed May 25 08:28:56 CST 2016
	 */
	private String hcsxId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column T_HCSXJG.HCRW_ID
	 * @mbggenerated  Wed May 25 08:28:56 CST 2016
	 */
	private String hcrwId;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column T_HCSXJG.HCSX_ID
	 * @return  the value of T_HCSXJG.HCSX_ID
	 * @mbggenerated  Wed May 25 08:28:56 CST 2016
	 */
	public String getHcsxId() {
		return hcsxId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column T_HCSXJG.HCSX_ID
	 * @param hcsxId  the value for T_HCSXJG.HCSX_ID
	 * @mbggenerated  Wed May 25 08:28:56 CST 2016
	 */
	public void setHcsxId(String hcsxId) {
		this.hcsxId = hcsxId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column T_HCSXJG.HCRW_ID
	 * @return  the value of T_HCSXJG.HCRW_ID
	 * @mbggenerated  Wed May 25 08:28:56 CST 2016
	 */
	public String getHcrwId() {
		return hcrwId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column T_HCSXJG.HCRW_ID
	 * @param hcrwId  the value for T_HCSXJG.HCRW_ID
	 * @mbggenerated  Wed May 25 08:28:56 CST 2016
	 */
	public void setHcrwId(String hcrwId) {
		this.hcrwId = hcrwId;
	}
}