package com.kysoft.cpsi.zcb.mapper;

import com.kysoft.cpsi.zcb.entity.SctXjllb;
import com.kysoft.cpsi.zcb.entity.SctXjllbKey;

public interface SctXjllbMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SCT_XJLLB
     *
     * @mbg.generated Tue Jan 03 14:17:25 CST 2017
     */
    int deleteByPrimaryKey(SctXjllbKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SCT_XJLLB
     *
     * @mbg.generated Tue Jan 03 14:17:25 CST 2017
     */
    int insert(SctXjllb record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SCT_XJLLB
     *
     * @mbg.generated Tue Jan 03 14:17:25 CST 2017
     */
    int insertSelective(SctXjllb record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SCT_XJLLB
     *
     * @mbg.generated Tue Jan 03 14:17:25 CST 2017
     */
    SctXjllb selectByPrimaryKey(SctXjllbKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SCT_XJLLB
     *
     * @mbg.generated Tue Jan 03 14:17:25 CST 2017
     */
    int updateByPrimaryKeySelective(SctXjllb record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SCT_XJLLB
     *
     * @mbg.generated Tue Jan 03 14:17:25 CST 2017
     */
    int updateByPrimaryKey(SctXjllb record);
}