package com.kysoft.kteam.leave.domain;

import java.util.Date;

public class Leave {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column LEAVE.ID
	 * @mbggenerated  Thu Jul 23 14:49:39 CST 2015
	 */
	private String id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column LEAVE.LEAVE_TYPE
	 * @mbggenerated  Thu Jul 23 14:49:39 CST 2015
	 */
	private Integer leaveType;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column LEAVE.START_DATE
	 * @mbggenerated  Thu Jul 23 14:49:39 CST 2015
	 */
	private Date startDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column LEAVE.END_DATE
	 * @mbggenerated  Thu Jul 23 14:49:39 CST 2015
	 */
	private Date endDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column LEAVE.REASON
	 * @mbggenerated  Thu Jul 23 14:49:39 CST 2015
	 */
	private String reason;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column LEAVE.PROPOSER
	 * @mbggenerated  Thu Jul 23 14:49:39 CST 2015
	 */
	private String proposer;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column LEAVE.PROCESS_INSTANCE_ID
	 * @mbggenerated  Thu Jul 23 14:49:39 CST 2015
	 */
	private String processInstanceId;

	private Integer processStatus;

	private Date processStartTime;
	
	private Date processEndTime;
	
	
	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column LEAVE.ID
	 * @return  the value of LEAVE.ID
	 * @mbggenerated  Thu Jul 23 14:49:39 CST 2015
	 */
	public String getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column LEAVE.ID
	 * @param id  the value for LEAVE.ID
	 * @mbggenerated  Thu Jul 23 14:49:39 CST 2015
	 */
	public void setId(String id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column LEAVE.LEAVE_TYPE
	 * @return  the value of LEAVE.LEAVE_TYPE
	 * @mbggenerated  Thu Jul 23 14:49:39 CST 2015
	 */
	public Integer getLeaveType() {
		return leaveType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column LEAVE.LEAVE_TYPE
	 * @param leaveType  the value for LEAVE.LEAVE_TYPE
	 * @mbggenerated  Thu Jul 23 14:49:39 CST 2015
	 */
	public void setLeaveType(Integer leaveType) {
		this.leaveType = leaveType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column LEAVE.START_DATE
	 * @return  the value of LEAVE.START_DATE
	 * @mbggenerated  Thu Jul 23 14:49:39 CST 2015
	 */
	public Date getStartDate() {
		return startDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column LEAVE.START_DATE
	 * @param startDate  the value for LEAVE.START_DATE
	 * @mbggenerated  Thu Jul 23 14:49:39 CST 2015
	 */
	public void setStartDate(Date startDate) {
		this.startDate = startDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column LEAVE.END_DATE
	 * @return  the value of LEAVE.END_DATE
	 * @mbggenerated  Thu Jul 23 14:49:39 CST 2015
	 */
	public Date getEndDate() {
		return endDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column LEAVE.END_DATE
	 * @param endDate  the value for LEAVE.END_DATE
	 * @mbggenerated  Thu Jul 23 14:49:39 CST 2015
	 */
	public void setEndDate(Date endDate) {
		this.endDate = endDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column LEAVE.REASON
	 * @return  the value of LEAVE.REASON
	 * @mbggenerated  Thu Jul 23 14:49:39 CST 2015
	 */
	public String getReason() {
		return reason;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column LEAVE.REASON
	 * @param reason  the value for LEAVE.REASON
	 * @mbggenerated  Thu Jul 23 14:49:39 CST 2015
	 */
	public void setReason(String reason) {
		this.reason = reason;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column LEAVE.PROPOSER
	 * @return  the value of LEAVE.PROPOSER
	 * @mbggenerated  Thu Jul 23 14:49:39 CST 2015
	 */
	public String getProposer() {
		return proposer;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column LEAVE.PROPOSER
	 * @param proposer  the value for LEAVE.PROPOSER
	 * @mbggenerated  Thu Jul 23 14:49:39 CST 2015
	 */
	public void setProposer(String proposer) {
		this.proposer = proposer;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column LEAVE.PROCESS_INSTANCE_ID
	 * @return  the value of LEAVE.PROCESS_INSTANCE_ID
	 * @mbggenerated  Thu Jul 23 14:49:39 CST 2015
	 */
	public String getProcessInstanceId() {
		return processInstanceId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column LEAVE.PROCESS_INSTANCE_ID
	 * @param processInstanceId  the value for LEAVE.PROCESS_INSTANCE_ID
	 * @mbggenerated  Thu Jul 23 14:49:39 CST 2015
	 */
	public void setProcessInstanceId(String processInstanceId) {
		this.processInstanceId = processInstanceId;
	}

	public Integer getProcessStatus() {
		return processStatus;
	}

	public void setProcessStatus(Integer processStatus) {
		this.processStatus = processStatus;
	}

	public Date getProcessStartTime() {
		return processStartTime;
	}

	public void setProcessStartTime(Date processStartTime) {
		this.processStartTime = processStartTime;
	}

	public Date getProcessEndTime() {
		return processEndTime;
	}

	public void setProcessEndTime(Date processEndTime) {
		this.processEndTime = processEndTime;
	}
	
}